In [1]:
from prediction import prediction

# players_teams = {
#     "Cade Cunningham": "WAS",
#     "Jordan Poole": "WAS",
#     "Malik Beasley": "DET",
#     "Jalen Duren": "DET",
#     "Tobias Harris": "DET",
#     "Alex Sarr": "WAS",
#     "Corey Kispert": "WAS",
#     "Khris Middleton": "WAS",
#     "Ausar Thompson": "DET",
#     "Dennis Schroder": "DET",
#     "Kyshawn George": "WAS",
#     "Tim Hardaway Jr.": "DET",
#     "Richaun Holmes": "WAS",
#     "Marcus Smart": "WAS",
#     "Isaiah Stewart": "DET",
#     "Luka Doncic": "LAL",
#     "Giannis Antetokounmpo": "MIL",
#     "Damian Lillard": "MIL",
#     "Austin Reaves": "LAL",
#     "Kyle Kuzma": "MIL",
#     "Dalton Knecht": "LAL",
#     "Brook Lopez": "MIL",
#     "Gabe Vincent": "LAL",
#     "Dorian Finney-Smith": "LAL",
#     "Taurean Prince": "MIL",
#     "Jarred Vanderbilt": "LAL",
#     "Paolo Banchero": "ORL",
#     "Franz Wagner": "ORL",
#     "Zion Williamson": "NOP",
#     "CJ McCollum": "NOP",
#     "Trey Murphy III": "NOP",
#     "Cole Anthony": "ORL",
#     "Kentavious Caldwell-Pope": "ORL",
#     "Yves Missi": "NOP",
#     "Cam Thomas": "BKN",
#     "Coby White": "CHI",
#     "Cameron Johnson": "BKN",
#     "Kevin Huerter": "BKN",
#     "Matas Buzelis": "CHI",
#     "D'Angelo Russell": "BKN",
#     "Nikola Vucevic": "CHI",
#     "Tre Jones": "BKN",
#     "Zach Collins": "BKN",
#     "Nic Claxton": "BKN",
#     "Ziaire Williams": "BKN",
#     "Keon Johnson": "BKN",
#     "Day'Ron Sharpe": "BKN",
#     "Stephen Curry": "GSW",
#     "Zach LaVine": "SAC",
#     "DeMar DeRozan": "SAC",
#     "Jimmy Butler": "GSW",
#     "Malik Monk": "SAC",
#     "Domantas Sabonis": "SAC",
#     "Keegan Murray": "SAC",
#     "Moses Moody": "GSW",
#     "Buddy Hield": "GSW",
#     "Quinten Post": "GSW",
#     "Draymond Green": "GSW",
#     "Keon Ellis": "SAC"
# }



players_teams = {
    "Coby White": "CHI",
    "Kevin Huerter": "CHI",
    "Tre Jones": "CHI",
    "Matas Buzelis": "CHI",
    "Nikola Vucevic": "CHI",
    "Jalen Green": "HOU",
    "Dillon Brooks": "HOU",
    "Fred VanVleet": "HOU",
    "Jabari Smith Jr.": "HOU",
    "Alperen Sengun": "HOU",
    "Duncan Robinson": "MIA",
    "Jaime Jaquez Jr.": "MIA",
    "Tyler Herro": "MIA",
    "Andrew Wiggins": "MIA",
    "Bam Adebayo": "MIA",
    "Desmond Bane": "MEM",
    "Jaylen Wells": "MEM",
    "Ja Morant": "MEM",
    "Jaren Jackson Jr.": "MEM",
    "Zach Edey": "MEM",
    "Andrew Nembhard": "IND",
    "Aaron Nesmith": "IND",
    "Tyrese Haliburton": "IND",
    "Pascal Siakam": "IND",
    "Myles Turner": "IND",
    "Taurean Prince": "MIL",
    "Kyle Kuzma": "MIL",
    "Damian Lillard": "MIL",
    "Giannis Antetokounmpo": "MIL",
    "Brook Lopez": "MIL",
    "Mikal Bridges": "NYK",
    "Josh Hart": "NYK",
    "Miles McBride": "NYK",
    "OG Anunoby": "NYK",
    "Karl-Anthony Towns": "NYK",
    "Moses Moody": "GSW",
    "Jimmy Butler III": "GSW",
    "Stephen Curry": "GSW",
    "Draymond Green": "GSW",
    "Quinten Post": "GSW",
    "Khris Middleton": "WAS",
    "Justin Champagnie": "WAS",
    "Jordan Poole": "WAS",
    "Kyshawn George": "WAS",
    "Alex Sarr": "WAS",
    "Christian Braun": "DEN",
    "Michael Porter Jr.": "DEN",
    "Jamal Murray": "DEN",
    "Aaron Gordon": "DEN",
    "Nikola Jokic": "DEN"
}




# remember to run mover
# remember to check schedule csv
import pandas as pd
date_list = ["2022-23","2023-24","2024-25"]
stats_path = {
    'usage_path':'D:/nba_usage_csv_historic/usage_csv_{date}/{date}_content.csv',
    'catch_shoot':"D:/nba_tracking_data_csv/nba_csv_{date}/catch_shoot_content.csv",
    'drives':"D:/nba_tracking_data_csv/nba_csv_{date}/drives_content.csv",
    'elbow_touches':"D:/nba_tracking_data_csv/nba_csv_{date}/elbow_touch_content.csv",
    'paint_touches':"D:/nba_tracking_data_csv/nba_csv_{date}/paint_touch_content.csv",
    'passing':"D:/nba_tracking_data_csv/nba_csv_{date}/passing_content.csv",
    'pullup':"D:/nba_tracking_data_csv/nba_csv_{date}/pullup_content.csv",
    'shooting_efficiency':"D:/nba_tracking_data_csv/nba_csv_{date}/shooting_efficiency_content.csv",
    'touches':"D:/nba_tracking_data_csv/nba_csv_{date}/touches_content.csv",
    'tracking_post_ups_content':"D:/nba_tracking_data_csv/nba_csv_{date}/tracking_post_ups_content.csv"
}
schedule_base_path = "D:/nba_scheduled_csv/schedule_csv_2025/{schedule_team}_schedule_content.csv"
player_base_path = "D:/nba_player_csv_historic/season_{date}/all_quarters/{player}_content.csv"
defense_base_path = "D:/nba_defense_history_csv/defense_csv_{date}/all_quarter_defense_content.csv"

results_reb = prediction(players_teams, date_list, stats_path, player_base_path, defense_base_path, schedule_base_path,'REB','REB')
results_ast = prediction(players_teams, date_list, stats_path, player_base_path, defense_base_path, schedule_base_path,'AST','AST')
results_pts = prediction(players_teams, date_list, stats_path, player_base_path, defense_base_path, schedule_base_path,'PTS','PTS')
results_3pm = prediction(players_teams, date_list, stats_path, player_base_path, defense_base_path, schedule_base_path,'3PM','3PM')
results_pts = results_pts.rename(columns={'FGA': 'PTS'})



# display(results_reb)
# display(results_ast)
# display(results_pts)
# display(results_3pm)

Player data missing for Matas Buzelis on 2022-23, skipping.
Skipping merge for Matas Buzelis on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Matas Buzelis on 2023-24, skipping.
Skipping merge for Matas Buzelis on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jaime Jaquez Jr. on 2022-23, skipping.
Skipping merge for Jaime Jaquez Jr. on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Wells on 2022-23, skipping.
Skipping merge for Jaylen Wells on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Wells on 2023-24, skipping.
Skipping merge for Jaylen Wells on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zach Edey on 2022-23, skipping.
Skipping merge for Zach Edey on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Zach Edey on 2023-24, skipping.
Skipping merge for Zach Edey on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Quinten Post on 2022-23, skipping.
Skipping merge for Quinten Post on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Quinten Post on 2023-24, skipping.
Skipping merge for Quinten Post on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Justin Champagnie on 2022-23, skipping.
Skipping merge for Justin Champagnie on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Kyshawn George on 2022-23, skipping.
Skipping merge for Kyshawn George on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Kyshawn George on 2023-24, skipping.
Skipping merge for Kyshawn George on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Alex Sarr on 2022-23, skipping.
Skipping merge for Alex Sarr on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Alex Sarr on 2023-24, skipping.
Skipping merge for Alex Sarr on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Matas Buzelis on 2022-23, skipping.
Skipping merge for Matas Buzelis on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Matas Buzelis on 2023-24, skipping.
Skipping merge for Matas Buzelis on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jaime Jaquez Jr. on 2022-23, skipping.
Skipping merge for Jaime Jaquez Jr. on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Wells on 2022-23, skipping.
Skipping merge for Jaylen Wells on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Wells on 2023-24, skipping.
Skipping merge for Jaylen Wells on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zach Edey on 2022-23, skipping.
Skipping merge for Zach Edey on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Zach Edey on 2023-24, skipping.
Skipping merge for Zach Edey on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Quinten Post on 2022-23, skipping.
Skipping merge for Quinten Post on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Quinten Post on 2023-24, skipping.
Skipping merge for Quinten Post on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Justin Champagnie on 2022-23, skipping.
Skipping merge for Justin Champagnie on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Kyshawn George on 2022-23, skipping.
Skipping merge for Kyshawn George on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Kyshawn George on 2023-24, skipping.
Skipping merge for Kyshawn George on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Alex Sarr on 2022-23, skipping.
Skipping merge for Alex Sarr on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Alex Sarr on 2023-24, skipping.
Skipping merge for Alex Sarr on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Matas Buzelis on 2022-23, skipping.
Skipping merge for Matas Buzelis on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Matas Buzelis on 2023-24, skipping.
Skipping merge for Matas Buzelis on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jaime Jaquez Jr. on 2022-23, skipping.
Skipping merge for Jaime Jaquez Jr. on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Wells on 2022-23, skipping.
Skipping merge for Jaylen Wells on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Wells on 2023-24, skipping.
Skipping merge for Jaylen Wells on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zach Edey on 2022-23, skipping.
Skipping merge for Zach Edey on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Zach Edey on 2023-24, skipping.
Skipping merge for Zach Edey on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Quinten Post on 2022-23, skipping.
Skipping merge for Quinten Post on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Quinten Post on 2023-24, skipping.
Skipping merge for Quinten Post on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Justin Champagnie on 2022-23, skipping.
Skipping merge for Justin Champagnie on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Kyshawn George on 2022-23, skipping.
Skipping merge for Kyshawn George on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Kyshawn George on 2023-24, skipping.
Skipping merge for Kyshawn George on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Alex Sarr on 2022-23, skipping.
Skipping merge for Alex Sarr on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Alex Sarr on 2023-24, skipping.
Skipping merge for Alex Sarr on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Matas Buzelis on 2022-23, skipping.
Skipping merge for Matas Buzelis on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Matas Buzelis on 2023-24, skipping.
Skipping merge for Matas Buzelis on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jaime Jaquez Jr. on 2022-23, skipping.
Skipping merge for Jaime Jaquez Jr. on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Wells on 2022-23, skipping.
Skipping merge for Jaylen Wells on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Wells on 2023-24, skipping.
Skipping merge for Jaylen Wells on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zach Edey on 2022-23, skipping.
Skipping merge for Zach Edey on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Zach Edey on 2023-24, skipping.
Skipping merge for Zach Edey on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Quinten Post on 2022-23, skipping.
Skipping merge for Quinten Post on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Quinten Post on 2023-24, skipping.
Skipping merge for Quinten Post on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Justin Champagnie on 2022-23, skipping.
Skipping merge for Justin Champagnie on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Kyshawn George on 2022-23, skipping.
Skipping merge for Kyshawn George on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Kyshawn George on 2023-24, skipping.
Skipping merge for Kyshawn George on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Alex Sarr on 2022-23, skipping.
Skipping merge for Alex Sarr on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Alex Sarr on 2023-24, skipping.
Skipping merge for Alex Sarr on 2023-24 due to missing data.
defense data skipping defense merge

c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.300e-01, tolerance: 9.195e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.363e-01, tolerance: 8.875e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.623e-02, tolerance: 1.052e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.035e-02, tolerance: 9.431e-03
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.773e-01, tolerance: 8.617e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.050e-01, tolerance: 7.569e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.802e-01, tolerance: 1.146e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.846e-01, tolerance: 1.259e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.757e-01, tolerance: 1.282e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.795e-01, tolerance: 1.335e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.915e-02, tolerance: 1.377e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.217e-01, tolerance: 8.440e-03
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.977e-03, tolerance: 8.338e-03
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.799e+00, tolerance: 9.580e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.701e+00, tolerance: 1.017e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.868e-01, tolerance: 1.120e-01
  model = cd_fast.enet_coordinate_descent(

Player data missing for Matas Buzelis on 2022-23, skipping.
Skipping merge for Matas Buzelis on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Matas Buzelis on 2023-24, skipping.
Skipping merge for Matas Buzelis on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jaime Jaquez Jr. on 2022-23, skipping.
Skipping merge for Jaime Jaquez Jr. on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Wells on 2022-23, skipping.
Skipping merge for Jaylen Wells on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Wells on 2023-24, skipping.
Skipping merge for Jaylen Wells on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zach Edey on 2022-23, skipping.
Skipping merge for Zach Edey on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Zach Edey on 2023-24, skipping.
Skipping merge for Zach Edey on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Quinten Post on 2022-23, skipping.
Skipping merge for Quinten Post on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Quinten Post on 2023-24, skipping.
Skipping merge for Quinten Post on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Justin Champagnie on 2022-23, skipping.
Skipping merge for Justin Champagnie on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Kyshawn George on 2022-23, skipping.
Skipping merge for Kyshawn George on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Kyshawn George on 2023-24, skipping.
Skipping merge for Kyshawn George on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Alex Sarr on 2022-23, skipping.
Skipping merge for Alex Sarr on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Alex Sarr on 2023-24, skipping.
Skipping merge for Alex Sarr on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Matas Buzelis on 2022-23, skipping.
Skipping merge for Matas Buzelis on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Matas Buzelis on 2023-24, skipping.
Skipping merge for Matas Buzelis on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jaime Jaquez Jr. on 2022-23, skipping.
Skipping merge for Jaime Jaquez Jr. on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Wells on 2022-23, skipping.
Skipping merge for Jaylen Wells on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Wells on 2023-24, skipping.
Skipping merge for Jaylen Wells on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zach Edey on 2022-23, skipping.
Skipping merge for Zach Edey on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Zach Edey on 2023-24, skipping.
Skipping merge for Zach Edey on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Quinten Post on 2022-23, skipping.
Skipping merge for Quinten Post on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Quinten Post on 2023-24, skipping.
Skipping merge for Quinten Post on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Justin Champagnie on 2022-23, skipping.
Skipping merge for Justin Champagnie on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Kyshawn George on 2022-23, skipping.
Skipping merge for Kyshawn George on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Kyshawn George on 2023-24, skipping.
Skipping merge for Kyshawn George on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Alex Sarr on 2022-23, skipping.
Skipping merge for Alex Sarr on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Alex Sarr on 2023-24, skipping.
Skipping merge for Alex Sarr on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Matas Buzelis on 2022-23, skipping.
Skipping merge for Matas Buzelis on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Matas Buzelis on 2023-24, skipping.
Skipping merge for Matas Buzelis on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jaime Jaquez Jr. on 2022-23, skipping.
Skipping merge for Jaime Jaquez Jr. on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Wells on 2022-23, skipping.
Skipping merge for Jaylen Wells on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Wells on 2023-24, skipping.
Skipping merge for Jaylen Wells on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zach Edey on 2022-23, skipping.
Skipping merge for Zach Edey on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Zach Edey on 2023-24, skipping.
Skipping merge for Zach Edey on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Quinten Post on 2022-23, skipping.
Skipping merge for Quinten Post on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Quinten Post on 2023-24, skipping.
Skipping merge for Quinten Post on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Justin Champagnie on 2022-23, skipping.
Skipping merge for Justin Champagnie on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Kyshawn George on 2022-23, skipping.
Skipping merge for Kyshawn George on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Kyshawn George on 2023-24, skipping.
Skipping merge for Kyshawn George on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Alex Sarr on 2022-23, skipping.
Skipping merge for Alex Sarr on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Alex Sarr on 2023-24, skipping.
Skipping merge for Alex Sarr on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Matas Buzelis on 2022-23, skipping.
Skipping merge for Matas Buzelis on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Matas Buzelis on 2023-24, skipping.
Skipping merge for Matas Buzelis on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Jaime Jaquez Jr. on 2022-23, skipping.
Skipping merge for Jaime Jaquez Jr. on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Wells on 2022-23, skipping.
Skipping merge for Jaylen Wells on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Jaylen Wells on 2023-24, skipping.
Skipping merge for Jaylen Wells on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Zach Edey on 2022-23, skipping.
Skipping merge for Zach Edey on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Zach Edey on 2023-24, skipping.
Skipping merge for Zach Edey on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Quinten Post on 2022-23, skipping.
Skipping merge for Quinten Post on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Quinten Post on 2023-24, skipping.
Skipping merge for Quinten Post on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Justin Champagnie on 2022-23, skipping.
Skipping merge for Justin Champagnie on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Kyshawn George on 2022-23, skipping.
Skipping merge for Kyshawn George on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Kyshawn George on 2023-24, skipping.
Skipping merge for Kyshawn George on 2023-24 due to missing data.
defense data skipping defense merge
Player data missing for Alex Sarr on 2022-23, skipping.
Skipping merge for Alex Sarr on 2022-23 due to missing data.
defense data skipping defense merge
Player data missing for Alex Sarr on 2023-24, skipping.
Skipping merge for Alex Sarr on 2023-24 due to missing data.
defense data skipping defense merge

c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:172: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Mean_{target}"] = df[target].rolling(window=20).mean()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:173: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_Std_{target}"] = df[target].rolling(window=20).std()
c:\Users\mandy\Documents\Github\web_scraping_sports\models\linear_regression\prediction.py:174: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f"Rolling_CV_{target}"] = df[f"Rolling_Std_{target}"] / df[f"Rolling_Mean_{target}"]

In [5]:

display(results_reb)
display(results_ast)
display(results_pts)
# display(results_3pm)

df_merged = results_reb.merge(results_ast, on=['Player', 'team'], suffixes=('_reb', '_ast')) \
    .merge(results_pts, on=['Player', 'team'], suffixes=('_pts','extra_pts')) \
    .merge(results_3pm, on=['Player', 'team'], suffixes=('_pts','_3pm'))

['Player', 'REB', 'confidence_level_REB', 'middlebet_REB', 'AST', 'confidence_level_AST', 'middlebet_AST', 'PTS', 'confidence_level_PTS', 'middlebet_PTS', '3PM', 'confidence_level_3PM', 'middlebet_3PM']

# print(df_merged.columns)


# df_merged['middlebet_PTS+REB'] = 0000

# df_merged['PTS+REB'] = df_merged[['middlebet_PTS', 'middlebet_REB']].sum(axis=1)
# df_merged['confidence_level_PTS+REB']=  round(df_merged[['confidence_level_PTS','confidence_level_REB']].sum(axis=1)/2,2)
# df_merged = df_merged.rename(columns={'FGA': 'PTS'})
# display(df_merged)
# display(df_merged[['Player','confidence_level_PTS+REB']])


from parlay_picker import create_parlays

num_groups = 100  # Number of parlays you want to generate
players_per_group = 4  # Number of players in each parlay
min_confidence = 50

parlays_df, group_confidence_scores = create_parlays(df_merged, num_groups, players_per_group,min_confidence)


# Display the confidence scores for each group
print("Confidence scores for each group:")
for group, score in group_confidence_scores:
    print(f"{group}: {score:.2f}")


# Display the DataFrames for each parlay and their confidence scores
for (parlay_name, score), parlay_df in zip(group_confidence_scores, parlays_df):
    print("\n")
    print(f"{parlay_name}: total confidence score: {score:.2f}")
    display(parlay_df)
    print("\n")

                   Player team          REB  confidence_level_REB                         recentgames_REB
0              Coby White  CHI    1 - 3 - 4                 50.39          [7, 7, 3, 5, 4, 7, 4, 1, 5, 4]
1           Kevin Huerter  CHI    0 - 1 - 1                  3.09          [9, 4, 3, 5, 1, 2, 0, 2, 1, 4]
2               Tre Jones  CHI    0 - 0 - 0                 18.75          [6, 3, 5, 5, 8, 0, 1, 2, 4, 1]
3           Matas Buzelis  CHI    1 - 3 - 4                 56.73          [3, 4, 5, 5, 7, 6, 4, 4, 3, 3]
4          Nikola Vucevic  CHI   6 - 9 - 11                 67.40    [3, 11, 11, 9, 14, 7, 4, 11, 11, 11]
5             Jalen Green  HOU    1 - 4 - 6                 48.61          [9, 7, 7, 7, 2, 4, 6, 2, 7, 8]
6           Dillon Brooks  HOU    1 - 3 - 4                 35.76          [2, 1, 4, 4, 4, 4, 1, 4, 8, 9]
7           Fred VanVleet  HOU    0 - 2 - 3                 33.13          [7, 2, 5, 0, 1, 4, 5, 3, 3, 5]
8        Jabari Smith Jr.  HOU    2 - 5 - 7                 56.86         [8, 4, 7, 5, 5, 9, 8, 7, 10, 8]
9          Alperen Sengun  HOU   4 - 8 - 11                 60.45    [15, 4, 14, 5, 6, 9, 10, 11, 11, 12]
10        Duncan Robinson  MIA    0 - 2 - 3                 33.75          [3, 1, 0, 1, 4, 3, 3, 3, 2, 5]
11       Jaime Jaquez Jr.  MIA    1 - 3 - 4                 55.28          [5, 1, 4, 4, 1, 4, 2, 1, 6, 3]
12            Tyler Herro  MIA    2 - 4 - 5                 58.82          [5, 6, 3, 8, 6, 3, 4, 3, 2, 6]
13         Andrew Wiggins  MIA    2 - 4 - 5                 52.32          [4, 3, 7, 3, 2, 4, 6, 8, 4, 5]
14            Bam Adebayo  MIA   6 - 9 - 11                 68.54      [9, 7, 14, 6, 13, 12, 15, 7, 7, 9]
15           Desmond Bane  MEM   3 - 7 - 10                 50.59       [6, 5, 7, 9, 16, 6, 10, 12, 3, 5]
16           Jaylen Wells  MEM    0 - 2 - 3                 48.26          [0, 4, 6, 7, 5, 5, 2, 2, 1, 5]
17              Ja Morant  MEM    1 - 3 - 4                 50.51          [8, 1, 4, 4, 4, 3, 4, 4, 2, 4]
18      Jaren Jackson Jr.  MEM    1 - 2 - 2                 54.66          [3, 0, 4, 7, 6, 3, 4, 7, 6, 6]
19              Zach Edey  MEM   3 - 7 - 10                 53.59       [3, 4, 12, 12, 9, 5, 9, 11, 8, 9]
20        Andrew Nembhard  IND    0 - 2 - 3                 28.32          [2, 2, 3, 5, 1, 6, 2, 3, 0, 2]
21          Aaron Nesmith  IND    0 - 2 - 3                 42.69          [3, 4, 5, 1, 3, 5, 5, 6, 5, 4]
22      Tyrese Haliburton  IND    1 - 2 - 2                 51.73          [5, 3, 3, 5, 2, 3, 1, 1, 5, 2]
23          Pascal Siakam  IND    2 - 5 - 7                 57.30         [7, 12, 1, 7, 9, 2, 6, 6, 8, 9]
24           Myles Turner  IND    1 - 3 - 4                 42.70         [7, 6, 4, 6, 9, 4, 6, 3, 10, 2]
25         Taurean Prince  MIL    0 - 2 - 3                 44.26          [4, 6, 2, 4, 4, 2, 7, 4, 2, 1]
26             Kyle Kuzma  MIL    3 - 5 - 6                 61.06         [4, 4, 6, 8, 4, 10, 8, 9, 6, 3]
27         Damian Lillard  MIL    1 - 3 - 4                 54.37          [6, 3, 5, 7, 3, 5, 6, 4, 1, 3]
28  Giannis Antetokounmpo  MIL  8 - 11 - 13                 73.07  [12, 17, 9, 11, 15, 12, 9, 19, 10, 16]
29            Brook Lopez  MIL    1 - 4 - 6                 44.96         [4, 7, 9, 2, 2, 13, 6, 4, 8, 4]
30          Mikal Bridges  NYK    0 - 2 - 3                 40.10          [4, 3, 4, 3, 4, 4, 2, 2, 0, 1]
31              Josh Hart  NYK  5 - 10 - 14                 58.82    [11, 6, 20, 10, 8, 7, 4, 17, 11, 10]
32          Miles McBride  NYK    0 - 0 - 0                 34.49          [1, 3, 2, 5, 4, 2, 4, 2, 2, 3]
33             OG Anunoby  NYK    1 - 4 - 6                 36.74          [7, 7, 8, 4, 3, 9, 3, 9, 2, 0]
34     Karl-Anthony Towns  NYK  7 - 11 - 14                 63.77    [7, 9, 10, 14, 16, 7, 18, 7, 18, 10]
35            Moses Moody  GSW    1 - 3 - 4                 42.43          [4, 2, 7, 5, 4, 5, 2, 1, 1, 4]
36       Jimmy Butler III  GSW    1 - 3 - 4                 37.82         [5, 10, 9, 2, 4, 3, 4, 8, 3, 3]
37          Stephen Curry  GSW    0 - 1 - 1                 47.14          [2, 2, 3, 4, 7, 3, 5, 4, 4, 4]
38         Draymond Green  GSW    2 - 5 - 7                 54.22        [4, 4, 9, 7, 9, 12, 8, 10, 6, 4]
39           Quinten Post  GSW    1 - 3 - 4                 45.33          [4, 7, 2, 7, 3, 3, 9, 5, 3, 6]
40        Khris Middleton  WAS    1 - 3 - 4                 52.98          [7, 3, 3, 6, 3, 5, 4, 3, 5, 2]
41      Justin Champagnie  WAS    1 - 3 - 4                 33.91          [9, 8, 9, 0, 3, 8, 8, 5, 7, 6]
42           Jordan Poole  WAS    1 - 3 - 4                 58.48          [6, 5, 3, 2, 5, 4, 3, 2, 5, 6]
43         Kyshawn George  WAS    2 - 4 - 5                 54.36          [4, 5, 3, 6, 7, 8, 4, 5, 3, 2]
44              Alex Sarr  WAS    3 - 6 - 8                 56.03        [5, 7, 11, 14, 5, 4, 3, 7, 6, 2]
45        Christian Braun  DEN    2 - 5 - 7                 56.28         [5, 4, 5, 3, 5, 2, 6, 6, 10, 8]
46     Michael Porter Jr.  DEN   3 - 7 - 10                 51.21      [4, 9, 6, 15, 2, 12, 5, 9, 10, 11]
47           Jamal Murray  DEN    0 - 1 - 1                 49.22          [4, 5, 4, 2, 1, 4, 6, 3, 3, 1]
48           Aaron Gordon  DEN    1 - 3 - 4                 43.54         [7, 2, 3, 5, 5, 5, 7, 2, 10, 3]
49           Nikola Jokic  DEN  8 - 12 - 15                 68.77   [7, 8, 18, 13, 21, 15, 14, 17, 14, 9]

                   Player team          AST  confidence_level_AST                         recentgames_AST
0              Coby White  CHI    1 - 4 - 6                 44.26          [4, 4, 3, 1, 7, 1, 3, 3, 6, 8]
1           Kevin Huerter  CHI   1 - 7 - 12                 25.71          [3, 1, 0, 3, 2, 3, 4, 2, 1, 2]
2               Tre Jones  CHI  4 - 14 - 23                 33.50          [6, 8, 5, 4, 7, 6, 2, 2, 5, 3]
3           Matas Buzelis  CHI    0 - 1 - 1                 14.44          [1, 1, 1, 2, 3, 3, 3, 2, 5, 1]
4          Nikola Vucevic  CHI    0 - 3 - 5                 31.59         [3, 1, 1, 1, 5, 1, 1, 4, 2, 10]
5             Jalen Green  HOU    1 - 3 - 4                 49.24          [5, 4, 8, 3, 8, 2, 4, 2, 4, 3]
6           Dillon Brooks  HOU    0 - 2 - 3                 31.18          [3, 4, 1, 3, 1, 2, 0, 1, 4, 5]
7           Fred VanVleet  HOU    1 - 2 - 2                 50.99          [3, 4, 5, 2, 5, 6, 7, 6, 5, 2]
8        Jabari Smith Jr.  HOU    0 - 0 - 0                 12.90          [2, 3, 0, 1, 1, 0, 1, 0, 1, 0]
9          Alperen Sengun  HOU    2 - 4 - 5                 50.04          [4, 7, 4, 6, 8, 7, 5, 3, 3, 7]
10        Duncan Robinson  MIA    0 - 1 - 1                  7.87          [0, 0, 1, 4, 1, 2, 1, 5, 5, 6]
11       Jaime Jaquez Jr.  MIA    0 - 1 - 1                 29.29          [3, 0, 1, 2, 0, 1, 1, 0, 3, 3]
12            Tyler Herro  MIA    3 - 5 - 6                 63.48         [6, 7, 2, 6, 7, 6, 7, 7, 10, 3]
13         Andrew Wiggins  MIA    0 - 2 - 3                 39.47          [3, 5, 2, 1, 6, 1, 4, 1, 3, 5]
14            Bam Adebayo  MIA    0 - 2 - 3                 39.94          [2, 7, 8, 2, 4, 5, 5, 4, 7, 3]
15           Desmond Bane  MEM  5 - 13 - 20                 45.31         [3, 9, 3, 8, 6, 1, 10, 4, 9, 8]
16           Jaylen Wells  MEM    0 - 1 - 1                  9.30          [0, 2, 2, 2, 1, 1, 6, 3, 2, 2]
17              Ja Morant  MEM    3 - 6 - 8                 62.92        [7, 7, 12, 6, 8, 6, 7, 8, 10, 5]
18      Jaren Jackson Jr.  MEM   0 - 6 - 11                 11.21          [0, 0, 2, 1, 1, 4, 1, 4, 2, 1]
19              Zach Edey  MEM    0 - 0 - 0                  9.93          [1, 0, 2, 0, 0, 2, 0, 1, 1, 0]
20        Andrew Nembhard  IND    1 - 4 - 6                 37.42       [7, 3, 3, 12, 10, 6, 4, 11, 3, 5]
21          Aaron Nesmith  IND    0 - 1 - 1                 46.96          [2, 1, 2, 2, 2, 0, 1, 2, 3, 0]
22      Tyrese Haliburton  IND    4 - 7 - 9                 69.65  [10, 10, 15, 12, 10, 11, 15, 12, 9, 7]
23          Pascal Siakam  IND    1 - 2 - 2                 56.82          [4, 5, 4, 3, 3, 2, 4, 2, 2, 2]
24           Myles Turner  IND    0 - 1 - 1                 44.15          [1, 2, 2, 2, 1, 1, 2, 3, 2, 2]
25         Taurean Prince  MIL    0 - 1 - 1                 20.12          [1, 3, 3, 3, 0, 2, 5, 1, 5, 0]
26             Kyle Kuzma  MIL    0 - 2 - 3                 11.44          [0, 2, 1, 0, 0, 2, 2, 5, 1, 3]
27         Damian Lillard  MIL    3 - 5 - 6                 63.06        [10, 11, 4, 4, 5, 4, 6, 4, 3, 8]
28  Giannis Antetokounmpo  MIL    2 - 4 - 5                 58.06         [9, 7, 3, 4, 4, 10, 9, 7, 6, 7]
29            Brook Lopez  MIL    0 - 1 - 1                 30.45          [5, 1, 0, 0, 1, 3, 3, 3, 3, 1]
30          Mikal Bridges  NYK    1 - 2 - 2                 53.27          [4, 8, 5, 3, 4, 8, 3, 3, 1, 5]
31              Josh Hart  NYK    2 - 5 - 7                 53.67          [9, 3, 6, 2, 3, 3, 6, 4, 9, 6]
32          Miles McBride  NYK    0 - 1 - 1                 22.11          [5, 7, 6, 2, 5, 2, 3, 1, 2, 0]
33             OG Anunoby  NYK    0 - 2 - 3                 32.99          [3, 8, 1, 1, 3, 5, 3, 3, 2, 0]
34     Karl-Anthony Towns  NYK    0 - 2 - 3                 30.33          [4, 3, 2, 1, 0, 2, 0, 4, 2, 3]
35            Moses Moody  GSW    0 - 1 - 2                 39.04          [6, 0, 3, 2, 2, 0, 0, 0, 1, 1]
36       Jimmy Butler III  GSW  7 - 12 - 16                 59.81         [7, 10, 5, 6, 4, 4, 7, 5, 5, 7]
37          Stephen Curry  GSW    2 - 5 - 7                 53.03        [5, 3, 4, 4, 9, 10, 13, 3, 6, 7]
38         Draymond Green  GSW    3 - 6 - 8                 61.86         [4, 7, 7, 10, 8, 7, 8, 4, 6, 6]
39           Quinten Post  GSW    1 - 5 - 8                 25.26          [0, 2, 1, 2, 0, 2, 1, 1, 2, 3]
40        Khris Middleton  WAS    2 - 5 - 7                 42.81          [8, 0, 2, 6, 3, 6, 5, 5, 2, 4]
41      Justin Champagnie  WAS    0 - 1 - 2                 33.95          [1, 1, 2, 0, 2, 1, 2, 1, 1, 0]
42           Jordan Poole  WAS   3 - 7 - 10                 48.60          [4, 3, 1, 5, 3, 2, 4, 5, 5, 4]
43         Kyshawn George  WAS    0 - 2 - 3                 32.35          [1, 2, 3, 3, 2, 5, 8, 2, 5, 3]
44              Alex Sarr  WAS    0 - 2 - 3                 43.65          [3, 2, 2, 3, 4, 3, 2, 1, 4, 1]
45        Christian Braun  DEN    1 - 3 - 4                 44.03          [6, 0, 5, 2, 5, 7, 3, 2, 3, 1]
46     Michael Porter Jr.  DEN    0 - 0 - 0                 33.48          [2, 2, 2, 0, 3, 0, 2, 1, 3, 3]
47           Jamal Murray  DEN    3 - 5 - 6                 71.16          [5, 8, 6, 4, 8, 8, 7, 4, 5, 6]
48           Aaron Gordon  DEN    0 - 4 - 7                 11.84          [4, 0, 1, 2, 2, 4, 2, 7, 4, 7]
49           Nikola Jokic  DEN   5 - 9 - 12                 57.87      [5, 4, 8, 9, 22, 6, 9, 15, 10, 19]

                   Player team           PTS  confidence_level_PTS                           recentgames_PTS
0              Coby White  CHI  10 - 18 - 25                 56.65  [31, 29, 21, 44, 25, 26, 24, 19, 15, 20]
1           Kevin Huerter  CHI     1 - 5 - 8                 23.93    [18, 13, 11, 13, 15, 13, 23, 14, 9, 2]
2               Tre Jones  CHI     2 - 6 - 9                 42.67      [18, 8, 15, 20, 9, 11, 10, 16, 4, 4]
3           Matas Buzelis  CHI   6 - 10 - 13                 61.81     [6, 8, 13, 11, 17, 18, 10, 5, 17, 15]
4          Nikola Vucevic  CHI   6 - 13 - 19                 51.09    [7, 11, 16, 21, 21, 8, 10, 10, 12, 20]
5             Jalen Green  HOU  12 - 19 - 25                 65.62   [23, 29, 15, 14, 9, 12, 18, 24, 21, 25]
6           Dillon Brooks  HOU   8 - 13 - 17                 66.35   [12, 19, 17, 27, 14, 13, 12, 19, 16, 9]
7           Fred VanVleet  HOU   4 - 10 - 15                 45.90       [8, 10, 3, 3, 13, 5, 7, 20, 26, 20]
8        Jabari Smith Jr.  HOU   6 - 10 - 13                 61.22     [13, 8, 20, 14, 16, 12, 11, 5, 9, 13]
9          Alperen Sengun  HOU  10 - 17 - 23                 59.77   [16, 20, 14, 20, 22, 25, 30, 9, 23, 27]
10        Duncan Robinson  MIA    3 - 8 - 12                 45.45   [6, 15, 14, 12, 15, 14, 17, 10, 20, 24]
11       Jaime Jaquez Jr.  MIA     1 - 4 - 6                 44.67          [13, 3, 5, 4, 4, 11, 2, 2, 6, 5]
12            Tyler Herro  MIA  12 - 20 - 27                 64.63  [19, 31, 21, 21, 22, 16, 22, 29, 24, 11]
13         Andrew Wiggins  MIA  12 - 18 - 23                 69.42  [23, 22, 19, 22, 15, 23, 20, 25, 13, 11]
14            Bam Adebayo  MIA  12 - 19 - 25                 67.65    [9, 6, 23, 22, 29, 34, 19, 30, 18, 20]
15           Desmond Bane  MEM  12 - 19 - 25                 66.60   [12, 17, 10, 30, 27, 15, 35, 24, 25, 7]
16           Jaylen Wells  MEM    2 - 7 - 11                 32.15         [7, 3, 2, 9, 5, 3, 12, 18, 3, 19]
17              Ja Morant  MEM  13 - 21 - 28                 65.16  [44, 28, 29, 32, 31, 24, 25, 29, 21, 23]
18      Jaren Jackson Jr.  MEM  11 - 20 - 28                 58.36   [13, 0, 42, 18, 28, 22, 16, 18, 13, 17]
19              Zach Edey  MEM     2 - 6 - 9                 47.25         [6, 8, 6, 8, 6, 15, 17, 10, 8, 6]
20        Andrew Nembhard  IND    3 - 7 - 10                 54.66        [5, 12, 8, 11, 15, 5, 11, 9, 7, 6]
21          Aaron Nesmith  IND   3 - 10 - 16                 39.59     [16, 9, 9, 14, 21, 16, 27, 7, 12, 17]
22      Tyrese Haliburton  IND   8 - 15 - 21                 58.43  [14, 14, 28, 17, 19, 33, 19, 29, 22, 20]
23          Pascal Siakam  IND  12 - 19 - 25                 65.63  [27, 25, 13, 23, 35, 18, 20, 36, 15, 19]
24           Myles Turner  IND   9 - 14 - 18                 64.81  [18, 13, 15, 14, 17, 16, 16, 22, 18, 23]
25         Taurean Prince  MIL    3 - 7 - 10                 53.40         [7, 18, 6, 13, 3, 8, 9, 10, 6, 2]
26             Kyle Kuzma  MIL   8 - 13 - 17                 62.30     [5, 9, 14, 11, 17, 17, 10, 16, 9, 16]
27         Damian Lillard  MIL  16 - 23 - 29                 69.68  [22, 15, 22, 26, 34, 23, 28, 19, 22, 28]
28  Giannis Antetokounmpo  MIL  22 - 28 - 33                 79.19  [24, 19, 30, 37, 32, 26, 29, 28, 27, 23]
29            Brook Lopez  MIL   5 - 10 - 14                 55.69     [23, 23, 7, 8, 2, 13, 13, 22, 12, 17]
30          Mikal Bridges  NYK   6 - 13 - 19                 52.69    [33, 15, 22, 6, 15, 5, 15, 28, 14, 14]
31              Josh Hart  NYK   7 - 14 - 20                 54.55    [11, 18, 14, 18, 2, 14, 12, 7, 20, 18]
32          Miles McBride  NYK    2 - 7 - 11                 30.31        [11, 21, 7, 0, 6, 12, 17, 6, 2, 5]
33             OG Anunoby  NYK   9 - 16 - 22                 58.46   [23, 24, 11, 20, 29, 23, 19, 16, 10, 5]
34     Karl-Anthony Towns  NYK  12 - 21 - 29                 57.45  [21, 26, 23, 12, 19, 11, 24, 23, 32, 44]
35            Moses Moody  GSW   6 - 11 - 15                 61.53    [17, 20, 12, 10, 9, 5, 10, 10, 13, 14]
36       Jimmy Butler III  GSW   5 - 12 - 18                 49.11     [6, 15, 26, 25, 19, 13, 5, 6, 18, 17]
37          Stephen Curry  GSW  15 - 24 - 32                 62.86  [11, 24, 32, 40, 28, 21, 29, 56, 15, 30]
38         Draymond Green  GSW    3 - 8 - 12                 46.46     [23, 4, 12, 7, 8, 16, 13, 12, 15, 13]
39           Quinten Post  GSW     2 - 6 - 9                 42.57      [10, 11, 6, 10, 3, 6, 16, 18, 8, 10]
40        Khris Middleton  WAS   5 - 10 - 14                 51.51     [16, 8, 12, 14, 16, 17, 8, 7, 12, 20]
41      Justin Champagnie  WAS     1 - 4 - 6                 26.79         [17, 5, 6, 0, 17, 7, 10, 0, 6, 6]
42           Jordan Poole  WAS   8 - 18 - 27                 48.98  [17, 15, 16, 34, 24, 26, 16, 11, 42, 16]
43         Kyshawn George  WAS    4 - 9 - 13                 52.64       [9, 12, 13, 5, 23, 10, 8, 7, 12, 9]
44              Alex Sarr  WAS   5 - 10 - 14                 55.04      [19, 8, 16, 10, 21, 9, 10, 22, 9, 4]
45        Christian Braun  DEN   9 - 14 - 18                 66.95   [22, 6, 14, 19, 25, 15, 24, 23, 13, 17]
46     Michael Porter Jr.  DEN   8 - 17 - 25                 49.31  [13, 10, 17, 24, 16, 13, 10, 28, 12, 19]
47           Jamal Murray  DEN  13 - 23 - 32                 58.73  [26, 12, 34, 17, 19, 24, 26, 31, 20, 16]
48           Aaron Gordon  DEN   5 - 11 - 16                 46.24      [17, 5, 27, 9, 25, 24, 18, 9, 9, 11]
49           Nikola Jokic  DEN  18 - 25 - 31                 75.56  [28, 34, 35, 24, 31, 22, 20, 23, 32, 18]

Confidence scores for each group:
Parlay 1: 60.65
Parlay 2: 64.54
Parlay 3: 58.47
Parlay 4: 67.56
Parlay 5: 57.47
Parlay 6: 63.26
Parlay 7: 52.34
Parlay 8: 64.63
Parlay 9: 55.13
Parlay 10: 71.25
Parlay 11: 59.28
Parlay 12: 59.62
Parlay 13: 53.55
Parlay 14: 61.52
Parlay 15: 55.98
Parlay 16: 52.39
Parlay 17: 70.61
Parlay 18: 56.02


Parlay 1: total confidence score: 60.65

           Player team Stat    Stat Range  Confidence                               recentgames
0  Nikola Vucevic  CHI  REB    6 - 9 - 11       67.40      [3, 11, 11, 9, 14, 7, 4, 11, 11, 11]
1   Matas Buzelis  CHI  PTS   6 - 10 - 13       61.81     [6, 8, 13, 11, 17, 18, 10, 5, 17, 15]
2   Matas Buzelis  CHI  REB     1 - 3 - 4       56.73            [3, 4, 5, 5, 7, 6, 4, 4, 3, 3]
3      Coby White  CHI  PTS  10 - 18 - 25       56.65  [31, 29, 21, 44, 25, 26, 24, 19, 15, 20]

Parlay 2: total confidence score: 64.54

             Player team Stat    Stat Range  Confidence                              recentgames
0     Dillon Brooks  HOU  PTS   8 - 13 - 17       66.35  [12, 19, 17, 27, 14, 13, 12, 19, 16, 9]
1       Jalen Green  HOU  PTS  12 - 19 - 25       65.62  [23, 29, 15, 14, 9, 12, 18, 24, 21, 25]
2    Alperen Sengun  HOU  3PM     0 - 0 - 0       64.96           [0, 1, 1, 0, 0, 0, 0, 0, 0, 1]
3  Jabari Smith Jr.  HOU  PTS   6 - 10 - 13       61.22    [13, 8, 20, 14, 16, 12, 11, 5, 9, 13]

Parlay 3: total confidence score: 58.47

             Player team Stat    Stat Range  Confidence                              recentgames
0    Alperen Sengun  HOU  REB    4 - 8 - 11       60.45     [15, 4, 14, 5, 6, 9, 10, 11, 11, 12]
1    Alperen Sengun  HOU  PTS  10 - 17 - 23       59.77  [16, 20, 14, 20, 22, 25, 30, 9, 23, 27]
2  Jabari Smith Jr.  HOU  REB     2 - 5 - 7       56.86          [8, 4, 7, 5, 5, 9, 8, 7, 10, 8]
3       Jalen Green  HOU  3PM     2 - 4 - 5       56.82           [4, 3, 3, 2, 2, 2, 1, 4, 3, 5]

Parlay 4: total confidence score: 67.56

           Player team Stat    Stat Range  Confidence                               recentgames
0  Andrew Wiggins  MIA  PTS  12 - 18 - 23       69.42  [23, 22, 19, 22, 15, 23, 20, 25, 13, 11]
1     Bam Adebayo  MIA  REB    6 - 9 - 11       68.54        [9, 7, 14, 6, 13, 12, 15, 7, 7, 9]
2     Bam Adebayo  MIA  PTS  12 - 19 - 25       67.65    [9, 6, 23, 22, 29, 34, 19, 30, 18, 20]
3     Tyler Herro  MIA  PTS  12 - 20 - 27       64.63  [19, 31, 21, 21, 22, 16, 22, 29, 24, 11]

Parlay 5: total confidence score: 57.47

             Player team Stat Stat Range  Confidence                      recentgames
0       Tyler Herro  MIA  AST  3 - 5 - 6       63.48  [6, 7, 2, 6, 7, 6, 7, 7, 10, 3]
1       Tyler Herro  MIA  REB  2 - 4 - 5       58.82   [5, 6, 3, 8, 6, 3, 4, 3, 2, 6]
2  Jaime Jaquez Jr.  MIA  REB  1 - 3 - 4       55.28   [5, 1, 4, 4, 1, 4, 2, 1, 6, 3]
3    Andrew Wiggins  MIA  REB  2 - 4 - 5       52.32   [4, 3, 7, 3, 2, 4, 6, 8, 4, 5]

Parlay 6: total confidence score: 63.26

              Player team Stat    Stat Range  Confidence                               recentgames
0       Desmond Bane  MEM  PTS  12 - 19 - 25       66.60   [12, 17, 10, 30, 27, 15, 35, 24, 25, 7]
1          Ja Morant  MEM  PTS  13 - 21 - 28       65.16  [44, 28, 29, 32, 31, 24, 25, 29, 21, 23]
2          Ja Morant  MEM  AST     3 - 6 - 8       62.92          [7, 7, 12, 6, 8, 6, 7, 8, 10, 5]
3  Jaren Jackson Jr.  MEM  PTS  11 - 20 - 28       58.36   [13, 0, 42, 18, 28, 22, 16, 18, 13, 17]

Parlay 7: total confidence score: 52.34

              Player team Stat  Stat Range  Confidence                        recentgames
0  Jaren Jackson Jr.  MEM  REB   1 - 2 - 2       54.66     [3, 0, 4, 7, 6, 3, 4, 7, 6, 6]
1          Zach Edey  MEM  REB  3 - 7 - 10       53.59  [3, 4, 12, 12, 9, 5, 9, 11, 8, 9]
2       Desmond Bane  MEM  REB  3 - 7 - 10       50.59  [6, 5, 7, 9, 16, 6, 10, 12, 3, 5]
3          Ja Morant  MEM  REB   1 - 3 - 4       50.51     [8, 1, 4, 4, 4, 3, 4, 4, 2, 4]

Parlay 8: total confidence score: 64.63

              Player team Stat    Stat Range  Confidence                               recentgames
0  Tyrese Haliburton  IND  AST     4 - 7 - 9       69.65    [10, 10, 15, 12, 10, 11, 15, 12, 9, 7]
1      Pascal Siakam  IND  PTS  12 - 19 - 25       65.63  [27, 25, 13, 23, 35, 18, 20, 36, 15, 19]
2       Myles Turner  IND  PTS   9 - 14 - 18       64.81  [18, 13, 15, 14, 17, 16, 16, 22, 18, 23]
3  Tyrese Haliburton  IND  PTS   8 - 15 - 21       58.43  [14, 14, 28, 17, 19, 33, 19, 29, 22, 20]

Parlay 9: total confidence score: 55.13

              Player team Stat  Stat Range  Confidence                         recentgames
0      Pascal Siakam  IND  REB   2 - 5 - 7       57.30     [7, 12, 1, 7, 9, 2, 6, 6, 8, 9]
1      Pascal Siakam  IND  AST   1 - 2 - 2       56.82      [4, 5, 4, 3, 3, 2, 4, 2, 2, 2]
2    Andrew Nembhard  IND  PTS  3 - 7 - 10       54.66  [5, 12, 8, 11, 15, 5, 11, 9, 7, 6]
3  Tyrese Haliburton  IND  REB   1 - 2 - 2       51.73      [5, 3, 3, 5, 2, 3, 1, 1, 5, 2]

Parlay 10: total confidence score: 71.25

                  Player team Stat    Stat Range  Confidence                               recentgames
0  Giannis Antetokounmpo  MIL  PTS  22 - 28 - 33       79.19  [24, 19, 30, 37, 32, 26, 29, 28, 27, 23]
1  Giannis Antetokounmpo  MIL  REB   8 - 11 - 13       73.07    [12, 17, 9, 11, 15, 12, 9, 19, 10, 16]
2         Damian Lillard  MIL  PTS  16 - 23 - 29       69.68  [22, 15, 22, 26, 34, 23, 28, 19, 22, 28]
3         Damian Lillard  MIL  AST     3 - 5 - 6       63.06          [10, 11, 4, 4, 5, 4, 6, 4, 3, 8]

Parlay 11: total confidence score: 59.28

                  Player team Stat   Stat Range  Confidence                            recentgames
0             Kyle Kuzma  MIL  PTS  8 - 13 - 17       62.30  [5, 9, 14, 11, 17, 17, 10, 16, 9, 16]
1             Kyle Kuzma  MIL  REB    3 - 5 - 6       61.06        [4, 4, 6, 8, 4, 10, 8, 9, 6, 3]
2  Giannis Antetokounmpo  MIL  AST    2 - 4 - 5       58.06        [9, 7, 3, 4, 4, 10, 9, 7, 6, 7]
3            Brook Lopez  MIL  PTS  5 - 10 - 14       55.69  [23, 23, 7, 8, 2, 13, 13, 22, 12, 17]

Parlay 12: total confidence score: 59.62

               Player team Stat    Stat Range  Confidence                               recentgames
0  Karl-Anthony Towns  NYK  REB   7 - 11 - 14       63.77      [7, 9, 10, 14, 16, 7, 18, 7, 18, 10]
1           Josh Hart  NYK  REB   5 - 10 - 14       58.82      [11, 6, 20, 10, 8, 7, 4, 17, 11, 10]
2          OG Anunoby  NYK  PTS   9 - 16 - 22       58.46   [23, 24, 11, 20, 29, 23, 19, 16, 10, 5]
3  Karl-Anthony Towns  NYK  PTS  12 - 21 - 29       57.45  [21, 26, 23, 12, 19, 11, 24, 23, 32, 44]

Parlay 13: total confidence score: 53.55

          Player team Stat   Stat Range  Confidence                             recentgames
0      Josh Hart  NYK  PTS  7 - 14 - 20       54.55  [11, 18, 14, 18, 2, 14, 12, 7, 20, 18]
1      Josh Hart  NYK  AST    2 - 5 - 7       53.67          [9, 3, 6, 2, 3, 3, 6, 4, 9, 6]
2  Mikal Bridges  NYK  AST    1 - 2 - 2       53.27          [4, 8, 5, 3, 4, 8, 3, 3, 1, 5]
3  Mikal Bridges  NYK  PTS  6 - 13 - 19       52.69  [33, 15, 22, 6, 15, 5, 15, 28, 14, 14]

Parlay 14: total confidence score: 61.52

             Player team Stat    Stat Range  Confidence                               recentgames
0     Stephen Curry  GSW  PTS  15 - 24 - 32       62.86  [11, 24, 32, 40, 28, 21, 29, 56, 15, 30]
1    Draymond Green  GSW  AST     3 - 6 - 8       61.86           [4, 7, 7, 10, 8, 7, 8, 4, 6, 6]
2       Moses Moody  GSW  PTS   6 - 11 - 15       61.53    [17, 20, 12, 10, 9, 5, 10, 10, 13, 14]
3  Jimmy Butler III  GSW  AST   7 - 12 - 16       59.81           [7, 10, 5, 6, 4, 4, 7, 5, 5, 7]

Parlay 15: total confidence score: 55.98

           Player team Stat   Stat Range  Confidence                           recentgames
0    Jordan Poole  WAS  REB    1 - 3 - 4       58.48        [6, 5, 3, 2, 5, 4, 3, 2, 5, 6]
1       Alex Sarr  WAS  REB    3 - 6 - 8       56.03      [5, 7, 11, 14, 5, 4, 3, 7, 6, 2]
2       Alex Sarr  WAS  PTS  5 - 10 - 14       55.04  [19, 8, 16, 10, 21, 9, 10, 22, 9, 4]
3  Kyshawn George  WAS  REB    2 - 4 - 5       54.36        [4, 5, 3, 6, 7, 8, 4, 5, 3, 2]

Parlay 16: total confidence score: 52.39

            Player team Stat   Stat Range  Confidence                            recentgames
0  Khris Middleton  WAS  REB    1 - 3 - 4       52.98         [7, 3, 3, 6, 3, 5, 4, 3, 5, 2]
1   Kyshawn George  WAS  PTS   4 - 9 - 13       52.64    [9, 12, 13, 5, 23, 10, 8, 7, 12, 9]
2   Kyshawn George  WAS  3PM    1 - 2 - 2       52.45         [3, 2, 3, 1, 3, 2, 2, 1, 2, 3]
3  Khris Middleton  WAS  PTS  5 - 10 - 14       51.51  [16, 8, 12, 14, 16, 17, 8, 7, 12, 20]

Parlay 17: total confidence score: 70.61

            Player team Stat    Stat Range  Confidence                               recentgames
0     Nikola Jokic  DEN  PTS  18 - 25 - 31       75.56  [28, 34, 35, 24, 31, 22, 20, 23, 32, 18]
1     Jamal Murray  DEN  AST     3 - 5 - 6       71.16            [5, 8, 6, 4, 8, 8, 7, 4, 5, 6]
2     Nikola Jokic  DEN  REB   8 - 12 - 15       68.77     [7, 8, 18, 13, 21, 15, 14, 17, 14, 9]
3  Christian Braun  DEN  PTS   9 - 14 - 18       66.95   [22, 6, 14, 19, 25, 15, 24, 23, 13, 17]

Parlay 18: total confidence score: 56.02

               Player team Stat    Stat Range  Confidence                               recentgames
0        Jamal Murray  DEN  PTS  13 - 23 - 32       58.73  [26, 12, 34, 17, 19, 24, 26, 31, 20, 16]
1        Nikola Jokic  DEN  AST    5 - 9 - 12       57.87        [5, 4, 8, 9, 22, 6, 9, 15, 10, 19]
2     Christian Braun  DEN  REB     2 - 5 - 7       56.28           [5, 4, 5, 3, 5, 2, 6, 6, 10, 8]
3  Michael Porter Jr.  DEN  REB    3 - 7 - 10       51.21        [4, 9, 6, 15, 2, 12, 5, 9, 10, 11]

In [3]:
# player_data = df_merged
# # For very high confidence parlays
# parlays_high, scores_high = create_parlays(player_data, num_groups=5, players_per_group=6, min_confidence=90)

# # For moderate confidence parlays
# parlays_medium, scores_medium = create_parlays(player_data, num_groups=5, players_per_group=3, min_confidence=6)



# print("Confidence scores for each group:")
# for group, score in scores_high:
#     print(f"{group}: {score:.2f}")


# # Display the DataFrames for each parlay and their confidence scores
# for (parlay_name, score), parlay_df in zip(scores_high, parlays_high):
#     print("\n")
#     print(f"{parlay_name}: total confidence score: {score:.2f}")
#     display(parlay_df)
#     print("\n")

In [4]:
# from parlay_picker import create_parlays_high
# # Define the number of parlays and players per parlay
# num_groups = 2  # Example: Create 3 parlays
# players_per_group = 7 # Example: Each parlay consists of 4 players

# # Call the function
# parlays, confidence_scores = create_parlays_high(df_merged, num_groups, players_per_group)

# # Display results
# for i, (df, (parlay_name, avg_conf)) in enumerate(zip(parlays, confidence_scores), 1):
#     print(f"\n{parlay_name} (Avg Confidence: {avg_conf:.2f})")
#     display(df)