In [16]:
from prediction import prediction

# players_teams = {
#     "Mark Williams": "CHA",
#     # "Miles Bridges": "CHA",
#     # "Jimmy Butler": "GSW",
#     "LaMelo Ball": "CHA",
#     "Stephen Curry": "GSW",
#     # "Brandin Podziemski": "GSW",
#     # "Nick Smith Jr.": "CHA",
#     "Josh Green": "CHA",
#     "Moses Moody": "GSW",
#     "Draymond Green": "GSW",
#     "Paul George": "PHI",
#     "Tyrese Maxey": "PHI",
#     "Kelly Oubre Jr.": "PHI",
#     "Andre Drummond": "PHI",
#     "Shaedon Sharpe": "POR",
#     "Quentin Grimes": "PHI",
#     "Deni Avdija": "POR",
#     "Anfernee Simons": "POR",
#     # "Toumani Camara": "POR",
#     # "Donovan Clingan": "POR",
#     "Bam Adebayo": "MIA",
#     "Tyler Herro": "MIA",
#     "Andrew Wiggins": "MIA",
#     # "Bilal Coulibaly": "WAS",
#     # "Alexandre Sarr": "WAS",
#     "Khris Middleton": "WAS",
#     # "Carlton Carrington": "WAS",
#     "Davion Mitchell": "MIA",
#     # "Kyshawn George": "WAS",
#     "Haywood Highsmith": "MIA"
# }



# players_teams = {
#     "Giannis Antetokounmpo": "MIL",
#     "Trae Young": "ATL",
#     "Damian Lillard": "MIL",
#     "Dyson Daniels": "ATL",
#     "Brook Lopez": "MIL",
#     "Taurean Prince": "MIL",
#     "Onyeka Okongwu": "ATL",
#     "Jalen Brunson": "NYK",
#     "Karl-Anthony Towns": "NYK",
#     "Mikal Bridges": "NYK",
#     "Moses Moody": "GSW",
#     "Stephen Curry": "GSW",
#     "Josh Hart": "NYK",
#     # "Brandin Podziemski": "GSW",
#     "OG Anunoby": "NYK",
#     "Draymond Green": "GSW",
#     "Paolo Banchero": "ORL",
#     "Franz Wagner": "ORL",
#     "Jakob Poeltl": "TOR",
#     "Immanuel Quickley": "TOR",
#     "Scottie Barnes": "TOR",
#     "RJ Barrett": "TOR",
#     "Wendell Carter Jr.": "ORL",
#     "Cole Anthony": "ORL",
#     "Kentavious Caldwell-Pope": "ORL",
#     # "Ja'Kobe Walter": "TOR",
#     "Donovan Mitchell": "CLE",
#     "Darius Garland": "CLE",
#     "Jarrett Allen": "CLE",
#     "Josh Giddey": "CHI",
#     "Coby White": "CHI",
#     # "Matas Buzelis": "CHI",
#     "Max Strus": "CLE",
#     "Dean Wade": "CLE",
#     "Zach Collins": "CHI",
#     # "Lonzo Ball": "CHI"
# }



# players_teams = {
#     "Jonas Valanciunas": "SAC",
#     "Jamal Murray": "DEN",
#     "DeMar DeRozan": "SAC",
#     "Michael Porter Jr.": "DEN",
#     "Christian Braun": "DEN",
#     "Keegan Murray": "SAC",
#     "Aaron Gordon": "DEN",
#     "Russell Westbrook": "DEN",
#     "Keon Ellis": "SAC",
#     "Trey Lyles": "SAC",
#     "Markelle Fultz": "SAC",
#     "Jake LaRavia": "SAC",
#     "Shai Gilgeous-Alexander": "OKC",
#     "Desmond Bane": "MEM",
#     "Jalen Williams": "OKC",
#     "Ja Morant": "MEM",
#     "Santi Aldama": "MEM",
#     # "Jaylen Wells": "MEM",
#     "Aaron Wiggins": "OKC",
#     "Isaiah Hartenstein": "OKC",
#     # "Cason Wallace": "OKC",
#     "Brandon Clarke": "MEM",
#     "Luguentz Dort": "OKC",
#     "Isaiah Joe": "OKC",
#     # "Zach Edey": "MEM",
#     "Kenrich Williams": "OKC",
#     "James Harden": "LAC",
#     "Malik Beasley": "DET",
#     "Ivica Zubac": "LAC",
#     # "Bogdan Bogdanovic": "LAC",
#     # "Ausar Thompson": "DET",
#     "Jalen Duren": "DET",
#     "Amir Coffey": "LAC",
#     "Tim Hardaway Jr.": "DET",
#     # "Dennis Schroder": "DET",
#     "Kris Dunn": "LAC",
#     # "Ron Holland II": "DET",
#     "Isaiah Stewart": "DET"
# }


players_teams = {
    "Franz Wagner": "ORL",
    "Paolo Banchero": "ORL",
    "Coby White": "CHI",
    "Josh Giddey": "CHI",
    "Zach Collins": "ORL",
    # "Matas Buzelis": "CHI",
    "Cole Anthony": "ORL",
    "Wendell Carter Jr.": "ORL",
    "Kevin Huerter": "CHI",
    "Kentavious Caldwell-Pope": "ORL",
    "Stephen Curry": "GSW",
    # "Cameron Thomas": "BKN",
    # "Cameron Johnson": "BKN",
    # "Brandin Podziemski": "GSW",
    # "D'Angelo Russell": "GSW",
    "Moses Moody": "GSW",
    "Buddy Hield": "GSW",
    # "Nicolas Claxton": "BKN",
    "Draymond Green": "GSW",
    "Trendon Watford": "BKN",
    "Ziaire Williams": "BKN",
    "Keon Johnson": "BKN",
    "Day'Ron Sharpe": "BKN",
    # "Quinten Post": "GSW",
    # "Tyrese Martin": "BKN",
    # "Jalen Wilson": "BKN",
    # "Gui Santos": "GSW",
    "Kevon Looney": "GSW",
    # "Zion Williamson": "NOP",
    "Alperen Sengun": "HOU",
    "Jalen Green": "HOU",
    "CJ McCollum": "NOP",
    "Trey Murphy III": "NOP",
    "Dillon Brooks": "HOU",
    # "Amen Thompson": "HOU",
    "Jabari Smith Jr.": "HOU",
    "Tari Eason": "HOU",
    # "Jordan Hawkins": "NOP",
    "Kelly Olynyk": "NOP",
    "Bruce Brown": "NOP",
    "Jose Alvarado": "NOP",
    # "Karlo Matkovic": "NOP"
}

import pandas as pd
date_list = ["2022-23","2023-24","2024-25"]
usage_path = "D:/nba_usage_csv_historic/usage_csv_{date}/{date}_content.csv"
schedule_base_path = "D:/nba_scheduled_csv/schedule_csv_2025/{schedule_team}_schedule_content.csv"
player_base_path = "D:/nba_player_csv_historic/season_{date}/all_quarters/{player}_content.csv"
defense_base_path = "D:/nba_defense_history_csv/defense_csv_{date}/all_quarter_defense_content.csv"

results_reb = prediction(players_teams, date_list, usage_path, player_base_path, defense_base_path, schedule_base_path,'REB','REB')
results_ast = prediction(players_teams, date_list, usage_path, player_base_path, defense_base_path, schedule_base_path,'AST','AST')
results_pts = prediction(players_teams, date_list, usage_path, player_base_path, defense_base_path, schedule_base_path,'PTS','FGA')
results_3pm = prediction(players_teams, date_list, usage_path, player_base_path, defense_base_path, schedule_base_path,'3PA','3PM')


df_combined = pd.concat([results_reb, results_ast, results_pts, results_3pm], axis=0, ignore_index=True)

df_merged = results_reb.merge(results_ast, on='Player', suffixes=('_reb', '_ast')) \
    .merge(results_pts, on='Player', suffixes=('_pts', '_extra')) \
    .merge(results_3pm, on='Player', suffixes=('_pts', '_3pm'))


df_merged['total_points'] = df_merged[['FGA', 'AST', 'REB','3PM']].sum(axis=1)
df_merged = df_merged.rename(columns={'FGA': 'PTS'})

display(df_merged)

Franz Wagner, MAE: 2.4671622769447922e-17, RMSE: 1.0467283057891834e-16
{'RANK': 23, 'OffRtg': 111.9, 'W': 24, 'L': 38, 'DefRtg': 116.2, 'NetRtg': -4.3, 'AST%': 67.7, 'AST/TO': 1.95, 'ASTRatio': 19.8, 'OREB%': 25.9, 'DREB%': 71.8, 'REB%': 49.1, 'TOV%': 14.3, 'eFG%': 54.8, 'TS%': 57.9, 'PACE': 103.46, 'POSS': 6452, 'TEAM': 'CHI', 'PIE': 48.1}

   OREB  DREB
0     1     4

Paolo Banchero, MAE: 4.810966440042345e-16, RMSE: 8.694778322860238e-16
{'RANK': 23, 'OffRtg': 111.9, 'W': 24, 'L': 38, 'DefRtg': 116.2, 'NetRtg': -4.3, 'AST%': 67.7, 'AST/TO': 1.95, 'ASTRatio': 19.8, 'OREB%': 25.9, 'DREB%': 71.8, 'REB%': 49.1, 'TOV%': 14.3, 'eFG%': 54.8, 'TS%': 57.9, 'PACE': 103.46, 'POSS': 6452, 'TEAM': 'CHI', 'PIE': 48.1}

   OREB  DREB
0     0     5

Coby White, MAE: 1.3322676295501878e-15, RMSE: 1.7055569729570692e-15
{'RANK': 17, 'OffRtg': 107.4, 'W': 29, 'L': 34, 'DefRtg': 109.2, 'NetRtg': -1.8, 'AST%': 60.9, 'AST/TO': 1.57, 'ASTRatio': 17.0, 'OREB%': 30.5, 'DREB%': 72.8, 'REB%': 50.4, 'TOV%': 15.0, 'eFG%': 50.3, 'TS%': 54.3, 'PACE': 96.63, 'POSS': 6109, 'TEAM': 'ORL', 'PIE': 48.7}

   OREB  DREB
0     0     3

Josh Giddey, MAE: 1.3877787807814457e-15, RMSE: 1.5320618013250914e-15
{'RANK': 17, 'OffRtg': 107.4, 'W': 29, 'L': 34, 'DefRtg': 109.2, 'NetRtg': -1.8, 'AST%': 60.9, 'AST/TO': 1.57, 'ASTRatio': 17.0, 'OREB%': 30.5, 'DREB%': 72.8, 'REB%': 50.4, 'TOV%': 15.0, 'eFG%': 50.3, 'TS%': 54.3, 'PACE': 96.63, 'POSS': 6109, 'TEAM': 'ORL', 'PIE': 48.7}

   OREB  DREB
0     2     5

Zach Collins, MAE: 1.414073536627831e-15, RMSE: 2.1630237516895885e-15
{'RANK': 23, 'OffRtg': 111.9, 'W': 24, 'L': 38, 'DefRtg': 116.2, 'NetRtg': -4.3, 'AST%': 67.7, 'AST/TO': 1.95, 'ASTRatio': 19.8, 'OREB%': 25.9, 'DREB%': 71.8, 'REB%': 49.1, 'TOV%': 14.3, 'eFG%': 54.8, 'TS%': 57.9, 'PACE': 103.46, 'POSS': 6452, 'TEAM': 'CHI', 'PIE': 48.1}

   OREB  DREB
0     1     2

Cole Anthony, MAE: 6.832141690000964e-16, RMSE: 9.659087557549529e-16
{'RANK': 23, 'OffRtg': 111.9, 'W': 24, 'L': 38, 'DefRtg': 116.2, 'NetRtg': -4.3, 'AST%': 67.7, 'AST/TO': 1.95, 'ASTRatio': 19.8, 'OREB%': 25.9, 'DREB%': 71.8, 'REB%': 49.1, 'TOV%': 14.3, 'eFG%': 54.8, 'TS%': 57.9, 'PACE': 103.46, 'POSS': 6452, 'TEAM': 'CHI', 'PIE': 48.1}

   OREB  DREB
0     1     2

Wendell Carter Jr., MAE: 7.044173673483752e-16, RMSE: 1.1471275413872634e-15
{'RANK': 23, 'OffRtg': 111.9, 'W': 24, 'L': 38, 'DefRtg': 116.2, 'NetRtg': -4.3, 'AST%': 67.7, 'AST/TO': 1.95, 'ASTRatio': 19.8, 'OREB%': 25.9, 'DREB%': 71.8, 'REB%': 49.1, 'TOV%': 14.3, 'eFG%': 54.8, 'TS%': 57.9, 'PACE': 103.46, 'POSS': 6452, 'TEAM': 'CHI', 'PIE': 48.1}

   OREB  DREB
0     2     5

Kevin Huerter, MAE: 1.226532103395411e-15, RMSE: 1.4308325803788431e-15
{'RANK': 17, 'OffRtg': 107.4, 'W': 29, 'L': 34, 'DefRtg': 109.2, 'NetRtg': -1.8, 'AST%': 60.9, 'AST/TO': 1.57, 'ASTRatio': 17.0, 'OREB%': 30.5, 'DREB%': 72.8, 'REB%': 50.4, 'TOV%': 15.0, 'eFG%': 50.3, 'TS%': 54.3, 'PACE': 96.63, 'POSS': 6109, 'TEAM': 'ORL', 'PIE': 48.7}

   OREB  DREB
0     0     1

Kentavious Caldwell-Pope, MAE: 7.401486830834377e-16, RMSE: 8.757557320955461e-16
{'RANK': 23, 'OffRtg': 111.9, 'W': 24, 'L': 38, 'DefRtg': 116.2, 'NetRtg': -4.3, 'AST%': 67.7, 'AST/TO': 1.95, 'ASTRatio': 19.8, 'OREB%': 25.9, 'DREB%': 71.8, 'REB%': 49.1, 'TOV%': 14.3, 'eFG%': 54.8, 'TS%': 57.9, 'PACE': 103.46, 'POSS': 6452, 'TEAM': 'CHI', 'PIE': 48.1}

   OREB  DREB
0     0     1

Stephen Curry, MAE: 3.4540271877227093e-16, RMSE: 5.233641528945917e-16
{'RANK': 24, 'OffRtg': 108.2, 'W': 21, 'L': 40, 'DefRtg': 115.0, 'NetRtg': -6.7, 'AST%': 66.1, 'AST/TO': 1.6, 'ASTRatio': 18.1, 'OREB%': 30.2, 'DREB%': 69.7, 'REB%': 49.0, 'TOV%': 16.0, 'eFG%': 51.4, 'TS%': 55.3, 'PACE': 96.51, 'POSS': 5915, 'TEAM': 'BKN', 'PIE': 45.5}

   OREB  DREB
0     0     3

Moses Moody, MAE: 9.43689570931383e-16, RMSE: 1.1046579618885443e-15
{'RANK': 24, 'OffRtg': 108.2, 'W': 21, 'L': 40, 'DefRtg': 115.0, 'NetRtg': -6.7, 'AST%': 66.1, 'AST/TO': 1.6, 'ASTRatio': 18.1, 'OREB%': 30.2, 'DREB%': 69.7, 'REB%': 49.0, 'TOV%': 16.0, 'eFG%': 51.4, 'TS%': 55.3, 'PACE': 96.51, 'POSS': 5915, 'TEAM': 'BKN', 'PIE': 45.5}

   OREB  DREB
0     0     2

Buddy Hield, MAE: 3.2566542055671256e-16, RMSE: 4.931856774513482e-16
{'RANK': 24, 'OffRtg': 108.2, 'W': 21, 'L': 40, 'DefRtg': 115.0, 'NetRtg': -6.7, 'AST%': 66.1, 'AST/TO': 1.6, 'ASTRatio': 18.1, 'OREB%': 30.2, 'DREB%': 69.7, 'REB%': 49.0, 'TOV%': 16.0, 'eFG%': 51.4, 'TS%': 55.3, 'PACE': 96.51, 'POSS': 5915, 'TEAM': 'BKN', 'PIE': 45.5}

   OREB  DREB
0     0     2

Draymond Green, MAE: 4.996003610813204e-16, RMSE: 7.246278631392365e-16
{'RANK': 24, 'OffRtg': 108.2, 'W': 21, 'L': 40, 'DefRtg': 115.0, 'NetRtg': -6.7, 'AST%': 66.1, 'AST/TO': 1.6, 'ASTRatio': 18.1, 'OREB%': 30.2, 'DREB%': 69.7, 'REB%': 49.0, 'TOV%': 16.0, 'eFG%': 51.4, 'TS%': 55.3, 'PACE': 96.51, 'POSS': 5915, 'TEAM': 'BKN', 'PIE': 45.5}

   OREB  DREB
0     1     4

Trendon Watford, MAE: 8.326672684688674e-16, RMSE: 1.3214297116801535e-15
{'RANK': 13, 'OffRtg': 113.3, 'W': 34, 'L': 28, 'DefRtg': 111.3, 'NetRtg': 2.0, 'AST%': 70.9, 'AST/TO': 2.12, 'ASTRatio': 20.0, 'OREB%': 31.4, 'DREB%': 71.4, 'REB%': 50.8, 'TOV%': 13.7, 'eFG%': 53.1, 'TS%': 56.0, 'PACE': 99.66, 'POSS': 6191, 'TEAM': 'GSW', 'PIE': 50.8}

   OREB  DREB
0     0     2

Ziaire Williams, MAE: 6.832141690000964e-17, RMSE: 2.1333355589415134e-16
{'RANK': 13, 'OffRtg': 113.3, 'W': 34, 'L': 28, 'DefRtg': 111.3, 'NetRtg': 2.0, 'AST%': 70.9, 'AST/TO': 2.12, 'ASTRatio': 20.0, 'OREB%': 31.4, 'DREB%': 71.4, 'REB%': 50.8, 'TOV%': 13.7, 'eFG%': 53.1, 'TS%': 56.0, 'PACE': 99.66, 'POSS': 6191, 'TEAM': 'GSW', 'PIE': 50.8}

   OREB  DREB
0     1     3

Keon Johnson, MAE: 1.1446782219411096e-15, RMSE: 1.6045010945309805e-15
{'RANK': 13, 'OffRtg': 113.3, 'W': 34, 'L': 28, 'DefRtg': 111.3, 'NetRtg': 2.0, 'AST%': 70.9, 'AST/TO': 2.12, 'ASTRatio': 20.0, 'OREB%': 31.4, 'DREB%': 71.4, 'REB%': 50.8, 'TOV%': 13.7, 'eFG%': 53.1, 'TS%': 56.0, 'PACE': 99.66, 'POSS': 6191, 'TEAM': 'GSW', 'PIE': 50.8}

   OREB  DREB
0     1     3

Day'Ron Sharpe, MAE: 7.454354593911765e-16, RMSE: 9.60565210212719e-16
{'RANK': 13, 'OffRtg': 113.3, 'W': 34, 'L': 28, 'DefRtg': 111.3, 'NetRtg': 2.0, 'AST%': 70.9, 'AST/TO': 2.12, 'ASTRatio': 20.0, 'OREB%': 31.4, 'DREB%': 71.4, 'REB%': 50.8, 'TOV%': 13.7, 'eFG%': 53.1, 'TS%': 56.0, 'PACE': 99.66, 'POSS': 6191, 'TEAM': 'GSW', 'PIE': 50.8}

   OREB  DREB
0     3     3

Kevon Looney, MAE: 1.3322676295501878e-15, RMSE: 1.7684088942114474e-15
{'RANK': 24, 'OffRtg': 108.2, 'W': 21, 'L': 40, 'DefRtg': 115.0, 'NetRtg': -6.7, 'AST%': 66.1, 'AST/TO': 1.6, 'ASTRatio': 18.1, 'OREB%': 30.2, 'DREB%': 69.7, 'REB%': 49.0, 'TOV%': 16.0, 'eFG%': 51.4, 'TS%': 55.3, 'PACE': 96.51, 'POSS': 5915, 'TEAM': 'BKN', 'PIE': 45.5}

   OREB  DREB
0     2     3

Alperen Sengun, MAE: 1.212705149975171e-15, RMSE: 1.7699401170234052e-15
{'RANK': 27, 'OffRtg': 110.4, 'W': 17, 'L': 45, 'DefRtg': 118.3, 'NetRtg': -7.9, 'AST%': 62.3, 'AST/TO': 1.81, 'ASTRatio': 18.0, 'OREB%': 30.0, 'DREB%': 67.5, 'REB%': 48.2, 'TOV%': 14.0, 'eFG%': 51.8, 'TS%': 55.2, 'PACE': 100.05, 'POSS': 6233, 'TEAM': 'NOP', 'PIE': 46.0}

   OREB  DREB
0     3     7

Jalen Green, MAE: 4.810966440042345e-16, RMSE: 7.308382661323868e-16
{'RANK': 27, 'OffRtg': 110.4, 'W': 17, 'L': 45, 'DefRtg': 118.3, 'NetRtg': -7.9, 'AST%': 62.3, 'AST/TO': 1.81, 'ASTRatio': 18.0, 'OREB%': 30.0, 'DREB%': 67.5, 'REB%': 48.2, 'TOV%': 14.0, 'eFG%': 51.8, 'TS%': 55.2, 'PACE': 100.05, 'POSS': 6233, 'TEAM': 'NOP', 'PIE': 46.0}

   OREB  DREB
0     0     3

CJ McCollum, MAE: 4.1119371282413205e-16, RMSE: 6.783574731503469e-16
{'RANK': 8, 'OffRtg': 113.3, 'W': 37, 'L': 25, 'DefRtg': 109.8, 'NetRtg': 3.5, 'AST%': 54.1, 'AST/TO': 1.61, 'ASTRatio': 15.9, 'OREB%': 36.2, 'DREB%': 70.7, 'REB%': 52.9, 'TOV%': 14.1, 'eFG%': 51.1, 'TS%': 54.4, 'PACE': 99.03, 'POSS': 6165, 'TEAM': 'HOU', 'PIE': 50.8}

   OREB  DREB
0     0     3

Trey Murphy III, MAE: 7.51535585900106e-16, RMSE: 1.0378335818748355e-15
{'RANK': 8, 'OffRtg': 113.3, 'W': 37, 'L': 25, 'DefRtg': 109.8, 'NetRtg': 3.5, 'AST%': 54.1, 'AST/TO': 1.61, 'ASTRatio': 15.9, 'OREB%': 36.2, 'DREB%': 70.7, 'REB%': 52.9, 'TOV%': 14.1, 'eFG%': 51.1, 'TS%': 54.4, 'PACE': 99.03, 'POSS': 6165, 'TEAM': 'HOU', 'PIE': 50.8}

   OREB  DREB
0     0     4

Dillon Brooks, MAE: 2.756415785276251e-16, RMSE: 5.470128901409763e-16
{'RANK': 27, 'OffRtg': 110.4, 'W': 17, 'L': 45, 'DefRtg': 118.3, 'NetRtg': -7.9, 'AST%': 62.3, 'AST/TO': 1.81, 'ASTRatio': 18.0, 'OREB%': 30.0, 'DREB%': 67.5, 'REB%': 48.2, 'TOV%': 14.0, 'eFG%': 51.8, 'TS%': 55.2, 'PACE': 100.05, 'POSS': 6233, 'TEAM': 'NOP', 'PIE': 46.0}

   OREB  DREB
0     1     2

Jabari Smith Jr., MAE: 4.440892098500626e-16, RMSE: 6.280369834735101e-16
{'RANK': 27, 'OffRtg': 110.4, 'W': 17, 'L': 45, 'DefRtg': 118.3, 'NetRtg': -7.9, 'AST%': 62.3, 'AST/TO': 1.81, 'ASTRatio': 18.0, 'OREB%': 30.0, 'DREB%': 67.5, 'REB%': 48.2, 'TOV%': 14.0, 'eFG%': 51.8, 'TS%': 55.2, 'PACE': 100.05, 'POSS': 6233, 'TEAM': 'NOP', 'PIE': 46.0}

   OREB  DREB
0     2     4

Tari Eason, MAE: 7.216449660063518e-16, RMSE: 9.155133597044475e-16
{'RANK': 27, 'OffRtg': 110.4, 'W': 17, 'L': 45, 'DefRtg': 118.3, 'NetRtg': -7.9, 'AST%': 62.3, 'AST/TO': 1.81, 'ASTRatio': 18.0, 'OREB%': 30.0, 'DREB%': 67.5, 'REB%': 48.2, 'TOV%': 14.0, 'eFG%': 51.8, 'TS%': 55.2, 'PACE': 100.05, 'POSS': 6233, 'TEAM': 'NOP', 'PIE': 46.0}

   OREB  DREB
0     2     3

Kelly Olynyk, MAE: 6.449867095441385e-16, RMSE: 9.025999715631213e-16
{'RANK': 8, 'OffRtg': 113.3, 'W': 37, 'L': 25, 'DefRtg': 109.8, 'NetRtg': 3.5, 'AST%': 54.1, 'AST/TO': 1.61, 'ASTRatio': 15.9, 'OREB%': 36.2, 'DREB%': 70.7, 'REB%': 52.9, 'TOV%': 14.1, 'eFG%': 51.1, 'TS%': 54.4, 'PACE': 99.03, 'POSS': 6165, 'TEAM': 'HOU', 'PIE': 50.8}

   OREB  DREB
0     1     3

Bruce Brown, MAE: 1.1287267417022424e-15, RMSE: 1.4289854171295707e-15
{'RANK': 8, 'OffRtg': 113.3, 'W': 37, 'L': 25, 'DefRtg': 109.8, 'NetRtg': 3.5, 'AST%': 54.1, 'AST/TO': 1.61, 'ASTRatio': 15.9, 'OREB%': 36.2, 'DREB%': 70.7, 'REB%': 52.9, 'TOV%': 14.1, 'eFG%': 51.1, 'TS%': 54.4, 'PACE': 99.03, 'POSS': 6165, 'TEAM': 'HOU', 'PIE': 50.8}

   OREB  DREB
0     1     3

Jose Alvarado, MAE: 0.0, RMSE: 0.0
{'RANK': 8, 'OffRtg': 113.3, 'W': 37, 'L': 25, 'DefRtg': 109.8, 'NetRtg': 3.5, 'AST%': 54.1, 'AST/TO': 1.61, 'ASTRatio': 15.9, 'OREB%': 36.2, 'DREB%': 70.7, 'REB%': 52.9, 'TOV%': 14.1, 'eFG%': 51.1, 'TS%': 54.4, 'PACE': 99.03, 'POSS': 6165, 'TEAM': 'HOU', 'PIE': 50.8}

   OREB  DREB
0     0     2

c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.770e+01, tolerance: 5.683e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.270e+01, tolerance: 5.426e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.042e+01, tolerance: 6.069e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.127e+02, tolerance: 6.163e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.890e+01, tolerance: 5.238e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.767e-01, tolerance: 5.683e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.509e-01, tolerance: 5.426e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.717e-01, tolerance: 6.069e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.938e-02, tolerance: 6.163e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.197e-02, tolerance: 5.238e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.253e+01, tolerance: 5.354e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.629e+01, tolerance: 4.858e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.203e+01, tolerance: 4.876e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.390e+01, tolerance: 4.456e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.563e+01, tolerance: 5.575e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.366e-01, tolerance: 5.354e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.281e+02, tolerance: 7.179e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.231e+02, tolerance: 7.410e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.416e+01, tolerance: 6.819e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.123e+01, tolerance: 7.976e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.308e+01, tolerance: 7.772e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.180e+02, tolerance: 1.123e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.832e+02, tolerance: 9.660e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.445e+02, tolerance: 1.089e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.955e+01, tolerance: 9.329e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.590e+01, tolerance: 1.070e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.694e-01, tolerance: 9.660e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.430e+00, tolerance: 3.101e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.865e+00, tolerance: 2.877e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.386e+00, tolerance: 3.215e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.654e-01, tolerance: 3.064e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.828e-01, tolerance: 2.758e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.330e-01, tolerance: 3.101e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.961e+01, tolerance: 5.886e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.895e+01, tolerance: 6.720e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.134e+01, tolerance: 6.192e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.324e+01, tolerance: 6.067e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.728e+01, tolerance: 5.619e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.846e+01, tolerance: 2.277e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.796e+01, tolerance: 2.373e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.009e+01, tolerance: 2.527e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.636e+01, tolerance: 2.235e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.519e+01, tolerance: 1.919e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.050e-02, tolerance: 2.373e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.215e+00, tolerance: 3.472e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.064e+00, tolerance: 3.097e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.226e+00, tolerance: 3.560e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.115e-01, tolerance: 3.921e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.136e+00, tolerance: 3.790e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.360e+00, tolerance: 2.451e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.075e+01, tolerance: 2.396e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.781e+01, tolerance: 2.691e-02
  model = cd_fast.enet_coordinate_descent(

Franz Wagner, MAE: 2.4210801148985492, RMSE: 2.815413373206107
{'RANK': 23, 'OffRtg': 111.9, 'W': 24, 'L': 38, 'DefRtg': 116.2, 'NetRtg': -4.3, 'AST%': 67.7, 'AST/TO': 1.95, 'ASTRatio': 19.8, 'OREB%': 25.9, 'DREB%': 71.8, 'REB%': 49.1, 'TOV%': 14.3, 'eFG%': 54.8, 'TS%': 57.9, 'PACE': 103.46, 'POSS': 6452, 'TEAM': 'CHI', 'PIE': 48.1}

c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.013e+01, tolerance: 5.434e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.138e+01, tolerance: 5.977e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.650e+01, tolerance: 5.446e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.474e+01, tolerance: 5.386e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.223e+01, tolerance: 4.442e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.543e-02, tolerance: 5.386e-02
  model = cd_fast.enet_coordinate_descent(

   MIN_x  OREB  DREB  STL  BLK  +/-   L  OREB%  DREB%  POSS  team_poss  home_away
0     33     1     4    0    0    0  38   25.9   71.8  6452       6109          0

Paolo Banchero, MAE: 1.168076538454815, RMSE: 1.6803008123181484
{'RANK': 23, 'OffRtg': 111.9, 'W': 24, 'L': 38, 'DefRtg': 116.2, 'NetRtg': -4.3, 'AST%': 67.7, 'AST/TO': 1.95, 'ASTRatio': 19.8, 'OREB%': 25.9, 'DREB%': 71.8, 'REB%': 49.1, 'TOV%': 14.3, 'eFG%': 54.8, 'TS%': 57.9, 'PACE': 103.46, 'POSS': 6452, 'TEAM': 'CHI', 'PIE': 48.1}

   MIN_x  FGA  FG%  3PM  3PA  FTM  OREB  REB  PF  +/-  OffRtg  AST/TO  OREB%  DREB%  TOV%  team_pace  team_offrtg
0     33   19   41    1    5    5     0    6   2   -5   111.9    1.95   25.9   71.8  14.3         96          107

Coby White, MAE: 1.7714545393484602, RMSE: 2.125284804753556
{'RANK': 17, 'OffRtg': 107.4, 'W': 29, 'L': 34, 'DefRtg': 109.2, 'NetRtg': -1.8, 'AST%': 60.9, 'AST/TO': 1.57, 'ASTRatio': 17.0, 'OREB%': 30.5, 'DREB%': 72.8, 'REB%': 50.4, 'TOV%': 15.0, 'eFG%': 50.3, 'TS%': 54.3, 'PACE': 96.63, 'POSS': 6109, 'TEAM': 'ORL', 'PIE': 48.7}

   MIN_x  3PA  FT%  OREB  TOV  +/-  RANK  OREB%  eFG%   PACE
0     32    7   84     0    2   -5    17   30.5  50.3  96.63

Josh Giddey, MAE: 2.5401579462250585, RMSE: 3.022319903228897
{'RANK': 17, 'OffRtg': 107.4, 'W': 29, 'L': 34, 'DefRtg': 109.2, 'NetRtg': -1.8, 'AST%': 60.9, 'AST/TO': 1.57, 'ASTRatio': 17.0, 'OREB%': 30.5, 'DREB%': 72.8, 'REB%': 50.4, 'TOV%': 15.0, 'eFG%': 50.3, 'TS%': 54.3, 'PACE': 96.63, 'POSS': 6109, 'TEAM': 'ORL', 'PIE': 48.7}

   MIN_x  3PM  DREB  BLK  TOV  PF  +/-  AST/TO  DREB%  TOV%  eFG%  team_offrtg  home_away
0     31    1     5    0    2   2   -4    1.57   72.8  15.0  50.3          111          1

Zach Collins, MAE: 0.9526712524866028, RMSE: 1.1945655289437704
{'RANK': 23, 'OffRtg': 111.9, 'W': 24, 'L': 38, 'DefRtg': 116.2, 'NetRtg': -4.3, 'AST%': 67.7, 'AST/TO': 1.95, 'ASTRatio': 19.8, 'OREB%': 25.9, 'DREB%': 71.8, 'REB%': 49.1, 'TOV%': 14.3, 'eFG%': 54.8, 'TS%': 57.9, 'PACE': 103.46, 'POSS': 6452, 'TEAM': 'CHI', 'PIE': 48.1}

   MIN_x  FTA  FT%  STL  BLK  TOV  PF  +/-  eFG%    PACE  team_poss
0     14    1   32    0    0    0   1    0  54.8  103.46       6109

Cole Anthony, MAE: 1.9477836701957958, RMSE: 2.4327045048093567
{'RANK': 23, 'OffRtg': 111.9, 'W': 24, 'L': 38, 'DefRtg': 116.2, 'NetRtg': -4.3, 'AST%': 67.7, 'AST/TO': 1.95, 'ASTRatio': 19.8, 'OREB%': 25.9, 'DREB%': 71.8, 'REB%': 49.1, 'TOV%': 14.3, 'eFG%': 54.8, 'TS%': 57.9, 'PACE': 103.46, 'POSS': 6452, 'TEAM': 'CHI', 'PIE': 48.1}

   MIN_x  3PM  3P%  FT%  REB  PF  +/-  AST/TO  eFG%    PACE  team_pace  team_offrtg
0     24    1   45   53    3   3   -2    1.95  54.8  103.46         96          107

Wendell Carter Jr., MAE: 1.2653898648073658, RMSE: 1.5320386555341767
{'RANK': 23, 'OffRtg': 111.9, 'W': 24, 'L': 38, 'DefRtg': 116.2, 'NetRtg': -4.3, 'AST%': 67.7, 'AST/TO': 1.95, 'ASTRatio': 19.8, 'OREB%': 25.9, 'DREB%': 71.8, 'REB%': 49.1, 'TOV%': 14.3, 'eFG%': 54.8, 'TS%': 57.9, 'PACE': 103.46, 'POSS': 6452, 'TEAM': 'CHI', 'PIE': 48.1}

   MIN_x  FGA  FG%  3PM  3PA  FTM  OREB  REB  PF  +/-  OffRtg  AST/TO  OREB%  DREB%  TOV%  team_pace  team_offrtg
0     26    7   50    0    1    1     2    8   3   -3   111.9    1.95   25.9   71.8  14.3         96          107

Kevin Huerter, MAE: 0.8564314919836468, RMSE: 1.175832427858664
{'RANK': 17, 'OffRtg': 107.4, 'W': 29, 'L': 34, 'DefRtg': 109.2, 'NetRtg': -1.8, 'AST%': 60.9, 'AST/TO': 1.57, 'ASTRatio': 17.0, 'OREB%': 30.5, 'DREB%': 72.8, 'REB%': 50.4, 'TOV%': 15.0, 'eFG%': 50.3, 'TS%': 54.3, 'PACE': 96.63, 'POSS': 6109, 'TEAM': 'ORL', 'PIE': 48.7}

   MIN_x  FGA  3PM  FTM  DREB  REB  +/-   W   PACE  POSS  team_offrtg  home_away
0     16    6    1    0     1    1   -1  29  96.63  6109          111          1

Kentavious Caldwell-Pope, MAE: 0.9823120600625643, RMSE: 1.1360767598391592
{'RANK': 23, 'OffRtg': 111.9, 'W': 24, 'L': 38, 'DefRtg': 116.2, 'NetRtg': -4.3, 'AST%': 67.7, 'AST/TO': 1.95, 'ASTRatio': 19.8, 'OREB%': 25.9, 'DREB%': 71.8, 'REB%': 49.1, 'TOV%': 14.3, 'eFG%': 54.8, 'TS%': 57.9, 'PACE': 103.46, 'POSS': 6452, 'TEAM': 'CHI', 'PIE': 48.1}

   MIN_x  FGA  FG%  FTA  FT%  OREB  BLK  PF  +/-  AST/TO  DREB%    PACE  team_poss  Date_in_Seconds
0     29    6   39    1   46     0    0   1   -7    1.95   71.8  103.46       6109       1739003040

Stephen Curry, MAE: 2.360966809680929, RMSE: 2.904908524506155
{'RANK': 24, 'OffRtg': 108.2, 'W': 21, 'L': 40, 'DefRtg': 115.0, 'NetRtg': -6.7, 'AST%': 66.1, 'AST/TO': 1.6, 'ASTRatio': 18.1, 'OREB%': 30.2, 'DREB%': 69.7, 'REB%': 49.0, 'TOV%': 16.0, 'eFG%': 51.4, 'TS%': 55.3, 'PACE': 96.51, 'POSS': 5915, 'TEAM': 'BKN', 'PIE': 45.5}

   +/-
0    4

Moses Moody, MAE: 0.9824627396862426, RMSE: 1.2482445003786728
{'RANK': 24, 'OffRtg': 108.2, 'W': 21, 'L': 40, 'DefRtg': 115.0, 'NetRtg': -6.7, 'AST%': 66.1, 'AST/TO': 1.6, 'ASTRatio': 18.1, 'OREB%': 30.2, 'DREB%': 69.7, 'REB%': 49.0, 'TOV%': 16.0, 'eFG%': 51.4, 'TS%': 55.3, 'PACE': 96.51, 'POSS': 5915, 'TEAM': 'BKN', 'PIE': 45.5}

   MIN_x  FGM  3PM  3PA  +/-  team_pace  home_away
0     26    4    2    5    5         99          1

Buddy Hield, MAE: 1.4043813669253025, RMSE: 1.7741400320984935
{'RANK': 24, 'OffRtg': 108.2, 'W': 21, 'L': 40, 'DefRtg': 115.0, 'NetRtg': -6.7, 'AST%': 66.1, 'AST/TO': 1.6, 'ASTRatio': 18.1, 'OREB%': 30.2, 'DREB%': 69.7, 'REB%': 49.0, 'TOV%': 16.0, 'eFG%': 51.4, 'TS%': 55.3, 'PACE': 96.51, 'POSS': 5915, 'TEAM': 'BKN', 'PIE': 45.5}

   MIN_x  3PA  FTM  FTA  BLK  TOV  RANK  DefRtg  AST%  AST/TO  REB%  TOV%  team_offrtg
0     22    6    0    0    0    1    24   115.0  66.1     1.6  49.0  16.0          113

Draymond Green, MAE: 1.8228604317659802, RMSE: 2.248002182146451
{'RANK': 24, 'OffRtg': 108.2, 'W': 21, 'L': 40, 'DefRtg': 115.0, 'NetRtg': -6.7, 'AST%': 66.1, 'AST/TO': 1.6, 'ASTRatio': 18.1, 'OREB%': 30.2, 'DREB%': 69.7, 'REB%': 49.0, 'TOV%': 16.0, 'eFG%': 51.4, 'TS%': 55.3, 'PACE': 96.51, 'POSS': 5915, 'TEAM': 'BKN', 'PIE': 45.5}

   MIN_x  FGA  FG%  FTA  FT%  DREB  BLK  PF  +/-  RANK  AST/TO  OREB%  TOV%
0     28    7   43    2   61     4    0   2    7    24     1.6   30.2  16.0

Trendon Watford, MAE: 1.287258533456087, RMSE: 1.739054324998136
{'RANK': 13, 'OffRtg': 113.3, 'W': 34, 'L': 28, 'DefRtg': 111.3, 'NetRtg': 2.0, 'AST%': 70.9, 'AST/TO': 2.12, 'ASTRatio': 20.0, 'OREB%': 31.4, 'DREB%': 71.4, 'REB%': 50.8, 'TOV%': 13.7, 'eFG%': 53.1, 'TS%': 56.0, 'PACE': 99.66, 'POSS': 6191, 'TEAM': 'GSW', 'PIE': 50.8}

   MIN_x  3PM  3PA  FTM  FTA  DREB  STL  AST%  OREB%  DREB%  REB%  eFG%
0     18    0    1    2    2     2    0  70.9   31.4   71.4  50.8  53.1

Ziaire Williams, MAE: 0.9256021652106605, RMSE: 1.1669286044624634
{'RANK': 13, 'OffRtg': 113.3, 'W': 34, 'L': 28, 'DefRtg': 111.3, 'NetRtg': 2.0, 'AST%': 70.9, 'AST/TO': 2.12, 'ASTRatio': 20.0, 'OREB%': 31.4, 'DREB%': 71.4, 'REB%': 50.8, 'TOV%': 13.7, 'eFG%': 53.1, 'TS%': 56.0, 'PACE': 99.66, 'POSS': 6191, 'TEAM': 'GSW', 'PIE': 50.8}

   MIN_x  FGM  FGA  FTA  OREB  DREB  TOV  +/-   W  NetRtg  AST/TO  TOV%
0     25    3    8    1     1     3    0   -5  34     2.0    2.12  13.7

Keon Johnson, MAE: 1.4365626651882757, RMSE: 1.78389036074029
{'RANK': 13, 'OffRtg': 113.3, 'W': 34, 'L': 28, 'DefRtg': 111.3, 'NetRtg': 2.0, 'AST%': 70.9, 'AST/TO': 2.12, 'ASTRatio': 20.0, 'OREB%': 31.4, 'DREB%': 71.4, 'REB%': 50.8, 'TOV%': 13.7, 'eFG%': 53.1, 'TS%': 56.0, 'PACE': 99.66, 'POSS': 6191, 'TEAM': 'GSW', 'PIE': 50.8}

   MIN_x  FTM  OREB  DREB  STL  TOV  +/-  AST%  DREB%  REB%  team_pace
0     27    2     1     3    1    1   -5  70.9   71.4  50.8         96

Day'Ron Sharpe, MAE: 1.0575490117210822, RMSE: 1.4746823839590166
{'RANK': 13, 'OffRtg': 113.3, 'W': 34, 'L': 28, 'DefRtg': 111.3, 'NetRtg': 2.0, 'AST%': 70.9, 'AST/TO': 2.12, 'ASTRatio': 20.0, 'OREB%': 31.4, 'DREB%': 71.4, 'REB%': 50.8, 'TOV%': 13.7, 'eFG%': 53.1, 'TS%': 56.0, 'PACE': 99.66, 'POSS': 6191, 'TEAM': 'GSW', 'PIE': 50.8}

   MIN_x  FGM  FGA  3PM  DREB  STL  BLK  PF  RANK  AST/TO  team_pace
0     17    3    6    0     3    0    1   3    13    2.12         96

Kevon Looney, MAE: 1.010127614843095, RMSE: 1.2606023357099592
{'RANK': 24, 'OffRtg': 108.2, 'W': 21, 'L': 40, 'DefRtg': 115.0, 'NetRtg': -6.7, 'AST%': 66.1, 'AST/TO': 1.6, 'ASTRatio': 18.1, 'OREB%': 30.2, 'DREB%': 69.7, 'REB%': 49.0, 'TOV%': 16.0, 'eFG%': 51.4, 'TS%': 55.3, 'PACE': 96.51, 'POSS': 5915, 'TEAM': 'BKN', 'PIE': 45.5}

   MIN_x  PTS  FGM  FTA  FT%  DREB  REB  STL  BLK  TOV  +/-  AST%  OREB%  home_away
0     15    4    1    1   34     3    6    0    0    0    3  66.1   30.2          1

Alperen Sengun, MAE: 1.7681492692519787, RMSE: 2.060843121154812
{'RANK': 27, 'OffRtg': 110.4, 'W': 17, 'L': 45, 'DefRtg': 118.3, 'NetRtg': -7.9, 'AST%': 62.3, 'AST/TO': 1.81, 'ASTRatio': 18.0, 'OREB%': 30.0, 'DREB%': 67.5, 'REB%': 48.2, 'TOV%': 14.0, 'eFG%': 51.8, 'TS%': 55.2, 'PACE': 100.05, 'POSS': 6233, 'TEAM': 'NOP', 'PIE': 46.0}

   MIN_x  FGA  FG%  3PA  3P%  FTM  FTA  OREB  BLK  PF  +/-  OffRtg  DefRtg  REB%
0     30   14   46    1   15    4    6     3    0   2    1   110.4   118.3  48.2

Jalen Green, MAE: 1.931975559414216, RMSE: 2.4556167631294192
{'RANK': 27, 'OffRtg': 110.4, 'W': 17, 'L': 45, 'DefRtg': 118.3, 'NetRtg': -7.9, 'AST%': 62.3, 'AST/TO': 1.81, 'ASTRatio': 18.0, 'OREB%': 30.0, 'DREB%': 67.5, 'REB%': 48.2, 'TOV%': 14.0, 'eFG%': 51.8, 'TS%': 55.2, 'PACE': 100.05, 'POSS': 6233, 'TEAM': 'NOP', 'PIE': 46.0}

   MIN_x  FGA  FG%  3PM  3PA  FTM  OREB  REB  PF  +/-  OffRtg  AST/TO  OREB%  DREB%  TOV%  team_pace  team_offrtg
0     34   18   40    3    8    2     0    4   1   -3   110.4    1.81   30.0   67.5  14.0         99          113

CJ McCollum, MAE: 1.7991253962787739, RMSE: 2.2189358132122274
{'RANK': 8, 'OffRtg': 113.3, 'W': 37, 'L': 25, 'DefRtg': 109.8, 'NetRtg': 3.5, 'AST%': 54.1, 'AST/TO': 1.61, 'ASTRatio': 15.9, 'OREB%': 36.2, 'DREB%': 70.7, 'REB%': 52.9, 'TOV%': 14.1, 'eFG%': 51.1, 'TS%': 54.4, 'PACE': 99.03, 'POSS': 6165, 'TEAM': 'HOU', 'PIE': 50.8}

   MIN_x  FGA  FG%  3PM  3PA  FTM  OREB  REB  PF  +/-  OffRtg  AST/TO  OREB%  DREB%  TOV%  team_pace  team_offrtg
0     32   17   42    2    7    2     0    3   2   -3   113.3    1.61   36.2   70.7  14.1        100          110

Trey Murphy III, MAE: 2.221085644219721, RMSE: 2.84352009907398
{'RANK': 8, 'OffRtg': 113.3, 'W': 37, 'L': 25, 'DefRtg': 109.8, 'NetRtg': 3.5, 'AST%': 54.1, 'AST/TO': 1.61, 'ASTRatio': 15.9, 'OREB%': 36.2, 'DREB%': 70.7, 'REB%': 52.9, 'TOV%': 14.1, 'eFG%': 51.1, 'TS%': 54.4, 'PACE': 99.03, 'POSS': 6165, 'TEAM': 'HOU', 'PIE': 50.8}

   MIN_x  3P%  BLK  TOV  PF  +/-  DefRtg  ASTRatio  DREB%  REB%  eFG%  team_offrtg  Date_in_Seconds
0     36   36    0    2   2   -6   109.8      15.9   70.7  52.9  51.1          110       1739115360

Dillon Brooks, MAE: 1.070350646145692, RMSE: 1.3102378689454717
{'RANK': 27, 'OffRtg': 110.4, 'W': 17, 'L': 45, 'DefRtg': 118.3, 'NetRtg': -7.9, 'AST%': 62.3, 'AST/TO': 1.81, 'ASTRatio': 18.0, 'OREB%': 30.0, 'DREB%': 67.5, 'REB%': 48.2, 'TOV%': 14.0, 'eFG%': 51.8, 'TS%': 55.2, 'PACE': 100.05, 'POSS': 6233, 'TEAM': 'NOP', 'PIE': 46.0}

   MIN_x  FG%  DREB  +/-  AST%  OREB%  team_offrtg
0     32   41     2   -2  62.3   30.0          113

Jabari Smith Jr., MAE: 0.651508121793711, RMSE: 0.7437058229788098
{'RANK': 27, 'OffRtg': 110.4, 'W': 17, 'L': 45, 'DefRtg': 118.3, 'NetRtg': -7.9, 'AST%': 62.3, 'AST/TO': 1.81, 'ASTRatio': 18.0, 'OREB%': 30.0, 'DREB%': 67.5, 'REB%': 48.2, 'TOV%': 14.0, 'eFG%': 51.8, 'TS%': 55.2, 'PACE': 100.05, 'POSS': 6233, 'TEAM': 'NOP', 'PIE': 46.0}

   MIN_x  FGM  FG%  DREB  PF   W  MIN_y  ASTRatio  REB%
0     33    3   37     4   2  17   2982      18.0  48.2

Tari Eason, MAE: 1.0631334197305802, RMSE: 1.3543506865009953
{'RANK': 27, 'OffRtg': 110.4, 'W': 17, 'L': 45, 'DefRtg': 118.3, 'NetRtg': -7.9, 'AST%': 62.3, 'AST/TO': 1.81, 'ASTRatio': 18.0, 'OREB%': 30.0, 'DREB%': 67.5, 'REB%': 48.2, 'TOV%': 14.0, 'eFG%': 51.8, 'TS%': 55.2, 'PACE': 100.05, 'POSS': 6233, 'TEAM': 'NOP', 'PIE': 46.0}

   MIN_x  FGA  FG%  3PM  3PA  FTM  OREB  REB  PF  +/-  OffRtg  AST/TO  OREB%  DREB%  TOV%  team_pace  team_offrtg
0     25    9   48    1    3    1     2    6   2    0   110.4    1.81   30.0   67.5  14.0         99          113

Kelly Olynyk, MAE: 1.528916976597439, RMSE: 1.9189865009553693
{'RANK': 8, 'OffRtg': 113.3, 'W': 37, 'L': 25, 'DefRtg': 109.8, 'NetRtg': 3.5, 'AST%': 54.1, 'AST/TO': 1.61, 'ASTRatio': 15.9, 'OREB%': 36.2, 'DREB%': 70.7, 'REB%': 52.9, 'TOV%': 14.1, 'eFG%': 51.1, 'TS%': 54.4, 'PACE': 99.03, 'POSS': 6165, 'TEAM': 'HOU', 'PIE': 50.8}

   MIN_x  FGM  FG%  3PM  3PA  3P%  FTA  FT%  DREB  TOV  +/-  TOV%  eFG%   PIE  team_pace  Date_in_Seconds
0     18    3   52    0    1   33    2   48     3    1    1  14.1  51.1  50.8        100       1738091520

Bruce Brown, MAE: 1.0762116003860607, RMSE: 1.386270984358712
{'RANK': 8, 'OffRtg': 113.3, 'W': 37, 'L': 25, 'DefRtg': 109.8, 'NetRtg': 3.5, 'AST%': 54.1, 'AST/TO': 1.61, 'ASTRatio': 15.9, 'OREB%': 36.2, 'DREB%': 70.7, 'REB%': 52.9, 'TOV%': 14.1, 'eFG%': 51.1, 'TS%': 54.4, 'PACE': 99.03, 'POSS': 6165, 'TEAM': 'HOU', 'PIE': 50.8}

   MIN_x  PTS  FG%  3P%  FTA  DREB  STL  TOV  PF  +/-   W  MIN_y  REB%  team_offrtg
0     20    7   35   22    1     3    1    0   1   -2  37   2973  52.9          110

Jose Alvarado, MAE: 1.5233394091743688, RMSE: 1.8659730629210063
{'RANK': 8, 'OffRtg': 113.3, 'W': 37, 'L': 25, 'DefRtg': 109.8, 'NetRtg': 3.5, 'AST%': 54.1, 'AST/TO': 1.61, 'ASTRatio': 15.9, 'OREB%': 36.2, 'DREB%': 70.7, 'REB%': 52.9, 'TOV%': 14.1, 'eFG%': 51.1, 'TS%': 54.4, 'PACE': 99.03, 'POSS': 6165, 'TEAM': 'HOU', 'PIE': 50.8}

   MIN_x  FG%  3PM  3P%  DREB  STL  PF  +/-  GP  AST%  DREB%  REB%  team_offrtg
0     24   38    1   30     2    1   1   -2  61  54.1   70.7  52.9          110

Franz Wagner, MAE: 7.500173321912169e-15, RMSE: 9.24919361948025e-15
{'RANK': 23, 'OffRtg': 111.9, 'W': 24, 'L': 38, 'DefRtg': 116.2, 'NetRtg': -4.3, 'AST%': 67.7, 'AST/TO': 1.95, 'ASTRatio': 19.8, 'OREB%': 25.9, 'DREB%': 71.8, 'REB%': 49.1, 'TOV%': 14.3, 'eFG%': 54.8, 'TS%': 57.9, 'PACE': 103.46, 'POSS': 6452, 'TEAM': 'CHI', 'PIE': 48.1}

   FGM  FGA  FG%  3PM  FTM
0    9   20   47    1    5

Paolo Banchero, MAE: 3.3242200196811935, RMSE: 3.9569822333128983
{'RANK': 23, 'OffRtg': 111.9, 'W': 24, 'L': 38, 'DefRtg': 116.2, 'NetRtg': -4.3, 'AST%': 67.7, 'AST/TO': 1.95, 'ASTRatio': 19.8, 'OREB%': 25.9, 'DREB%': 71.8, 'REB%': 49.1, 'TOV%': 14.3, 'eFG%': 54.8, 'TS%': 57.9, 'PACE': 103.46, 'POSS': 6452, 'TEAM': 'CHI', 'PIE': 48.1}

   FGM  3PM  FTM
0    8    1    5

Coby White, MAE: 1.9871719379839403, RMSE: 2.7178738928927357
{'RANK': 17, 'OffRtg': 107.4, 'W': 29, 'L': 34, 'DefRtg': 109.2, 'NetRtg': -1.8, 'AST%': 60.9, 'AST/TO': 1.57, 'ASTRatio': 17.0, 'OREB%': 30.5, 'DREB%': 72.8, 'REB%': 50.4, 'TOV%': 15.0, 'eFG%': 50.3, 'TS%': 54.3, 'PACE': 96.63, 'POSS': 6109, 'TEAM': 'ORL', 'PIE': 48.7}

   FGM  3PM  FTM
0    6    2    3

Josh Giddey, MAE: 1.9031853533506322, RMSE: 2.362615020627684
{'RANK': 17, 'OffRtg': 107.4, 'W': 29, 'L': 34, 'DefRtg': 109.2, 'NetRtg': -1.8, 'AST%': 60.9, 'AST/TO': 1.57, 'ASTRatio': 17.0, 'OREB%': 30.5, 'DREB%': 72.8, 'REB%': 50.4, 'TOV%': 15.0, 'eFG%': 50.3, 'TS%': 54.3, 'PACE': 96.63, 'POSS': 6109, 'TEAM': 'ORL', 'PIE': 48.7}

   FGM  3PM  FTM
0    5    1    2

Zach Collins, MAE: 1.2266383252784798, RMSE: 1.5646719136674763
{'RANK': 23, 'OffRtg': 111.9, 'W': 24, 'L': 38, 'DefRtg': 116.2, 'NetRtg': -4.3, 'AST%': 67.7, 'AST/TO': 1.95, 'ASTRatio': 19.8, 'OREB%': 25.9, 'DREB%': 71.8, 'REB%': 49.1, 'TOV%': 14.3, 'eFG%': 54.8, 'TS%': 57.9, 'PACE': 103.46, 'POSS': 6452, 'TEAM': 'CHI', 'PIE': 48.1}

   MIN_x  FGM  3PM  FTM
0     14    2    0    1

Cole Anthony, MAE: 2.3189318305204734, RMSE: 2.721804629506037
{'RANK': 23, 'OffRtg': 111.9, 'W': 24, 'L': 38, 'DefRtg': 116.2, 'NetRtg': -4.3, 'AST%': 67.7, 'AST/TO': 1.95, 'ASTRatio': 19.8, 'OREB%': 25.9, 'DREB%': 71.8, 'REB%': 49.1, 'TOV%': 14.3, 'eFG%': 54.8, 'TS%': 57.9, 'PACE': 103.46, 'POSS': 6452, 'TEAM': 'CHI', 'PIE': 48.1}

   FGM  3PM  FTM
0    4    1    1

Wendell Carter Jr., MAE: 1.0872528930811877e-15, RMSE: 1.3322676295501878e-15
{'RANK': 23, 'OffRtg': 111.9, 'W': 24, 'L': 38, 'DefRtg': 116.2, 'NetRtg': -4.3, 'AST%': 67.7, 'AST/TO': 1.95, 'ASTRatio': 19.8, 'OREB%': 25.9, 'DREB%': 71.8, 'REB%': 49.1, 'TOV%': 14.3, 'eFG%': 54.8, 'TS%': 57.9, 'PACE': 103.46, 'POSS': 6452, 'TEAM': 'CHI', 'PIE': 48.1}

   FGM  FGA  3PM  FTM
0    3    7    0    1

Kevin Huerter, MAE: 1.3754543215775403, RMSE: 1.7921277345907252
{'RANK': 17, 'OffRtg': 107.4, 'W': 29, 'L': 34, 'DefRtg': 109.2, 'NetRtg': -1.8, 'AST%': 60.9, 'AST/TO': 1.57, 'ASTRatio': 17.0, 'OREB%': 30.5, 'DREB%': 72.8, 'REB%': 50.4, 'TOV%': 15.0, 'eFG%': 50.3, 'TS%': 54.3, 'PACE': 96.63, 'POSS': 6109, 'TEAM': 'ORL', 'PIE': 48.7}

   MIN_x  FGM  3PM  FTM
0     16    2    1    0

Kentavious Caldwell-Pope, MAE: 1.3828721474600827, RMSE: 1.8143761890967303
{'RANK': 23, 'OffRtg': 111.9, 'W': 24, 'L': 38, 'DefRtg': 116.2, 'NetRtg': -4.3, 'AST%': 67.7, 'AST/TO': 1.95, 'ASTRatio': 19.8, 'OREB%': 25.9, 'DREB%': 71.8, 'REB%': 49.1, 'TOV%': 14.3, 'eFG%': 54.8, 'TS%': 57.9, 'PACE': 103.46, 'POSS': 6452, 'TEAM': 'CHI', 'PIE': 48.1}

   FGM  3PM  FTM
0    2    0    1

Stephen Curry, MAE: 2.9864959769485404, RMSE: 4.053167263112166
{'RANK': 24, 'OffRtg': 108.2, 'W': 21, 'L': 40, 'DefRtg': 115.0, 'NetRtg': -6.7, 'AST%': 66.1, 'AST/TO': 1.6, 'ASTRatio': 18.1, 'OREB%': 30.2, 'DREB%': 69.7, 'REB%': 49.0, 'TOV%': 16.0, 'eFG%': 51.4, 'TS%': 55.3, 'PACE': 96.51, 'POSS': 5915, 'TEAM': 'BKN', 'PIE': 45.5}

   FGM  3PM  FTM
0    8    4    4

Moses Moody, MAE: 1.6561714038520574, RMSE: 2.016174083374746
{'RANK': 24, 'OffRtg': 108.2, 'W': 21, 'L': 40, 'DefRtg': 115.0, 'NetRtg': -6.7, 'AST%': 66.1, 'AST/TO': 1.6, 'ASTRatio': 18.1, 'OREB%': 30.2, 'DREB%': 69.7, 'REB%': 49.0, 'TOV%': 16.0, 'eFG%': 51.4, 'TS%': 55.3, 'PACE': 96.51, 'POSS': 5915, 'TEAM': 'BKN', 'PIE': 45.5}

   MIN_x  FGM  3PM  FTM
0     26    4    2    1

Buddy Hield, MAE: 2.575717417130363e-15, RMSE: 3.081010585207313e-15
{'RANK': 24, 'OffRtg': 108.2, 'W': 21, 'L': 40, 'DefRtg': 115.0, 'NetRtg': -6.7, 'AST%': 66.1, 'AST/TO': 1.6, 'ASTRatio': 18.1, 'OREB%': 30.2, 'DREB%': 69.7, 'REB%': 49.0, 'TOV%': 16.0, 'eFG%': 51.4, 'TS%': 55.3, 'PACE': 96.51, 'POSS': 5915, 'TEAM': 'BKN', 'PIE': 45.5}

   FGM  FGA  FG%  3PM  FTM  FT%
0    3    9   37    2    0   21

Draymond Green, MAE: 1.8675660921489303, RMSE: 2.275743838234478
{'RANK': 24, 'OffRtg': 108.2, 'W': 21, 'L': 40, 'DefRtg': 115.0, 'NetRtg': -6.7, 'AST%': 66.1, 'AST/TO': 1.6, 'ASTRatio': 18.1, 'OREB%': 30.2, 'DREB%': 69.7, 'REB%': 49.0, 'TOV%': 16.0, 'eFG%': 51.4, 'TS%': 55.3, 'PACE': 96.51, 'POSS': 5915, 'TEAM': 'BKN', 'PIE': 45.5}

   FGM  3PM  FTM
0    3    0    1

Trendon Watford, MAE: 2.812564995717063e-15, RMSE: 3.5155114632813414e-15
{'RANK': 13, 'OffRtg': 113.3, 'W': 34, 'L': 28, 'DefRtg': 111.3, 'NetRtg': 2.0, 'AST%': 70.9, 'AST/TO': 2.12, 'ASTRatio': 20.0, 'OREB%': 31.4, 'DREB%': 71.4, 'REB%': 50.8, 'TOV%': 13.7, 'eFG%': 53.1, 'TS%': 56.0, 'PACE': 99.66, 'POSS': 6191, 'TEAM': 'GSW', 'PIE': 50.8}

   FGM  FGA  3PM  FTM  FTA
0    3    7    0    2    2

Ziaire Williams, MAE: 1.609889738997231, RMSE: 2.076436315258968
{'RANK': 13, 'OffRtg': 113.3, 'W': 34, 'L': 28, 'DefRtg': 111.3, 'NetRtg': 2.0, 'AST%': 70.9, 'AST/TO': 2.12, 'ASTRatio': 20.0, 'OREB%': 31.4, 'DREB%': 71.4, 'REB%': 50.8, 'TOV%': 13.7, 'eFG%': 53.1, 'TS%': 56.0, 'PACE': 99.66, 'POSS': 6191, 'TEAM': 'GSW', 'PIE': 50.8}

   FGM  3PM  FTM  FTA
0    3    1    1    1

Keon Johnson, MAE: 1.8228363779902608, RMSE: 2.2496810492974246
{'RANK': 13, 'OffRtg': 113.3, 'W': 34, 'L': 28, 'DefRtg': 111.3, 'NetRtg': 2.0, 'AST%': 70.9, 'AST/TO': 2.12, 'ASTRatio': 20.0, 'OREB%': 31.4, 'DREB%': 71.4, 'REB%': 50.8, 'TOV%': 13.7, 'eFG%': 53.1, 'TS%': 56.0, 'PACE': 99.66, 'POSS': 6191, 'TEAM': 'GSW', 'PIE': 50.8}

   MIN_x  FGM  3PM  FTM  FTA
0     27    4    1    2    2

Day'Ron Sharpe, MAE: 1.5382690699961334, RMSE: 2.0681787723466822
{'RANK': 13, 'OffRtg': 113.3, 'W': 34, 'L': 28, 'DefRtg': 111.3, 'NetRtg': 2.0, 'AST%': 70.9, 'AST/TO': 2.12, 'ASTRatio': 20.0, 'OREB%': 31.4, 'DREB%': 71.4, 'REB%': 50.8, 'TOV%': 13.7, 'eFG%': 53.1, 'TS%': 56.0, 'PACE': 99.66, 'POSS': 6191, 'TEAM': 'GSW', 'PIE': 50.8}

   FGM  3PM  FTM
0    3    0    1

Kevon Looney, MAE: 1.2404081468627959, RMSE: 1.5523525491999253
{'RANK': 24, 'OffRtg': 108.2, 'W': 21, 'L': 40, 'DefRtg': 115.0, 'NetRtg': -6.7, 'AST%': 66.1, 'AST/TO': 1.6, 'ASTRatio': 18.1, 'OREB%': 30.2, 'DREB%': 69.7, 'REB%': 49.0, 'TOV%': 16.0, 'eFG%': 51.4, 'TS%': 55.3, 'PACE': 96.51, 'POSS': 5915, 'TEAM': 'BKN', 'PIE': 45.5}

   FGM  FTM
0    1    1

Alperen Sengun, MAE: 2.0076048656271173, RMSE: 2.6613600728395346
{'RANK': 27, 'OffRtg': 110.4, 'W': 17, 'L': 45, 'DefRtg': 118.3, 'NetRtg': -7.9, 'AST%': 62.3, 'AST/TO': 1.81, 'ASTRatio': 18.0, 'OREB%': 30.0, 'DREB%': 67.5, 'REB%': 48.2, 'TOV%': 14.0, 'eFG%': 51.8, 'TS%': 55.2, 'PACE': 100.05, 'POSS': 6233, 'TEAM': 'NOP', 'PIE': 46.0}

   FGM  3PM  FTM  FTA
0    7    0    4    6

Jalen Green, MAE: 2.108008582216533, RMSE: 2.574327937554638
{'RANK': 27, 'OffRtg': 110.4, 'W': 17, 'L': 45, 'DefRtg': 118.3, 'NetRtg': -7.9, 'AST%': 62.3, 'AST/TO': 1.81, 'ASTRatio': 18.0, 'OREB%': 30.0, 'DREB%': 67.5, 'REB%': 48.2, 'TOV%': 14.0, 'eFG%': 51.8, 'TS%': 55.2, 'PACE': 100.05, 'POSS': 6233, 'TEAM': 'NOP', 'PIE': 46.0}

   FGM  3PM  FTM
0    7    3    2

CJ McCollum, MAE: 1.640135744657087, RMSE: 2.114749140156739
{'RANK': 8, 'OffRtg': 113.3, 'W': 37, 'L': 25, 'DefRtg': 109.8, 'NetRtg': 3.5, 'AST%': 54.1, 'AST/TO': 1.61, 'ASTRatio': 15.9, 'OREB%': 36.2, 'DREB%': 70.7, 'REB%': 52.9, 'TOV%': 14.1, 'eFG%': 51.1, 'TS%': 54.4, 'PACE': 99.03, 'POSS': 6165, 'TEAM': 'HOU', 'PIE': 50.8}

   FGM  3PM  FTM
0    7    2    2

Trey Murphy III, MAE: 3.3377319013379396, RMSE: 3.966525391916553
{'RANK': 8, 'OffRtg': 113.3, 'W': 37, 'L': 25, 'DefRtg': 109.8, 'NetRtg': 3.5, 'AST%': 54.1, 'AST/TO': 1.61, 'ASTRatio': 15.9, 'OREB%': 36.2, 'DREB%': 70.7, 'REB%': 52.9, 'TOV%': 14.1, 'eFG%': 51.1, 'TS%': 54.4, 'PACE': 99.03, 'POSS': 6165, 'TEAM': 'HOU', 'PIE': 50.8}

   FGM  3PM  FTM
0    7    3    3

Dillon Brooks, MAE: 2.312326575426188e-15, RMSE: 3.71460163628924e-15
{'RANK': 27, 'OffRtg': 110.4, 'W': 17, 'L': 45, 'DefRtg': 118.3, 'NetRtg': -7.9, 'AST%': 62.3, 'AST/TO': 1.81, 'ASTRatio': 18.0, 'OREB%': 30.0, 'DREB%': 67.5, 'REB%': 48.2, 'TOV%': 14.0, 'eFG%': 51.8, 'TS%': 55.2, 'PACE': 100.05, 'POSS': 6233, 'TEAM': 'NOP', 'PIE': 46.0}

   FGM  FGA  FG%  3PM  FTM  FTA
0    4   11   41    2    1    1

Jabari Smith Jr., MAE: 3.774758283725532e-15, RMSE: 4.39625888431457e-15
{'RANK': 27, 'OffRtg': 110.4, 'W': 17, 'L': 45, 'DefRtg': 118.3, 'NetRtg': -7.9, 'AST%': 62.3, 'AST/TO': 1.81, 'ASTRatio': 18.0, 'OREB%': 30.0, 'DREB%': 67.5, 'REB%': 48.2, 'TOV%': 14.0, 'eFG%': 51.8, 'TS%': 55.2, 'PACE': 100.05, 'POSS': 6233, 'TEAM': 'NOP', 'PIE': 46.0}

   FGM  FGA  FG%  3PM  FTM
0    3   10   37    1    1

Tari Eason, MAE: 1.7283155701416755, RMSE: 2.0329435570012455
{'RANK': 27, 'OffRtg': 110.4, 'W': 17, 'L': 45, 'DefRtg': 118.3, 'NetRtg': -7.9, 'AST%': 62.3, 'AST/TO': 1.81, 'ASTRatio': 18.0, 'OREB%': 30.0, 'DREB%': 67.5, 'REB%': 48.2, 'TOV%': 14.0, 'eFG%': 51.8, 'TS%': 55.2, 'PACE': 100.05, 'POSS': 6233, 'TEAM': 'NOP', 'PIE': 46.0}

   FGM  3PM  FTM  FTA
0    4    1    1    2

Kelly Olynyk, MAE: 1.3907565443267618, RMSE: 1.6639241868038999
{'RANK': 8, 'OffRtg': 113.3, 'W': 37, 'L': 25, 'DefRtg': 109.8, 'NetRtg': 3.5, 'AST%': 54.1, 'AST/TO': 1.61, 'ASTRatio': 15.9, 'OREB%': 36.2, 'DREB%': 70.7, 'REB%': 52.9, 'TOV%': 14.1, 'eFG%': 51.1, 'TS%': 54.4, 'PACE': 99.03, 'POSS': 6165, 'TEAM': 'HOU', 'PIE': 50.8}

   MIN_x  FGM  3PM  FTM
0     18    3    0    1

Bruce Brown, MAE: 1.0981178152814632, RMSE: 1.2075957773420003
{'RANK': 8, 'OffRtg': 113.3, 'W': 37, 'L': 25, 'DefRtg': 109.8, 'NetRtg': 3.5, 'AST%': 54.1, 'AST/TO': 1.61, 'ASTRatio': 15.9, 'OREB%': 36.2, 'DREB%': 70.7, 'REB%': 52.9, 'TOV%': 14.1, 'eFG%': 51.1, 'TS%': 54.4, 'PACE': 99.03, 'POSS': 6165, 'TEAM': 'HOU', 'PIE': 50.8}

   FGM  3PM  FTM  FTA
0    3    0    1    1

Jose Alvarado, MAE: 3.026385726385612e-15, RMSE: 4.030470348909677e-15
{'RANK': 8, 'OffRtg': 113.3, 'W': 37, 'L': 25, 'DefRtg': 109.8, 'NetRtg': 3.5, 'AST%': 54.1, 'AST/TO': 1.61, 'ASTRatio': 15.9, 'OREB%': 36.2, 'DREB%': 70.7, 'REB%': 52.9, 'TOV%': 14.1, 'eFG%': 51.1, 'TS%': 54.4, 'PACE': 99.03, 'POSS': 6165, 'TEAM': 'HOU', 'PIE': 50.8}

   FGM  FGA  3PM  FTM  FTA  FT%
0    3    7    1    0    1   41

c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.990e+00, tolerance: 7.403e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.832e+01, tolerance: 6.485e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.541e+00, tolerance: 6.828e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.109e+00, tolerance: 6.748e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.008e+00, tolerance: 6.166e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.218e-02, tolerance: 6.166e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.288e+01, tolerance: 5.813e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.672e+01, tolerance: 5.482e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.316e+00, tolerance: 5.179e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.258e+00, tolerance: 5.393e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.627e+00, tolerance: 4.717e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.264e-01, tolerance: 8.500e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.036e+01, tolerance: 9.615e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.642e+00, tolerance: 8.459e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.024e+00, tolerance: 8.655e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.414e+00, tolerance: 9.295e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.685e+00, tolerance: 4.635e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.393e+00, tolerance: 4.771e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.190e+01, tolerance: 4.294e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.603e-01, tolerance: 4.733e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.681e+00, tolerance: 4.652e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.758e+00, tolerance: 3.545e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.768e+00, tolerance: 1.875e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.000e+00, tolerance: 3.535e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.362e+00, tolerance: 3.600e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.844e+00, tolerance: 3.424e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.512e-01, tolerance: 5.740e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.426e-01, tolerance: 5.546e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.201e-01, tolerance: 5.248e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.406e+00, tolerance: 5.519e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.627e+00, tolerance: 5.052e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.022e-01, tolerance: 3.300e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.769e+00, tolerance: 2.513e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.244e-01, tolerance: 3.203e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.520e+00, tolerance: 2.784e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.322e-01, tolerance: 3.008e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.829e+00, tolerance: 8.898e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.643e+00, tolerance: 8.011e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.608e+00, tolerance: 8.189e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.247e+00, tolerance: 7.701e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.264e+00, tolerance: 8.057e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.729e+00, tolerance: 1.025e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.729e+00, tolerance: 1.025e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.591e-01, tolerance: 4.897e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.279e+00, tolerance: 4.457e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.777e+00, tolerance: 4.584e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.643e+00, tolerance: 3.928e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.077e+00, tolerance: 4.758e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.751e-01, tolerance: 1.760e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.006e+00, tolerance: 1.724e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.005e-01, tolerance: 1.377e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.011e-01, tolerance: 1.577e-01
  model = cd_fast.enet_coordinate_descent(

Franz Wagner, MAE: 1.936870637807149e-15, RMSE: 2.7884460304914936e-15
{'RANK': 23, 'OffRtg': 111.9, 'W': 24, 'L': 38, 'DefRtg': 116.2, 'NetRtg': -4.3, 'AST%': 67.7, 'AST/TO': 1.95, 'ASTRatio': 19.8, 'OREB%': 25.9, 'DREB%': 71.8, 'REB%': 49.1, 'TOV%': 14.3, 'eFG%': 54.8, 'TS%': 57.9, 'PACE': 103.46, 'POSS': 6452, 'TEAM': 'CHI', 'PIE': 48.1}

c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.698e+00, tolerance: 5.989e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.352e+00, tolerance: 6.695e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.264e+00, tolerance: 6.475e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.979e-01, tolerance: 5.964e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.952e-01, tolerance: 6.130e-02
  model = cd_fast.enet_coordinate_descent(

   MIN_x  FGA  FG%  3PM  3P%  FTA  FT%  AST/TO  home_away
0     33   20   47    1   24    6   75    1.95          0

Paolo Banchero, MAE: 6.229064813514905e-13, RMSE: 6.232207387497657e-13
{'RANK': 23, 'OffRtg': 111.9, 'W': 24, 'L': 38, 'DefRtg': 116.2, 'NetRtg': -4.3, 'AST%': 67.7, 'AST/TO': 1.95, 'ASTRatio': 19.8, 'OREB%': 25.9, 'DREB%': 71.8, 'REB%': 49.1, 'TOV%': 14.3, 'eFG%': 54.8, 'TS%': 57.9, 'PACE': 103.46, 'POSS': 6452, 'TEAM': 'CHI', 'PIE': 48.1}

   FGA  FG%  3PM  3P%  TOV  PF  +/-  AST%  Date_in_Seconds
0   19   41    1   26    3   2   -5  67.7       1739067840

Coby White, MAE: 1.4706538326913298e-15, RMSE: 1.745093261946325e-15
{'RANK': 17, 'OffRtg': 107.4, 'W': 29, 'L': 34, 'DefRtg': 109.2, 'NetRtg': -1.8, 'AST%': 60.9, 'AST/TO': 1.57, 'ASTRatio': 17.0, 'OREB%': 30.5, 'DREB%': 72.8, 'REB%': 50.4, 'TOV%': 15.0, 'eFG%': 50.3, 'TS%': 54.3, 'PACE': 96.63, 'POSS': 6109, 'TEAM': 'ORL', 'PIE': 48.7}

   MIN_x  FGM  FGA  3PM  3P%  DREB  AST  TOV  PF  DefRtg  team_offrtg  home_away
0     32    6   14    2   36     3    4    2   1   109.2          111          1

Josh Giddey, MAE: 1.902638098637468e-13, RMSE: 1.905523806655732e-13
{'RANK': 17, 'OffRtg': 107.4, 'W': 29, 'L': 34, 'DefRtg': 109.2, 'NetRtg': -1.8, 'AST%': 60.9, 'AST/TO': 1.57, 'ASTRatio': 17.0, 'OREB%': 30.5, 'DREB%': 72.8, 'REB%': 50.4, 'TOV%': 15.0, 'eFG%': 50.3, 'TS%': 54.3, 'PACE': 96.63, 'POSS': 6109, 'TEAM': 'ORL', 'PIE': 48.7}

   FGA  FG%  3PM  3P%  FTA  DefRtg  TOV%  Date_in_Seconds
0   11   47    1   42    3   109.2  15.0       1738864800

Zach Collins, MAE: 9.332547960598458e-15, RMSE: 1.0667183126524578e-14
{'RANK': 23, 'OffRtg': 111.9, 'W': 24, 'L': 38, 'DefRtg': 116.2, 'NetRtg': -4.3, 'AST%': 67.7, 'AST/TO': 1.95, 'ASTRatio': 19.8, 'OREB%': 25.9, 'DREB%': 71.8, 'REB%': 49.1, 'TOV%': 14.3, 'eFG%': 54.8, 'TS%': 57.9, 'PACE': 103.46, 'POSS': 6452, 'TEAM': 'CHI', 'PIE': 48.1}

   MIN_x  FGA  FG%  3PM  3P%  STL  TOV   L  DefRtg  POSS  team_poss
0     14    4   47    0   18    0    0  38   116.2  6452       6109

Cole Anthony, MAE: 2.8106099226674714e-14, RMSE: 2.9422030273609037e-14
{'RANK': 23, 'OffRtg': 111.9, 'W': 24, 'L': 38, 'DefRtg': 116.2, 'NetRtg': -4.3, 'AST%': 67.7, 'AST/TO': 1.95, 'ASTRatio': 19.8, 'OREB%': 25.9, 'DREB%': 71.8, 'REB%': 49.1, 'TOV%': 14.3, 'eFG%': 54.8, 'TS%': 57.9, 'PACE': 103.46, 'POSS': 6452, 'TEAM': 'CHI', 'PIE': 48.1}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTM  FT%  DREB  STL  BLK  TOV  PF  +/-  RANK   L  DefRtg  AST/TO  REB%   TS%    PACE   PIE  POSS  home_away
0     24    4   10   45    1   45    1   53     2    1    0    1   3   -2    23  38   116.2    1.95  49.1  57.9  103.46  48.1  6452          0

Wendell Carter Jr., MAE: 1.993593297594752e-14, RMSE: 2.1088609857647105e-14
{'RANK': 23, 'OffRtg': 111.9, 'W': 24, 'L': 38, 'DefRtg': 116.2, 'NetRtg': -4.3, 'AST%': 67.7, 'AST/TO': 1.95, 'ASTRatio': 19.8, 'OREB%': 25.9, 'DREB%': 71.8, 'REB%': 49.1, 'TOV%': 14.3, 'eFG%': 54.8, 'TS%': 57.9, 'PACE': 103.46, 'POSS': 6452, 'TEAM': 'CHI', 'PIE': 48.1}

   MIN_x  FGM  FGA  3PM  3P%  FT%  OREB  DREB  STL  BLK  TOV  PF  +/-  RANK  MIN_y  OffRtg  NetRtg  ASTRatio  OREB%  REB%  TOV%  eFG%    PACE  team_pace  home_away
0     26    3    7    0   19   50     2     5    0    0    1   3   -3    23   2986   111.9    -4.3      19.8   25.9  49.1  14.3  54.8  103.46         96          0

Kevin Huerter, MAE: 5.362475322065297e-12, RMSE: 6.807353521587786e-12
{'RANK': 17, 'OffRtg': 107.4, 'W': 29, 'L': 34, 'DefRtg': 109.2, 'NetRtg': -1.8, 'AST%': 60.9, 'AST/TO': 1.57, 'ASTRatio': 17.0, 'OREB%': 30.5, 'DREB%': 72.8, 'REB%': 50.4, 'TOV%': 15.0, 'eFG%': 50.3, 'TS%': 54.3, 'PACE': 96.63, 'POSS': 6109, 'TEAM': 'ORL', 'PIE': 48.7}

   MIN_x  PTS  FGM  FGA  FG%  3PM  3P%  FTA  FT%  OREB  REB  AST  STL  BLK  TOV  PF  +/-  RANK  GP   W  MIN_y  OffRtg  DefRtg  AST%  AST/TO  OREB%  DREB%  REB%  TOV%  eFG%   TS%   PACE   PIE  POSS  team_poss  Date_in_Seconds  home_away
0     16    7    2    6   33    1   28    0   22     0    1    1    0    0    0   0   -1    17  61  29   2981   107.4   109.2  60.9    1.57   30.5   72.8  50.4  15.0  50.3  54.3  96.63  48.7  6109       6452       1738208160          1

Kentavious Caldwell-Pope, MAE: 6.142337400255828e-15, RMSE: 7.849292258926702e-15
{'RANK': 23, 'OffRtg': 111.9, 'W': 24, 'L': 38, 'DefRtg': 116.2, 'NetRtg': -4.3, 'AST%': 67.7, 'AST/TO': 1.95, 'ASTRatio': 19.8, 'OREB%': 25.9, 'DREB%': 71.8, 'REB%': 49.1, 'TOV%': 14.3, 'eFG%': 54.8, 'TS%': 57.9, 'PACE': 103.46, 'POSS': 6452, 'TEAM': 'CHI', 'PIE': 48.1}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTM  FT%  OREB  REB  AST  STL  BLK  TOV  PF  RANK  GP   W  AST%  OREB%  REB%  TOV%   TS%    PACE   PIE  team_pace  home_away
0     29    2    6   39    0   28    1   46     0    2    1    0    0    0   1    23  61  24  67.7   25.9  49.1  14.3  57.9  103.46  48.1         96          0

Stephen Curry, MAE: 7.317494758278069e-11, RMSE: 7.32344804549658e-11
{'RANK': 24, 'OffRtg': 108.2, 'W': 21, 'L': 40, 'DefRtg': 115.0, 'NetRtg': -6.7, 'AST%': 66.1, 'AST/TO': 1.6, 'ASTRatio': 18.1, 'OREB%': 30.2, 'DREB%': 69.7, 'REB%': 49.0, 'TOV%': 16.0, 'eFG%': 51.4, 'TS%': 55.3, 'PACE': 96.51, 'POSS': 5915, 'TEAM': 'BKN', 'PIE': 45.5}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTM  FTA  FT%  OREB  REB  AST  STL  BLK  TOV  PF  RANK   W  MIN_y  AST/TO  ASTRatio  OREB%  DREB%   PACE   PIE  POSS  Date_in_Seconds  home_away
0     32    8   19   44    4   36    4    4   88     0    3    6    0    0    2   1    24  21   2975     1.6      18.1   30.2   69.7  96.51  45.5  5915       1739184480          1

Moses Moody, MAE: 5.434477195024259e-15, RMSE: 6.2348996557353206e-15
{'RANK': 24, 'OffRtg': 108.2, 'W': 21, 'L': 40, 'DefRtg': 115.0, 'NetRtg': -6.7, 'AST%': 66.1, 'AST/TO': 1.6, 'ASTRatio': 18.1, 'OREB%': 30.2, 'DREB%': 69.7, 'REB%': 49.0, 'TOV%': 16.0, 'eFG%': 51.4, 'TS%': 55.3, 'PACE': 96.51, 'POSS': 5915, 'TEAM': 'BKN', 'PIE': 45.5}

   FGM  FGA  3PM  3P%  FTM  FT%  OREB  DREB  AST  STL  BLK  TOV  +/-  RANK  DefRtg  AST%  AST/TO  DREB%  REB%   TS%   PACE  team_offrtg  home_away
0    4    9    2   35    1   57     0     2    1    0    0    0    5    24   115.0  66.1     1.6   69.7  49.0  55.3  96.51          113          1

Buddy Hield, MAE: 4.661135070470403e-15, RMSE: 6.259453591095532e-15
{'RANK': 24, 'OffRtg': 108.2, 'W': 21, 'L': 40, 'DefRtg': 115.0, 'NetRtg': -6.7, 'AST%': 66.1, 'AST/TO': 1.6, 'ASTRatio': 18.1, 'OREB%': 30.2, 'DREB%': 69.7, 'REB%': 49.0, 'TOV%': 16.0, 'eFG%': 51.4, 'TS%': 55.3, 'PACE': 96.51, 'POSS': 5915, 'TEAM': 'BKN', 'PIE': 45.5}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTA  FT%  DREB  TOV  PF  +/-  RANK  GP  DefRtg  AST%  REB%  TOV%   TS%   PACE  POSS  team_offrtg  home_away
0     22    3    9   37    2   30    0   21     2    1   1    2    24  61   115.0  66.1  49.0  16.0  55.3  96.51  5915          113          1

Draymond Green, MAE: 4.30813902556493e-14, RMSE: 4.365989302407954e-14
{'RANK': 24, 'OffRtg': 108.2, 'W': 21, 'L': 40, 'DefRtg': 115.0, 'NetRtg': -6.7, 'AST%': 66.1, 'AST/TO': 1.6, 'ASTRatio': 18.1, 'OREB%': 30.2, 'DREB%': 69.7, 'REB%': 49.0, 'TOV%': 16.0, 'eFG%': 51.4, 'TS%': 55.3, 'PACE': 96.51, 'POSS': 5915, 'TEAM': 'BKN', 'PIE': 45.5}

   FGA  FG%  3PM  3P%  AST  GP  POSS  home_away
0    7   43    0   20    5  61  5915          1

Trendon Watford, MAE: 4.265932453438247e-15, RMSE: 5.8665983050841965e-15
{'RANK': 13, 'OffRtg': 113.3, 'W': 34, 'L': 28, 'DefRtg': 111.3, 'NetRtg': 2.0, 'AST%': 70.9, 'AST/TO': 2.12, 'ASTRatio': 20.0, 'OREB%': 31.4, 'DREB%': 71.4, 'REB%': 50.8, 'TOV%': 13.7, 'eFG%': 53.1, 'TS%': 56.0, 'PACE': 99.66, 'POSS': 6191, 'TEAM': 'GSW', 'PIE': 50.8}

   FGM  FGA  FG%  3PM  3P%  FTA  FT%  OREB  DREB  AST  STL  BLK  TOV  PF  +/-  GP   W  OffRtg  AST/TO  OREB%  DREB%  REB%  TOV%   PACE   PIE  home_away
0    3    7   43    0   25    2   62     0     2    2    0    0    1   2    0  61  34   113.3    2.12   31.4   71.4  50.8  13.7  99.66  50.8          0

Ziaire Williams, MAE: 1.1728232312639163e-14, RMSE: 1.2287629756341105e-14
{'RANK': 13, 'OffRtg': 113.3, 'W': 34, 'L': 28, 'DefRtg': 111.3, 'NetRtg': 2.0, 'AST%': 70.9, 'AST/TO': 2.12, 'ASTRatio': 20.0, 'OREB%': 31.4, 'DREB%': 71.4, 'REB%': 50.8, 'TOV%': 13.7, 'eFG%': 53.1, 'TS%': 56.0, 'PACE': 99.66, 'POSS': 6191, 'TEAM': 'GSW', 'PIE': 50.8}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTM  FT%  OREB  AST  BLK  TOV  PF  +/-   W   L  OffRtg  NetRtg  AST/TO  REB%  TOV%   PACE  team_pace
0     25    3    8   37    1   30    1   69     1    1    0    0   2   -5  34  28   113.3     2.0    2.12  50.8  13.7  99.66         96

Keon Johnson, MAE: 8.876872174797749e-15, RMSE: 1.0862863212940013e-14
{'RANK': 13, 'OffRtg': 113.3, 'W': 34, 'L': 28, 'DefRtg': 111.3, 'NetRtg': 2.0, 'AST%': 70.9, 'AST/TO': 2.12, 'ASTRatio': 20.0, 'OREB%': 31.4, 'DREB%': 71.4, 'REB%': 50.8, 'TOV%': 13.7, 'eFG%': 53.1, 'TS%': 56.0, 'PACE': 99.66, 'POSS': 6191, 'TEAM': 'GSW', 'PIE': 50.8}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTM  FTA  FT%  OREB  DREB  AST  STL  BLK  TOV  PF  +/-  RANK  DefRtg  AST%  AST/TO  OREB%  DREB%  TOV%  eFG%   PACE  team_poss
0     27    4   12   36    1   25    2    2   63     1     3    2    1    0    1   2   -5    13   111.3  70.9    2.12   31.4   71.4  13.7  53.1  99.66       5915

Day'Ron Sharpe, MAE: 1.9483547668233021e-13, RMSE: 1.951870436822498e-13
{'RANK': 13, 'OffRtg': 113.3, 'W': 34, 'L': 28, 'DefRtg': 111.3, 'NetRtg': 2.0, 'AST%': 70.9, 'AST/TO': 2.12, 'ASTRatio': 20.0, 'OREB%': 31.4, 'DREB%': 71.4, 'REB%': 50.8, 'TOV%': 13.7, 'eFG%': 53.1, 'TS%': 56.0, 'PACE': 99.66, 'POSS': 6191, 'TEAM': 'GSW', 'PIE': 50.8}

   FGA  3PM   L  team_poss
0    6    0  28       5915

Kevon Looney, MAE: 0.0, RMSE: 0.0
{'RANK': 24, 'OffRtg': 108.2, 'W': 21, 'L': 40, 'DefRtg': 115.0, 'NetRtg': -6.7, 'AST%': 66.1, 'AST/TO': 1.6, 'ASTRatio': 18.1, 'OREB%': 30.2, 'DREB%': 69.7, 'REB%': 49.0, 'TOV%': 16.0, 'eFG%': 51.4, 'TS%': 55.3, 'PACE': 96.51, 'POSS': 5915, 'TEAM': 'BKN', 'PIE': 45.5}

   MIN_x  PTS  FGM  FGA  FG%  3PM  3P%  FTA  FT%  OREB  REB  AST  STL  BLK  TOV  PF  +/-  RANK  GP   W  MIN_y  OffRtg  DefRtg  AST%  AST/TO  OREB%  DREB%  REB%  TOV%  eFG%   TS%   PACE   PIE  POSS  team_poss  Date_in_Seconds  home_away
0     15    4    1    3   41    0    0    1   34     2    6    1    0    0    0   2    3    24  61  21   2974   108.2   115.0  66.1     1.6   30.2   69.7  49.0  16.0  51.4  55.3  96.51  45.5  5915       6191       1739219040          1

Alperen Sengun, MAE: 3.3998133830745934e-15, RMSE: 3.818294718323344e-15
{'RANK': 27, 'OffRtg': 110.4, 'W': 17, 'L': 45, 'DefRtg': 118.3, 'NetRtg': -7.9, 'AST%': 62.3, 'AST/TO': 1.81, 'ASTRatio': 18.0, 'OREB%': 30.0, 'DREB%': 67.5, 'REB%': 48.2, 'TOV%': 14.0, 'eFG%': 51.8, 'TS%': 55.2, 'PACE': 100.05, 'POSS': 6233, 'TEAM': 'NOP', 'PIE': 46.0}

   MIN_x  PTS  FGM  FGA  FG%  3PM  3P%  FTA  FT%  OREB  AST  BLK  TOV  PF  +/-   W   L  OffRtg  NetRtg  OREB%  DREB%  REB%    PACE  team_offrtg  home_away
0     30   19    7   14   46    0   15    6   64     3    4    0    2   2    1  17  45   110.4    -7.9   30.0   67.5  48.2  100.05          113          1

Jalen Green, MAE: 4.543573354820584e-15, RMSE: 5.196929986363286e-15
{'RANK': 27, 'OffRtg': 110.4, 'W': 17, 'L': 45, 'DefRtg': 118.3, 'NetRtg': -7.9, 'AST%': 62.3, 'AST/TO': 1.81, 'ASTRatio': 18.0, 'OREB%': 30.0, 'DREB%': 67.5, 'REB%': 48.2, 'TOV%': 14.0, 'eFG%': 51.8, 'TS%': 55.2, 'PACE': 100.05, 'POSS': 6233, 'TEAM': 'NOP', 'PIE': 46.0}

   MIN_x  FGA  FG%  3PM  3P%  FTM  FTA  FT%  OREB  DREB  AST  STL  TOV  PF  +/-  RANK   L  ASTRatio  DREB%  REB%  eFG%   TS%    PACE   PIE  team_offrtg  home_away
0     34   18   40    3   34    2    3   62     0     3    4    0    2   1   -3    27  45      18.0   67.5  48.2  51.8  55.2  100.05  46.0          113          1

CJ McCollum, MAE: 5.991200918571196e-14, RMSE: 6.050892532415324e-14
{'RANK': 8, 'OffRtg': 113.3, 'W': 37, 'L': 25, 'DefRtg': 109.8, 'NetRtg': 3.5, 'AST%': 54.1, 'AST/TO': 1.61, 'ASTRatio': 15.9, 'OREB%': 36.2, 'DREB%': 70.7, 'REB%': 52.9, 'TOV%': 14.1, 'eFG%': 51.1, 'TS%': 54.4, 'PACE': 99.03, 'POSS': 6165, 'TEAM': 'HOU', 'PIE': 50.8}

   FGM  FGA  FG%  3PM  3P%  FTA  FT%  DREB  REB  AST  STL  TOV  PF  +/-  AST%  OREB%  DREB%  REB%  eFG%   PACE  team_pace  team_poss  home_away
0    7   17   42    2   34    3   69     3    3    4    0    2   2   -3  54.1   36.2   70.7  52.9  51.1  99.03        100       6233          0

Trey Murphy III, MAE: 2.9669529397416192e-09, RMSE: 4.0367942394001145e-09
{'RANK': 8, 'OffRtg': 113.3, 'W': 37, 'L': 25, 'DefRtg': 109.8, 'NetRtg': 3.5, 'AST%': 54.1, 'AST/TO': 1.61, 'ASTRatio': 15.9, 'OREB%': 36.2, 'DREB%': 70.7, 'REB%': 52.9, 'TOV%': 14.1, 'eFG%': 51.1, 'TS%': 54.4, 'PACE': 99.03, 'POSS': 6165, 'TEAM': 'HOU', 'PIE': 50.8}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTA  FT%  OREB  AST  STL  BLK  TOV  PF  +/-   L  MIN_y  DefRtg  AST%  AST/TO  OREB%  DREB%  eFG%   TS%   PACE  team_pace  Date_in_Seconds  home_away
0     36    7   16   45    3   36    4   78     0    5    1    0    2   2   -6  25   2975   109.8  54.1    1.61   36.2   70.7  51.1  54.4  99.03        100       1739115360          0

Dillon Brooks, MAE: 2.4972761653758742e-15, RMSE: 3.0568281750630362e-15
{'RANK': 27, 'OffRtg': 110.4, 'W': 17, 'L': 45, 'DefRtg': 118.3, 'NetRtg': -7.9, 'AST%': 62.3, 'AST/TO': 1.81, 'ASTRatio': 18.0, 'OREB%': 30.0, 'DREB%': 67.5, 'REB%': 48.2, 'TOV%': 14.0, 'eFG%': 51.8, 'TS%': 55.2, 'PACE': 100.05, 'POSS': 6233, 'TEAM': 'NOP', 'PIE': 46.0}

   MIN_x  FGA  FG%  3PM  3P%  OREB  OREB%  REB%  home_away
0     32   11   41    2   39     1   30.0  48.2          1

Jabari Smith Jr., MAE: 2.525166219072384e-15, RMSE: 2.9336440047842704e-15
{'RANK': 27, 'OffRtg': 110.4, 'W': 17, 'L': 45, 'DefRtg': 118.3, 'NetRtg': -7.9, 'AST%': 62.3, 'AST/TO': 1.81, 'ASTRatio': 18.0, 'OREB%': 30.0, 'DREB%': 67.5, 'REB%': 48.2, 'TOV%': 14.0, 'eFG%': 51.8, 'TS%': 55.2, 'PACE': 100.05, 'POSS': 6233, 'TEAM': 'NOP', 'PIE': 46.0}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTM  FTA  OREB  DREB  AST  STL  BLK  TOV  +/-  RANK  DefRtg  NetRtg  AST/TO  OREB%  DREB%  eFG%    PACE  team_pace  team_offrtg  home_away
0     33    3   10   37    1   33    1    2     2     4    1    0    1    1    0    27   118.3    -7.9    1.81   30.0   67.5  51.8  100.05         99          113          1

Tari Eason, MAE: 3.406351504671835e-15, RMSE: 4.846807948555385e-15
{'RANK': 27, 'OffRtg': 110.4, 'W': 17, 'L': 45, 'DefRtg': 118.3, 'NetRtg': -7.9, 'AST%': 62.3, 'AST/TO': 1.81, 'ASTRatio': 18.0, 'OREB%': 30.0, 'DREB%': 67.5, 'REB%': 48.2, 'TOV%': 14.0, 'eFG%': 51.8, 'TS%': 55.2, 'PACE': 100.05, 'POSS': 6233, 'TEAM': 'NOP', 'PIE': 46.0}

   FGA  FG%  3PM  3P%  OREB  BLK  GP  DefRtg  DREB%  REB%   PIE
0    9   48    1   36     2    0  61   118.3   67.5  48.2  46.0

Kelly Olynyk, MAE: 1.3704353808438476e-12, RMSE: 1.3717029132797566e-12
{'RANK': 8, 'OffRtg': 113.3, 'W': 37, 'L': 25, 'DefRtg': 109.8, 'NetRtg': 3.5, 'AST%': 54.1, 'AST/TO': 1.61, 'ASTRatio': 15.9, 'OREB%': 36.2, 'DREB%': 70.7, 'REB%': 52.9, 'TOV%': 14.1, 'eFG%': 51.1, 'TS%': 54.4, 'PACE': 99.03, 'POSS': 6165, 'TEAM': 'HOU', 'PIE': 50.8}

   MIN_x  FGA  FG%  3PM  3P%  OREB  STL  team_pace  Date_in_Seconds
0     18    5   52    0   33     1    0        100       1738091520

Bruce Brown, MAE: 4.249537052537571e-12, RMSE: 4.252365243854536e-12
{'RANK': 8, 'OffRtg': 113.3, 'W': 37, 'L': 25, 'DefRtg': 109.8, 'NetRtg': 3.5, 'AST%': 54.1, 'AST/TO': 1.61, 'ASTRatio': 15.9, 'OREB%': 36.2, 'DREB%': 70.7, 'REB%': 52.9, 'TOV%': 14.1, 'eFG%': 51.1, 'TS%': 54.4, 'PACE': 99.03, 'POSS': 6165, 'TEAM': 'HOU', 'PIE': 50.8}

   MIN_x  FGM  FGA  3PM  3P%  FTA  FT%  DREB  REB  AST  STL  BLK  TOV  PF  +/-  RANK  DefRtg  AST%  AST/TO  REB%  eFG%   TS%   PACE  Date_in_Seconds  home_away
0     20    3    7    0   22    1   53     3    4    1    1    0    0   1   -2     8   109.8  54.1    1.61  52.9  51.1  54.4  99.03       1738717920          0

Jose Alvarado, MAE: 7.1901674250174164e-12, RMSE: 7.195166307404787e-12
{'RANK': 8, 'OffRtg': 113.3, 'W': 37, 'L': 25, 'DefRtg': 109.8, 'NetRtg': 3.5, 'AST%': 54.1, 'AST/TO': 1.61, 'ASTRatio': 15.9, 'OREB%': 36.2, 'DREB%': 70.7, 'REB%': 52.9, 'TOV%': 14.1, 'eFG%': 51.1, 'TS%': 54.4, 'PACE': 99.03, 'POSS': 6165, 'TEAM': 'HOU', 'PIE': 50.8}

   FGA  FG%  3PM  3P%  OREB  PF   PACE  Date_in_Seconds
0    7   38    1   30     0   1  99.03       1739024640

                      Player  REB      RMSE_reb  AST  RMSE_ast  PTS      RMSE_pts  3PM      RMSE_3pm  total_points
0               Franz Wagner    5  1.046728e-16    6  2.815413   20  9.249194e-15    1  2.788446e-15            32
1             Paolo Banchero    4  8.694778e-16    5  1.680301   17  3.956982e+00    0  6.232207e-13            26
2                 Coby White    3  1.705557e-15    4  2.125285   13  2.717874e+00    2  1.745093e-15            22
3                Josh Giddey    6  1.532062e-15    6  3.022320   11  2.362615e+00    0  1.905524e-13            23
4               Zach Collins    3  2.163024e-15    1  1.194566    4  1.564672e+00    0  1.066718e-14             8
5               Cole Anthony    2  9.659088e-16    4  2.432705    8  2.721805e+00    1  2.942203e-14            15
6         Wendell Carter Jr.    6  1.147128e-15    2  1.532039    7  1.332268e-15    0  2.108861e-14            15
7              Kevin Huerter    1  1.430833e-15    0  1.175832    5  1.792128e+00    1  6.807354e-12             7
8   Kentavious Caldwell-Pope    0  8.757557e-16    1  1.136077    6  1.814376e+00    0  7.849292e-15             7
9              Stephen Curry    3  5.233642e-16    5  2.904909   18  4.053167e+00    3  7.323448e-11            29
10               Moses Moody    2  1.104658e-15    1  1.248245    8  2.016174e+00    1  6.234900e-15            12
11               Buddy Hield    1  4.931857e-16    1  1.774140    8  3.081011e-15    1  6.259454e-15            11
12            Draymond Green    5  7.246279e-16    5  2.248002    6  2.275744e+00    0  4.365989e-14            16
13           Trendon Watford    1  1.321430e-15    1  1.739054    6  3.515511e-15    0  5.866598e-15             8
14           Ziaire Williams    4  2.133336e-16    0  1.166929    6  2.076436e+00    0  1.228763e-14            10
15              Keon Johnson    4  1.604501e-15    1  1.783890   10  2.249681e+00    1  1.086286e-14            16
16            Day'Ron Sharpe    5  9.605652e-16    2  1.474682    5  2.068179e+00    0  1.951870e-13            12
17              Kevon Looney    4  1.768409e-15    2  1.260602    2  1.552353e+00    0  0.000000e+00             8
18            Alperen Sengun   10  1.769940e-15    4  2.060843   13  2.661360e+00    0  3.818295e-15            27
19               Jalen Green    3  7.308383e-16    2  2.455617   16  2.574328e+00    2  5.196930e-15            23
20               CJ McCollum    3  6.783575e-16    3  2.218936   16  2.114749e+00    2  6.050893e-14            24
21           Trey Murphy III    4  1.037834e-15    2  2.843520   13  3.966525e+00    2  4.036794e-09            21
22             Dillon Brooks    3  5.470129e-16    1  1.310238   11  3.714602e-15    2  3.056828e-15            17
23          Jabari Smith Jr.    6  6.280370e-16    1  0.743706    9  4.396259e-15    1  2.933644e-15            17
24                Tari Eason    4  9.155134e-16    1  1.354351    8  2.032944e+00    1  4.846808e-15            14
25              Kelly Olynyk    4  9.026000e-16    3  1.918987    6  1.663924e+00    0  1.371703e-12            13
26               Bruce Brown    4  1.428985e-15    0  1.386271    7  1.207596e+00    0  4.252365e-12            11
27             Jose Alvarado    2  0.000000e+00    5  1.865973    7  4.030470e-15    1  7.195166e-12            15