In [4]:
from prediction import prediction

# players_teams = {
#     "Mark Williams": "CHA",
#     # "Miles Bridges": "CHA",
#     # "Jimmy Butler": "GSW",
#     "LaMelo Ball": "CHA",
#     "Stephen Curry": "GSW",
#     # "Brandin Podziemski": "GSW",
#     # "Nick Smith Jr.": "CHA",
#     "Josh Green": "CHA",
#     "Moses Moody": "GSW",
#     "Draymond Green": "GSW",
#     "Paul George": "PHI",
#     "Tyrese Maxey": "PHI",
#     "Kelly Oubre Jr.": "PHI",
#     "Andre Drummond": "PHI",
#     "Shaedon Sharpe": "POR",
#     "Quentin Grimes": "PHI",
#     "Deni Avdija": "POR",
#     "Anfernee Simons": "POR",
#     # "Toumani Camara": "POR",
#     # "Donovan Clingan": "POR",
#     "Bam Adebayo": "MIA",
#     "Tyler Herro": "MIA",
#     "Andrew Wiggins": "MIA",
#     # "Bilal Coulibaly": "WAS",
#     # "Alexandre Sarr": "WAS",
#     "Khris Middleton": "WAS",
#     # "Carlton Carrington": "WAS",
#     "Davion Mitchell": "MIA",
#     # "Kyshawn George": "WAS",
#     "Haywood Highsmith": "MIA"
# }



# players_teams = {
#     "Giannis Antetokounmpo": "MIL",
#     "Trae Young": "ATL",
#     "Damian Lillard": "MIL",
#     "Dyson Daniels": "ATL",
#     "Brook Lopez": "MIL",
#     "Taurean Prince": "MIL",
#     "Onyeka Okongwu": "ATL",
#     "Jalen Brunson": "NYK",
#     "Karl-Anthony Towns": "NYK",
#     "Mikal Bridges": "NYK",
#     "Moses Moody": "GSW",
#     "Stephen Curry": "GSW",
#     "Josh Hart": "NYK",
#     # "Brandin Podziemski": "GSW",
#     "OG Anunoby": "NYK",
#     "Draymond Green": "GSW",
#     "Paolo Banchero": "ORL",
#     "Franz Wagner": "ORL",
#     "Jakob Poeltl": "TOR",
#     "Immanuel Quickley": "TOR",
#     "Scottie Barnes": "TOR",
#     "RJ Barrett": "TOR",
#     "Wendell Carter Jr.": "ORL",
#     "Cole Anthony": "ORL",
#     "Kentavious Caldwell-Pope": "ORL",
#     # "Ja'Kobe Walter": "TOR",
#     "Donovan Mitchell": "CLE",
#     "Darius Garland": "CLE",
#     "Jarrett Allen": "CLE",
#     "Josh Giddey": "CHI",
#     "Coby White": "CHI",
#     # "Matas Buzelis": "CHI",
#     "Max Strus": "CLE",
#     "Dean Wade": "CLE",
#     "Zach Collins": "CHI",
#     # "Lonzo Ball": "CHI"
# }



players_teams = {
    "Jonas Valanciunas": "SAC",
    "Jamal Murray": "DEN",
    "DeMar DeRozan": "SAC",
    "Michael Porter Jr.": "DEN",
    "Christian Braun": "DEN",
    "Keegan Murray": "SAC",
    "Aaron Gordon": "DEN",
    "Russell Westbrook": "DEN",
    "Keon Ellis": "SAC",
    "Trey Lyles": "SAC",
    "Markelle Fultz": "SAC",
    "Jake LaRavia": "SAC",
    "Shai Gilgeous-Alexander": "OKC",
    "Desmond Bane": "MEM",
    "Jalen Williams": "OKC",
    "Ja Morant": "MEM",
    "Santi Aldama": "MEM",
    # "Jaylen Wells": "MEM",
    "Aaron Wiggins": "OKC",
    "Isaiah Hartenstein": "OKC",
    # "Cason Wallace": "OKC",
    "Brandon Clarke": "MEM",
    "Luguentz Dort": "OKC",
    "Isaiah Joe": "OKC",
    # "Zach Edey": "MEM",
    "Kenrich Williams": "OKC",
    "James Harden": "LAC",
    "Malik Beasley": "DET",
    "Ivica Zubac": "LAC",
    # "Bogdan Bogdanovic": "LAC",
    # "Ausar Thompson": "DET",
    "Jalen Duren": "DET",
    "Amir Coffey": "LAC",
    "Tim Hardaway Jr.": "DET",
    # "Dennis Schroder": "DET",
    "Kris Dunn": "LAC",
    # "Ron Holland II": "DET",
    "Isaiah Stewart": "DET"
}




import pandas as pd
date_list = ["2022-23","2023-24","2024-25"]
usage_path = "D:/nba_usage_csv_historic/usage_csv_{date}/{date}_content.csv"
schedule_base_path = "D:/nba_scheduled_csv/schedule_csv_2025/{schedule_team}_schedule_content.csv"
player_base_path = "D:/nba_player_csv_historic/season_{date}/all_quarters/{player}_content.csv"
defense_base_path = "D:/nba_defense_history_csv/defense_csv_{date}/all_quarter_defense_content.csv"

results_reb = prediction(players_teams, date_list, usage_path, player_base_path, defense_base_path, schedule_base_path,'REB','REB')
results_ast = prediction(players_teams, date_list, usage_path, player_base_path, defense_base_path, schedule_base_path,'AST','AST')
results_pts = prediction(players_teams, date_list, usage_path, player_base_path, defense_base_path, schedule_base_path,'PTS','FGA')
results_3pm = prediction(players_teams, date_list, usage_path, player_base_path, defense_base_path, schedule_base_path,'3PA','3PM')


df_combined = pd.concat([results_reb, results_ast, results_pts, results_3pm], axis=0, ignore_index=True)

df_merged = results_reb.merge(results_ast, on='Player', suffixes=('_reb', '_ast')) \
    .merge(results_pts, on='Player', suffixes=('_pts', '_extra')) \
    .merge(results_3pm, on='Player', suffixes=('_3pm', '_final'))


df_merged['total_points'] = df_merged[['FGA', 'AST', 'REB','3PM']].sum(axis=1)
df_merged = df_merged.rename(columns={'FGA': 'PTS'})

display(df_merged)

Jonas Valanciunas, MAE: 2.854859206178974e-16, RMSE: 6.792221739132951e-16
{'RANK': 5, 'OffRtg': 119.1, 'W': 39, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.2, 'eFG%': 57.4, 'TS%': 60.5, 'PACE': 101.04, 'POSS': 6201, 'TEAM': 'DEN', 'PIE': 53.3}

   OREB  DREB
0     2     4

Jamal Murray, MAE: 0.0, RMSE: 0.0
{'RANK': 14, 'OffRtg': 115.9, 'W': 32, 'L': 28, 'DefRtg': 113.8, 'NetRtg': 2.1, 'AST%': 62.0, 'AST/TO': 2.0, 'ASTRatio': 19.0, 'OREB%': 29.4, 'DREB%': 72.8, 'REB%': 51.2, 'TOV%': 13.4, 'eFG%': 54.7, 'TS%': 58.2, 'PACE': 99.8, 'POSS': 6054, 'TEAM': 'SAC', 'PIE': 51.0}

   OREB  DREB
0     0     2

DeMar DeRozan, MAE: 2.4671622769447922e-17, RMSE: 9.555278410998351e-17
{'RANK': 5, 'OffRtg': 119.1, 'W': 39, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.2, 'eFG%': 57.4, 'TS%': 60.5, 'PACE': 101.04, 'POSS': 6201, 'TEAM': 'DEN', 'PIE': 53.3}

   OREB  DREB
0     0     3

Michael Porter Jr., MAE: 1.0197604078038475e-15, RMSE: 1.538370149106851e-15
{'RANK': 14, 'OffRtg': 115.9, 'W': 32, 'L': 28, 'DefRtg': 113.8, 'NetRtg': 2.1, 'AST%': 62.0, 'AST/TO': 2.0, 'ASTRatio': 19.0, 'OREB%': 29.4, 'DREB%': 72.8, 'REB%': 51.2, 'TOV%': 13.4, 'eFG%': 54.7, 'TS%': 58.2, 'PACE': 99.8, 'POSS': 6054, 'TEAM': 'SAC', 'PIE': 51.0}

   OREB  DREB
0     2     4

Christian Braun, MAE: 8.289665250534502e-16, RMSE: 1.081731794890875e-15
{'RANK': 14, 'OffRtg': 115.9, 'W': 32, 'L': 28, 'DefRtg': 113.8, 'NetRtg': 2.1, 'AST%': 62.0, 'AST/TO': 2.0, 'ASTRatio': 19.0, 'OREB%': 29.4, 'DREB%': 72.8, 'REB%': 51.2, 'TOV%': 13.4, 'eFG%': 54.7, 'TS%': 58.2, 'PACE': 99.8, 'POSS': 6054, 'TEAM': 'SAC', 'PIE': 51.0}

   OREB  DREB
0     1     4

Keegan Murray, MAE: 3.1974423109204507e-16, RMSE: 6.404745667978754e-16
{'RANK': 5, 'OffRtg': 119.1, 'W': 39, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.2, 'eFG%': 57.4, 'TS%': 60.5, 'PACE': 101.04, 'POSS': 6201, 'TEAM': 'DEN', 'PIE': 53.3}

   OREB  DREB
0     1     4

Aaron Gordon, MAE: 1.5659987926291681e-15, RMSE: 1.7557862568130812e-15
{'RANK': 14, 'OffRtg': 115.9, 'W': 32, 'L': 28, 'DefRtg': 113.8, 'NetRtg': 2.1, 'AST%': 62.0, 'AST/TO': 2.0, 'ASTRatio': 19.0, 'OREB%': 29.4, 'DREB%': 72.8, 'REB%': 51.2, 'TOV%': 13.4, 'eFG%': 54.7, 'TS%': 58.2, 'PACE': 99.8, 'POSS': 6054, 'TEAM': 'SAC', 'PIE': 51.0}

   OREB  DREB
0     1     2

Russell Westbrook, MAE: 7.144043810631442e-16, RMSE: 1.0185890151905064e-15
{'RANK': 14, 'OffRtg': 115.9, 'W': 32, 'L': 28, 'DefRtg': 113.8, 'NetRtg': 2.1, 'AST%': 62.0, 'AST/TO': 2.0, 'ASTRatio': 19.0, 'OREB%': 29.4, 'DREB%': 72.8, 'REB%': 51.2, 'TOV%': 13.4, 'eFG%': 54.7, 'TS%': 58.2, 'PACE': 99.8, 'POSS': 6054, 'TEAM': 'SAC', 'PIE': 51.0}

   OREB  DREB
0     1     3

Keon Ellis, MAE: 1.0197604078038475e-15, RMSE: 1.3171042345699646e-15
{'RANK': 5, 'OffRtg': 119.1, 'W': 39, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.2, 'eFG%': 57.4, 'TS%': 60.5, 'PACE': 101.04, 'POSS': 6201, 'TEAM': 'DEN', 'PIE': 53.3}

   OREB  DREB
0     0     2

Trey Lyles, MAE: 6.5759363766259275e-16, RMSE: 8.319552826452395e-16
{'RANK': 5, 'OffRtg': 119.1, 'W': 39, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.2, 'eFG%': 57.4, 'TS%': 60.5, 'PACE': 101.04, 'POSS': 6201, 'TEAM': 'DEN', 'PIE': 53.3}

   OREB  DREB
0     0     2

Markelle Fultz, MAE: 1.3322676295501878e-15, RMSE: 1.3831079839119408e-15
{'RANK': 5, 'OffRtg': 119.1, 'W': 39, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.2, 'eFG%': 57.4, 'TS%': 60.5, 'PACE': 101.04, 'POSS': 6201, 'TEAM': 'DEN', 'PIE': 53.3}

   OREB  DREB
0     1     1

Jake LaRavia, MAE: 5.853903220750825e-16, RMSE: 8.932106323199654e-16
{'RANK': 5, 'OffRtg': 119.1, 'W': 39, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.2, 'eFG%': 57.4, 'TS%': 60.5, 'PACE': 101.04, 'POSS': 6201, 'TEAM': 'DEN', 'PIE': 53.3}

   OREB  DREB
0     1     2

Shai Gilgeous-Alexander, MAE: 0.0, RMSE: 0.0
{'RANK': 7, 'OffRtg': 118.0, 'W': 38, 'L': 23, 'DefRtg': 112.1, 'NetRtg': 5.9, 'AST%': 64.5, 'AST/TO': 1.77, 'ASTRatio': 19.3, 'OREB%': 34.5, 'DREB%': 69.5, 'REB%': 52.3, 'TOV%': 15.7, 'eFG%': 55.8, 'TS%': 59.2, 'PACE': 104.27, 'POSS': 6375, 'TEAM': 'MEM', 'PIE': 53.2}

   OREB  DREB
0     1     3

Desmond Bane, MAE: 1.4802973661668753e-16, RMSE: 3.1401849173675503e-16
{'RANK': 2, 'OffRtg': 118.5, 'W': 50, 'L': 11, 'DefRtg': 106.0, 'NetRtg': 12.5, 'AST%': 60.4, 'AST/TO': 2.26, 'ASTRatio': 18.9, 'OREB%': 28.5, 'DREB%': 69.4, 'REB%': 49.2, 'TOV%': 11.8, 'eFG%': 55.5, 'TS%': 58.8, 'PACE': 100.76, 'POSS': 6158, 'TEAM': 'OKC', 'PIE': 56.2}

   OREB  DREB
0     1     4

Jalen Williams, MAE: 5.592234494408196e-16, RMSE: 7.047625128960819e-16
{'RANK': 7, 'OffRtg': 118.0, 'W': 38, 'L': 23, 'DefRtg': 112.1, 'NetRtg': 5.9, 'AST%': 64.5, 'AST/TO': 1.77, 'ASTRatio': 19.3, 'OREB%': 34.5, 'DREB%': 69.5, 'REB%': 52.3, 'TOV%': 15.7, 'eFG%': 55.8, 'TS%': 59.2, 'PACE': 104.27, 'POSS': 6375, 'TEAM': 'MEM', 'PIE': 53.2}

   OREB  DREB
0     0     4

Ja Morant, MAE: 7.053181568206876e-16, RMSE: 7.691850745534255e-16
{'RANK': 2, 'OffRtg': 118.5, 'W': 50, 'L': 11, 'DefRtg': 106.0, 'NetRtg': 12.5, 'AST%': 60.4, 'AST/TO': 2.26, 'ASTRatio': 18.9, 'OREB%': 28.5, 'DREB%': 69.4, 'REB%': 49.2, 'TOV%': 11.8, 'eFG%': 55.5, 'TS%': 58.8, 'PACE': 100.76, 'POSS': 6158, 'TEAM': 'OKC', 'PIE': 56.2}

   OREB  DREB
0     0     3

Santi Aldama, MAE: 1.0467817089322905e-15, RMSE: 1.408506749937081e-15
{'RANK': 2, 'OffRtg': 118.5, 'W': 50, 'L': 11, 'DefRtg': 106.0, 'NetRtg': 12.5, 'AST%': 60.4, 'AST/TO': 2.26, 'ASTRatio': 18.9, 'OREB%': 28.5, 'DREB%': 69.4, 'REB%': 49.2, 'TOV%': 11.8, 'eFG%': 55.5, 'TS%': 58.8, 'PACE': 100.76, 'POSS': 6158, 'TEAM': 'OKC', 'PIE': 56.2}

   OREB  DREB
0     1     4

Aaron Wiggins, MAE: 1.791159813061919e-15, RMSE: 2.5932680572993465e-15
{'RANK': 7, 'OffRtg': 118.0, 'W': 38, 'L': 23, 'DefRtg': 112.1, 'NetRtg': 5.9, 'AST%': 64.5, 'AST/TO': 1.77, 'ASTRatio': 19.3, 'OREB%': 34.5, 'DREB%': 69.5, 'REB%': 52.3, 'TOV%': 15.7, 'eFG%': 55.8, 'TS%': 59.2, 'PACE': 104.27, 'POSS': 6375, 'TEAM': 'MEM', 'PIE': 53.2}

   OREB  DREB
0     1     3

Isaiah Hartenstein, MAE: 4.796163466380677e-16, RMSE: 8.747542958250514e-16
{'RANK': 7, 'OffRtg': 118.0, 'W': 38, 'L': 23, 'DefRtg': 112.1, 'NetRtg': 5.9, 'AST%': 64.5, 'AST/TO': 1.77, 'ASTRatio': 19.3, 'OREB%': 34.5, 'DREB%': 69.5, 'REB%': 52.3, 'TOV%': 15.7, 'eFG%': 55.8, 'TS%': 59.2, 'PACE': 104.27, 'POSS': 6375, 'TEAM': 'MEM', 'PIE': 53.2}

   OREB  DREB
0     3     6

Brandon Clarke, MAE: 1.1546319456101628e-15, RMSE: 1.5713480306226774e-15
{'RANK': 2, 'OffRtg': 118.5, 'W': 50, 'L': 11, 'DefRtg': 106.0, 'NetRtg': 12.5, 'AST%': 60.4, 'AST/TO': 2.26, 'ASTRatio': 18.9, 'OREB%': 28.5, 'DREB%': 69.4, 'REB%': 49.2, 'TOV%': 11.8, 'eFG%': 55.5, 'TS%': 58.8, 'PACE': 100.76, 'POSS': 6158, 'TEAM': 'OKC', 'PIE': 56.2}

   OREB  DREB
0     2     2

Luguentz Dort, MAE: 4.1119371282413205e-16, RMSE: 5.438959822042073e-16
{'RANK': 7, 'OffRtg': 118.0, 'W': 38, 'L': 23, 'DefRtg': 112.1, 'NetRtg': 5.9, 'AST%': 64.5, 'AST/TO': 1.77, 'ASTRatio': 19.3, 'OREB%': 34.5, 'DREB%': 69.5, 'REB%': 52.3, 'TOV%': 15.7, 'eFG%': 55.8, 'TS%': 59.2, 'PACE': 104.27, 'POSS': 6375, 'TEAM': 'MEM', 'PIE': 53.2}

   OREB  DREB
0     1     2

Isaiah Joe, MAE: 2.1316282072803005e-16, RMSE: 4.213000162292041e-16
{'RANK': 7, 'OffRtg': 118.0, 'W': 38, 'L': 23, 'DefRtg': 112.1, 'NetRtg': 5.9, 'AST%': 64.5, 'AST/TO': 1.77, 'ASTRatio': 19.3, 'OREB%': 34.5, 'DREB%': 69.5, 'REB%': 52.3, 'TOV%': 15.7, 'eFG%': 55.8, 'TS%': 59.2, 'PACE': 104.27, 'POSS': 6375, 'TEAM': 'MEM', 'PIE': 53.2}

   OREB  DREB
0     0     1

Kenrich Williams, MAE: 9.833403932394244e-16, RMSE: 1.2865454600503747e-15
{'RANK': 7, 'OffRtg': 118.0, 'W': 38, 'L': 23, 'DefRtg': 112.1, 'NetRtg': 5.9, 'AST%': 64.5, 'AST/TO': 1.77, 'ASTRatio': 19.3, 'OREB%': 34.5, 'DREB%': 69.5, 'REB%': 52.3, 'TOV%': 15.7, 'eFG%': 55.8, 'TS%': 59.2, 'PACE': 104.27, 'POSS': 6375, 'TEAM': 'MEM', 'PIE': 53.2}

   OREB  DREB
0     1     2

James Harden, MAE: 8.552829226741946e-16, RMSE: 1.1338214607267812e-15
{'RANK': 9, 'OffRtg': 113.7, 'W': 35, 'L': 27, 'DefRtg': 111.9, 'NetRtg': 1.9, 'AST%': 62.3, 'AST/TO': 1.71, 'ASTRatio': 18.6, 'OREB%': 30.8, 'DREB%': 72.4, 'REB%': 51.7, 'TOV%': 15.4, 'eFG%': 54.7, 'TS%': 57.9, 'PACE': 100.21, 'POSS': 6251, 'TEAM': 'DET', 'PIE': 50.8}

   OREB  DREB
0     0     4

Malik Beasley, MAE: 8.585724723767877e-16, RMSE: 1.1117023364400436e-15
{'RANK': 14, 'OffRtg': 111.6, 'W': 32, 'L': 29, 'DefRtg': 109.5, 'NetRtg': 2.1, 'AST%': 61.1, 'AST/TO': 1.59, 'ASTRatio': 18.1, 'OREB%': 28.7, 'DREB%': 73.1, 'REB%': 51.0, 'TOV%': 15.8, 'eFG%': 54.0, 'TS%': 57.6, 'PACE': 98.76, 'POSS': 6051, 'TEAM': 'LAC', 'PIE': 50.8}

   OREB  DREB
0     0     1

Ivica Zubac, MAE: 1.907938827503973e-15, RMSE: 2.2155062298961195e-15
{'RANK': 9, 'OffRtg': 113.7, 'W': 35, 'L': 27, 'DefRtg': 111.9, 'NetRtg': 1.9, 'AST%': 62.3, 'AST/TO': 1.71, 'ASTRatio': 18.6, 'OREB%': 30.8, 'DREB%': 72.4, 'REB%': 51.7, 'TOV%': 15.4, 'eFG%': 54.7, 'TS%': 57.9, 'PACE': 100.21, 'POSS': 6251, 'TEAM': 'DET', 'PIE': 50.8}

   OREB  DREB
0     3     8

Jalen Duren, MAE: 1.0066022089934752e-15, RMSE: 1.3567149463006938e-15
{'RANK': 14, 'OffRtg': 111.6, 'W': 32, 'L': 29, 'DefRtg': 109.5, 'NetRtg': 2.1, 'AST%': 61.1, 'AST/TO': 1.59, 'ASTRatio': 18.1, 'OREB%': 28.7, 'DREB%': 73.1, 'REB%': 51.0, 'TOV%': 15.8, 'eFG%': 54.0, 'TS%': 57.6, 'PACE': 98.76, 'POSS': 6051, 'TEAM': 'LAC', 'PIE': 50.8}

   OREB  DREB
0     3     7

Amir Coffey, MAE: 4.3615904538845433e-16, RMSE: 6.792221739132951e-16
{'RANK': 9, 'OffRtg': 113.7, 'W': 35, 'L': 27, 'DefRtg': 111.9, 'NetRtg': 1.9, 'AST%': 62.3, 'AST/TO': 1.71, 'ASTRatio': 18.6, 'OREB%': 30.8, 'DREB%': 72.4, 'REB%': 51.7, 'TOV%': 15.4, 'eFG%': 54.7, 'TS%': 57.9, 'PACE': 100.21, 'POSS': 6251, 'TEAM': 'DET', 'PIE': 50.8}

   OREB  DREB
0     0     1

Tim Hardaway Jr., MAE: 4.2111907830609386e-16, RMSE: 7.081939861855601e-16
{'RANK': 14, 'OffRtg': 111.6, 'W': 32, 'L': 29, 'DefRtg': 109.5, 'NetRtg': 2.1, 'AST%': 61.1, 'AST/TO': 1.59, 'ASTRatio': 18.1, 'OREB%': 28.7, 'DREB%': 73.1, 'REB%': 51.0, 'TOV%': 15.8, 'eFG%': 54.0, 'TS%': 57.6, 'PACE': 98.76, 'POSS': 6051, 'TEAM': 'LAC', 'PIE': 50.8}

   OREB  DREB
0     0     2

Kris Dunn, MAE: 0.0, RMSE: 0.0
{'RANK': 9, 'OffRtg': 113.7, 'W': 35, 'L': 27, 'DefRtg': 111.9, 'NetRtg': 1.9, 'AST%': 62.3, 'AST/TO': 1.71, 'ASTRatio': 18.6, 'OREB%': 30.8, 'DREB%': 72.4, 'REB%': 51.7, 'TOV%': 15.4, 'eFG%': 54.7, 'TS%': 57.9, 'PACE': 100.21, 'POSS': 6251, 'TEAM': 'DET', 'PIE': 50.8}

   OREB  DREB
0     1     2

Isaiah Stewart, MAE: 6.344131569286609e-16, RMSE: 7.412052841682383e-16
{'RANK': 14, 'OffRtg': 111.6, 'W': 32, 'L': 29, 'DefRtg': 109.5, 'NetRtg': 2.1, 'AST%': 61.1, 'AST/TO': 1.59, 'ASTRatio': 18.1, 'OREB%': 28.7, 'DREB%': 73.1, 'REB%': 51.0, 'TOV%': 15.8, 'eFG%': 54.0, 'TS%': 57.6, 'PACE': 98.76, 'POSS': 6051, 'TEAM': 'LAC', 'PIE': 50.8}

   OREB  DREB
0     1     3

c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.685e+01, tolerance: 2.854e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.326e+01, tolerance: 2.639e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.178e+01, tolerance: 2.803e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.026e+01, tolerance: 2.650e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.429e+01, tolerance: 3.011e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.261e+02, tolerance: 7.541e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.435e+02, tolerance: 7.679e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.690e+02, tolerance: 7.173e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.351e+02, tolerance: 8.310e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.318e+01, tolerance: 8.419e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.235e-01, tolerance: 8.310e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.114e-01, tolerance: 8.419e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.907e+01, tolerance: 6.129e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.310e+01, tolerance: 5.837e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.031e+01, tolerance: 5.569e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.221e+01, tolerance: 5.943e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.618e+01, tolerance: 5.423e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.755e-01, tolerance: 6.129e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.733e-01, tolerance: 5.569e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.493e-02, tolerance: 5.943e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.551e+00, tolerance: 2.323e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.558e+01, tolerance: 2.224e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.153e+00, tolerance: 2.259e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.131e+00, tolerance: 1.592e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.797e-01, tolerance: 2.360e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.411e+01, tolerance: 3.090e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.503e+01, tolerance: 3.209e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.506e+01, tolerance: 3.110e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.298e+01, tolerance: 2.561e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.074e+00, tolerance: 2.664e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.785e+00, tolerance: 1.576e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.685e+01, tolerance: 1.836e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.808e-01, tolerance: 1.700e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.906e+00, tolerance: 1.737e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.191e-02, tolerance: 1.675e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.834e+01, tolerance: 5.279e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.543e+01, tolerance: 5.502e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.727e+01, tolerance: 5.856e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.495e+01, tolerance: 5.023e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.310e+00, tolerance: 5.013e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.130e-01, tolerance: 5.279e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.139e-01, tolerance: 5.502e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.030e-01, tolerance: 5.856e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.772e-01, tolerance: 5.023e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.363e-01, tolerance: 5.013e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.834e+01, tolerance: 1.079e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.842e+01, tolerance: 1.262e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.458e+02, tolerance: 1.169e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.899e+01, tolerance: 1.112e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.789e+01, tolerance: 1.307e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.977e-01, tolerance: 1.079e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.432e-01, tolerance: 1.262e-01
  model = cd_fast.enet_coordinate_descent(

Jonas Valanciunas, MAE: 1.0385176505907272, RMSE: 1.2096168190911991
{'RANK': 5, 'OffRtg': 119.1, 'W': 39, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.2, 'eFG%': 57.4, 'TS%': 60.5, 'PACE': 101.04, 'POSS': 6201, 'TEAM': 'DEN', 'PIE': 53.3}

c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.198e+00, tolerance: 2.358e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.915e+00, tolerance: 1.991e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.455e-01, tolerance: 2.009e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.965e+00, tolerance: 2.091e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.088e+00, tolerance: 2.192e-02
  model = cd_fast.enet_coordinate_descent(

   MIN_x  PTS  3PA  3P%  FT%  STL  BLK  AST%    PACE   PIE  team_offrtg  Date_in_Seconds
0     18    9    0   10   79    0    0  68.1  101.04  53.3          115       1738821600

Jamal Murray, MAE: 1.5068958719267662, RMSE: 1.9056545030795993
{'RANK': 14, 'OffRtg': 115.9, 'W': 32, 'L': 28, 'DefRtg': 113.8, 'NetRtg': 2.1, 'AST%': 62.0, 'AST/TO': 2.0, 'ASTRatio': 19.0, 'OREB%': 29.4, 'DREB%': 72.8, 'REB%': 51.2, 'TOV%': 13.4, 'eFG%': 54.7, 'TS%': 58.2, 'PACE': 99.8, 'POSS': 6054, 'TEAM': 'SAC', 'PIE': 51.0}

   MIN_x  PTS  3PM  FTM  DREB  TOV  +/-  AST/TO  DREB%  TOV%  team_pace  team_poss  home_away
0     36   24    2    2     2    2    5     2.0   72.8  13.4        101       6201          0

DeMar DeRozan, MAE: 1.9227483861715313, RMSE: 2.254447071919704
{'RANK': 5, 'OffRtg': 119.1, 'W': 39, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.2, 'eFG%': 57.4, 'TS%': 60.5, 'PACE': 101.04, 'POSS': 6201, 'TEAM': 'DEN', 'PIE': 53.3}

   MIN_x  FG%  3PA  3P%  FTM  TOV  PF  +/-  AST%  DREB%  REB%  POSS
0     35   50    3   35    5    1   1    2  68.1   71.0  52.2  6201

Michael Porter Jr., MAE: 1.5105735837741696, RMSE: 1.882614492364463
{'RANK': 14, 'OffRtg': 115.9, 'W': 32, 'L': 28, 'DefRtg': 113.8, 'NetRtg': 2.1, 'AST%': 62.0, 'AST/TO': 2.0, 'ASTRatio': 19.0, 'OREB%': 29.4, 'DREB%': 72.8, 'REB%': 51.2, 'TOV%': 13.4, 'eFG%': 54.7, 'TS%': 58.2, 'PACE': 99.8, 'POSS': 6054, 'TEAM': 'SAC', 'PIE': 51.0}

   MIN_x  FGA  FG%  3PM  3PA  FTM  FTA  FT%  OREB  DREB  STL  BLK  TOV  PF  +/-  RANK  DefRtg  AST%  OREB%  TOV%   TS%  PACE  team_pace  Date_in_Seconds  home_away
0     31   13   48    2    6    1    2   65     2     4    0    0    1   1    4    14   113.8  62.0   29.4  13.4  58.2  99.8        101       1738614240          0

Christian Braun, MAE: 1.157196661932769, RMSE: 1.368525190700005
{'RANK': 14, 'OffRtg': 115.9, 'W': 32, 'L': 28, 'DefRtg': 113.8, 'NetRtg': 2.1, 'AST%': 62.0, 'AST/TO': 2.0, 'ASTRatio': 19.0, 'OREB%': 29.4, 'DREB%': 72.8, 'REB%': 51.2, 'TOV%': 13.4, 'eFG%': 54.7, 'TS%': 58.2, 'PACE': 99.8, 'POSS': 6054, 'TEAM': 'SAC', 'PIE': 51.0}

   MIN_x  FG%  3PM  3PA  FTA  OREB  TOV  PF  +/-  OffRtg  NetRtg  AST%  DREB%  REB%
0     33   57    1    3    3     1    0   2    8   115.9     2.1  62.0   72.8  51.2

Keegan Murray, MAE: 1.220747615066058, RMSE: 1.5171625032567349
{'RANK': 5, 'OffRtg': 119.1, 'W': 39, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.2, 'eFG%': 57.4, 'TS%': 60.5, 'PACE': 101.04, 'POSS': 6201, 'TEAM': 'DEN', 'PIE': 53.3}

   MIN_x  FGA  FG%  3PM  3PA  FTM  FTA  FT%  OREB  DREB  STL  BLK  TOV  PF  +/-  RANK  DefRtg  AST%  OREB%  TOV%   TS%    PACE  team_pace  Date_in_Seconds  home_away
0     32   10   47    2    5    0    1   33     1     4    1    0    0   1    0     5   113.9  68.1   31.2  14.2  60.5  101.04         99       1738856160          1

Aaron Gordon, MAE: 2.233587395873064, RMSE: 3.0354450362708274
{'RANK': 14, 'OffRtg': 115.9, 'W': 32, 'L': 28, 'DefRtg': 113.8, 'NetRtg': 2.1, 'AST%': 62.0, 'AST/TO': 2.0, 'ASTRatio': 19.0, 'OREB%': 29.4, 'DREB%': 72.8, 'REB%': 51.2, 'TOV%': 13.4, 'eFG%': 54.7, 'TS%': 58.2, 'PACE': 99.8, 'POSS': 6054, 'TEAM': 'SAC', 'PIE': 51.0}

   MIN_x  FGA  FG%  3PM  3PA  FTM  FTA  FT%  OREB  DREB  STL  BLK  TOV  PF  +/-  RANK  DefRtg  AST%  OREB%  TOV%   TS%  PACE  team_pace  Date_in_Seconds  home_away
0     24    8   51    1    2    1    2   64     1     2    0    0    1   1    5    14   113.8  62.0   29.4  13.4  58.2  99.8        101       1738255680          0

Russell Westbrook, MAE: 2.067814690105409, RMSE: 2.51206329046723
{'RANK': 14, 'OffRtg': 115.9, 'W': 32, 'L': 28, 'DefRtg': 113.8, 'NetRtg': 2.1, 'AST%': 62.0, 'AST/TO': 2.0, 'ASTRatio': 19.0, 'OREB%': 29.4, 'DREB%': 72.8, 'REB%': 51.2, 'TOV%': 13.4, 'eFG%': 54.7, 'TS%': 58.2, 'PACE': 99.8, 'POSS': 6054, 'TEAM': 'SAC', 'PIE': 51.0}

   MIN_x  FGA  3P%  FT%  DREB  TOV  PF  +/-  DefRtg  DREB%  REB%  TOV%   TS%  PACE  team_pace  Date_in_Seconds  home_away
0     28   11   28   60     3    3   2    2   113.8   72.8  51.2  13.4  58.2  99.8        101       1738173600          0

Keon Ellis, MAE: 0.8716693836236465, RMSE: 1.0910224923339809
{'RANK': 5, 'OffRtg': 119.1, 'W': 39, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.2, 'eFG%': 57.4, 'TS%': 60.5, 'PACE': 101.04, 'POSS': 6201, 'TEAM': 'DEN', 'PIE': 53.3}

   MIN_x  3P%  FTM  OREB  STL  PF  +/-  MIN_y  DREB%  REB%    PACE  team_pace
0     23   47    0     0    1   1   -2   2970   71.0  52.2  101.04         99

Trey Lyles, MAE: 0.7813814397996087, RMSE: 1.1190014992275596
{'RANK': 5, 'OffRtg': 119.1, 'W': 39, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.2, 'eFG%': 57.4, 'TS%': 60.5, 'PACE': 101.04, 'POSS': 6201, 'TEAM': 'DEN', 'PIE': 53.3}

   MIN_x  FG%  3P%  FTM  REB  TOV  TOV%
0     14   45   35    0    3    0  14.2

Markelle Fultz, MAE: 2.131421509164497, RMSE: 2.439461820017244
{'RANK': 5, 'OffRtg': 119.1, 'W': 39, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.2, 'eFG%': 57.4, 'TS%': 60.5, 'PACE': 101.04, 'POSS': 6201, 'TEAM': 'DEN', 'PIE': 53.3}

   MIN_x  FGA  FG%  3PM  FTM  FT%  OREB  DREB  STL  TOV  +/-  RANK  AST%  ASTRatio  DREB%    PACE  team_pace  Date_in_Seconds
0     16    6   48    0    0   25     1     1    0    1    0     5  68.1      21.1   71.0  101.04         99       1718958240

Jake LaRavia, MAE: 1.7656639290840268, RMSE: 2.02428232358951
{'RANK': 5, 'OffRtg': 119.1, 'W': 39, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.2, 'eFG%': 57.4, 'TS%': 60.5, 'PACE': 101.04, 'POSS': 6201, 'TEAM': 'DEN', 'PIE': 53.3}

   MIN_x  FGM  3PM  3PA  FTA  OREB  STL  PF  +/-   L  MIN_y  AST%    PACE  home_away
0     15    1    0    1    0     1    0   1    0  22   2966  68.1  101.04          1

Shai Gilgeous-Alexander, MAE: 1.9622788510805962, RMSE: 2.3980191057982574
{'RANK': 7, 'OffRtg': 118.0, 'W': 38, 'L': 23, 'DefRtg': 112.1, 'NetRtg': 5.9, 'AST%': 64.5, 'AST/TO': 1.77, 'ASTRatio': 19.3, 'OREB%': 34.5, 'DREB%': 69.5, 'REB%': 52.3, 'TOV%': 15.7, 'eFG%': 55.8, 'TS%': 59.2, 'PACE': 104.27, 'POSS': 6375, 'TEAM': 'MEM', 'PIE': 53.2}

   MIN_x  FGA  FG%  3P%  FTM  FT%  STL  BLK  +/-  AST%  ASTRatio  DREB%  REB%  TOV%    PACE  team_offrtg  home_away
0     33   22   51   42    9   89    1    0   11  64.5      19.3   69.5  52.3  15.7  104.27          118          1

Desmond Bane, MAE: 2.0527144980148244, RMSE: 2.7970611367677565
{'RANK': 2, 'OffRtg': 118.5, 'W': 50, 'L': 11, 'DefRtg': 106.0, 'NetRtg': 12.5, 'AST%': 60.4, 'AST/TO': 2.26, 'ASTRatio': 18.9, 'OREB%': 28.5, 'DREB%': 69.4, 'REB%': 49.2, 'TOV%': 11.8, 'eFG%': 55.5, 'TS%': 58.8, 'PACE': 100.76, 'POSS': 6158, 'TEAM': 'OKC', 'PIE': 56.2}

   MIN_x  FT%  OREB  TOV  +/-  OffRtg  DefRtg   TS%    PACE  Date_in_Seconds  home_away
0     34   76     1    2    2   118.5   106.0  58.8  100.76       1738605600          0

Jalen Williams, MAE: 1.5652502530765244, RMSE: 2.0504053195568996
{'RANK': 7, 'OffRtg': 118.0, 'W': 38, 'L': 23, 'DefRtg': 112.1, 'NetRtg': 5.9, 'AST%': 64.5, 'AST/TO': 1.77, 'ASTRatio': 19.3, 'OREB%': 34.5, 'DREB%': 69.5, 'REB%': 52.3, 'TOV%': 15.7, 'eFG%': 55.8, 'TS%': 59.2, 'PACE': 104.27, 'POSS': 6375, 'TEAM': 'MEM', 'PIE': 53.2}

   MIN_x  FGA  FG%  3PM  3PA  FTM  FTA  FT%  OREB  DREB  STL  BLK  TOV  PF  +/-  RANK  DefRtg  AST%  OREB%  TOV%   TS%    PACE  team_pace  Date_in_Seconds  home_away
0     33   17   48    2    5    3    5   68     0     4    1    0    2   2    5     7   112.1  64.5   34.5  15.7  59.2  104.27        100       1739007360          1

Ja Morant, MAE: 3.162081584315494, RMSE: 3.6612809078430817
{'RANK': 2, 'OffRtg': 118.5, 'W': 50, 'L': 11, 'DefRtg': 106.0, 'NetRtg': 12.5, 'AST%': 60.4, 'AST/TO': 2.26, 'ASTRatio': 18.9, 'OREB%': 28.5, 'DREB%': 69.4, 'REB%': 49.2, 'TOV%': 11.8, 'eFG%': 55.5, 'TS%': 58.8, 'PACE': 100.76, 'POSS': 6158, 'TEAM': 'OKC', 'PIE': 56.2}

   MIN_x  FGA  FG%  3PM  3PA  FTM  FTA  FT%  OREB  DREB  STL  BLK  TOV  PF  +/-  RANK  DefRtg  AST%  OREB%  TOV%   TS%    PACE  team_pace  Date_in_Seconds  home_away
0     30   16   44    1    5    5    5   80     0     3    1    0    4   2    4     2   106.0  60.4   28.5  11.8  58.8  100.76        104       1737970560          0

Santi Aldama, MAE: 1.785802539194239, RMSE: 2.240626603244679
{'RANK': 2, 'OffRtg': 118.5, 'W': 50, 'L': 11, 'DefRtg': 106.0, 'NetRtg': 12.5, 'AST%': 60.4, 'AST/TO': 2.26, 'ASTRatio': 18.9, 'OREB%': 28.5, 'DREB%': 69.4, 'REB%': 49.2, 'TOV%': 11.8, 'eFG%': 55.5, 'TS%': 58.8, 'PACE': 100.76, 'POSS': 6158, 'TEAM': 'OKC', 'PIE': 56.2}

   MIN_x  3PA  3P%  FTA  BLK  PF  +/-  REB%  eFG%  POSS  Date_in_Seconds
0     24    5   35    1    0   1    3  49.2  55.5  6158       1738687680

Aaron Wiggins, MAE: 0.9909210336878823, RMSE: 1.2822955440269026
{'RANK': 7, 'OffRtg': 118.0, 'W': 38, 'L': 23, 'DefRtg': 112.1, 'NetRtg': 5.9, 'AST%': 64.5, 'AST/TO': 1.77, 'ASTRatio': 19.3, 'OREB%': 34.5, 'DREB%': 69.5, 'REB%': 52.3, 'TOV%': 15.7, 'eFG%': 55.8, 'TS%': 59.2, 'PACE': 104.27, 'POSS': 6375, 'TEAM': 'MEM', 'PIE': 53.2}

   MIN_x  TOV  +/-  DefRtg  OREB%    PACE  team_offrtg
0     25    0    7   112.1   34.5  104.27          118

Isaiah Hartenstein, MAE: 1.4595713278007794, RMSE: 1.7955783002170191
{'RANK': 7, 'OffRtg': 118.0, 'W': 38, 'L': 23, 'DefRtg': 112.1, 'NetRtg': 5.9, 'AST%': 64.5, 'AST/TO': 1.77, 'ASTRatio': 19.3, 'OREB%': 34.5, 'DREB%': 69.5, 'REB%': 52.3, 'TOV%': 15.7, 'eFG%': 55.8, 'TS%': 59.2, 'PACE': 104.27, 'POSS': 6375, 'TEAM': 'MEM', 'PIE': 53.2}

   MIN_x  FTM  OREB  PF  +/-  ASTRatio  OREB%  TOV%  eFG%  Date_in_Seconds
0     26    1     3   2    7      19.3   34.5  15.7  55.8       1739050560

Brandon Clarke, MAE: 1.0806658356815002, RMSE: 1.334105447238465
{'RANK': 2, 'OffRtg': 118.5, 'W': 50, 'L': 11, 'DefRtg': 106.0, 'NetRtg': 12.5, 'AST%': 60.4, 'AST/TO': 2.26, 'ASTRatio': 18.9, 'OREB%': 28.5, 'DREB%': 69.4, 'REB%': 49.2, 'TOV%': 11.8, 'eFG%': 55.5, 'TS%': 58.8, 'PACE': 100.76, 'POSS': 6158, 'TEAM': 'OKC', 'PIE': 56.2}

   MIN_x  FGA  FG%  3PM  3PA  FTM  FTA  FT%  OREB  DREB  STL  BLK  TOV  PF  +/-  RANK  DefRtg  AST%  OREB%  TOV%   TS%    PACE  team_pace  Date_in_Seconds  home_away
0     19    6   61    0    0    1    1   45     2     2    0    0    0   2   -1     2   106.0  60.4   28.5  11.8  58.8  100.76        104       1738713600          0

Luguentz Dort, MAE: 1.049008794587563, RMSE: 1.3415494681416362
{'RANK': 7, 'OffRtg': 118.0, 'W': 38, 'L': 23, 'DefRtg': 112.1, 'NetRtg': 5.9, 'AST%': 64.5, 'AST/TO': 1.77, 'ASTRatio': 19.3, 'OREB%': 34.5, 'DREB%': 69.5, 'REB%': 52.3, 'TOV%': 15.7, 'eFG%': 55.8, 'TS%': 59.2, 'PACE': 104.27, 'POSS': 6375, 'TEAM': 'MEM', 'PIE': 53.2}

   MIN_x  FGA  FG%  3PM  3PA  FTM  FTA  FT%  OREB  DREB  STL  BLK  TOV  PF  +/-  RANK  DefRtg  AST%  OREB%  TOV%   TS%    PACE  team_pace  Date_in_Seconds  home_away
0     27    8   45    2    5    0    0   10     1     2    0    0    0   2    5     7   112.1  64.5   34.5  15.7  59.2  104.27        100       1738929600          1

Isaiah Joe, MAE: 0.8951881566902506, RMSE: 1.0443399660708474
{'RANK': 7, 'OffRtg': 118.0, 'W': 38, 'L': 23, 'DefRtg': 112.1, 'NetRtg': 5.9, 'AST%': 64.5, 'AST/TO': 1.77, 'ASTRatio': 19.3, 'OREB%': 34.5, 'DREB%': 69.5, 'REB%': 52.3, 'TOV%': 15.7, 'eFG%': 55.8, 'TS%': 59.2, 'PACE': 104.27, 'POSS': 6375, 'TEAM': 'MEM', 'PIE': 53.2}

   MIN_x  3PM  FT%  OREB  STL  DefRtg  AST%  OREB%  REB%  team_offrtg
0     21    3   25     0    0   112.1  64.5   34.5  52.3          118

Kenrich Williams, MAE: 1.0939258935434504, RMSE: 1.2810615292825243
{'RANK': 7, 'OffRtg': 118.0, 'W': 38, 'L': 23, 'DefRtg': 112.1, 'NetRtg': 5.9, 'AST%': 64.5, 'AST/TO': 1.77, 'ASTRatio': 19.3, 'OREB%': 34.5, 'DREB%': 69.5, 'REB%': 52.3, 'TOV%': 15.7, 'eFG%': 55.8, 'TS%': 59.2, 'PACE': 104.27, 'POSS': 6375, 'TEAM': 'MEM', 'PIE': 53.2}

   MIN_x  3PM  3PA  FTA  OREB  BLK  TOV  +/-   W  OffRtg    PACE
0     15    0    2    0     1    0    0    4  38   118.0  104.27

James Harden, MAE: 2.7214944713518956, RMSE: 3.356657609923955
{'RANK': 9, 'OffRtg': 113.7, 'W': 35, 'L': 27, 'DefRtg': 111.9, 'NetRtg': 1.9, 'AST%': 62.3, 'AST/TO': 1.71, 'ASTRatio': 18.6, 'OREB%': 30.8, 'DREB%': 72.4, 'REB%': 51.7, 'TOV%': 15.4, 'eFG%': 54.7, 'TS%': 57.9, 'PACE': 100.21, 'POSS': 6251, 'TEAM': 'DET', 'PIE': 50.8}

   MIN_x  FGA  FG%  3PM  3PA  FTM  FTA  FT%  OREB  DREB  STL  BLK  TOV  PF  +/-  RANK  DefRtg  AST%  OREB%  TOV%   TS%    PACE  team_pace  Date_in_Seconds  home_away
0     37   17   36    2    9    6    7   88     0     4    1    0    4   2    0     9   111.9  62.3   30.8  15.4  57.9  100.21         98       1739080800          0

Malik Beasley, MAE: 1.3172476227343703, RMSE: 1.6058142463185128
{'RANK': 14, 'OffRtg': 111.6, 'W': 32, 'L': 29, 'DefRtg': 109.5, 'NetRtg': 2.1, 'AST%': 61.1, 'AST/TO': 1.59, 'ASTRatio': 18.1, 'OREB%': 28.7, 'DREB%': 73.1, 'REB%': 51.0, 'TOV%': 15.8, 'eFG%': 54.0, 'TS%': 57.6, 'PACE': 98.76, 'POSS': 6051, 'TEAM': 'LAC', 'PIE': 50.8}

   MIN_x  FGA  FG%  3PM  3PA  FTM  FTA  FT%  OREB  DREB  STL  BLK  TOV  PF  +/-  RANK  DefRtg  AST%  OREB%  TOV%   TS%   PACE  team_pace  Date_in_Seconds  home_away
0     25   12   47    4    9    1    1   30     0     1    1    0    0   1    3    14   109.5  61.1   28.7  15.8  57.6  98.76        100       1739141280          1

Ivica Zubac, MAE: 0.9683155375134415, RMSE: 1.2511061286920877
{'RANK': 9, 'OffRtg': 113.7, 'W': 35, 'L': 27, 'DefRtg': 111.9, 'NetRtg': 1.9, 'AST%': 62.3, 'AST/TO': 1.71, 'ASTRatio': 18.6, 'OREB%': 30.8, 'DREB%': 72.4, 'REB%': 51.7, 'TOV%': 15.4, 'eFG%': 54.7, 'TS%': 57.9, 'PACE': 100.21, 'POSS': 6251, 'TEAM': 'DET', 'PIE': 50.8}

   MIN_x  FG%  OREB  REB  +/-  DefRtg  ASTRatio  eFG%   TS%    PACE  team_poss  Date_in_Seconds
0     32   61     3   12    6   111.9      18.6  54.7  57.9  100.21       6051       1739063520

Jalen Duren, MAE: 1.491577159940205, RMSE: 1.8279156617548695
{'RANK': 14, 'OffRtg': 111.6, 'W': 32, 'L': 29, 'DefRtg': 109.5, 'NetRtg': 2.1, 'AST%': 61.1, 'AST/TO': 1.59, 'ASTRatio': 18.1, 'OREB%': 28.7, 'DREB%': 73.1, 'REB%': 51.0, 'TOV%': 15.8, 'eFG%': 54.0, 'TS%': 57.6, 'PACE': 98.76, 'POSS': 6051, 'TEAM': 'LAC', 'PIE': 50.8}

   MIN_x  FTM  OREB  REB  BLK  +/-  AST/TO  team_pace  Date_in_Seconds  home_away
0     27    2     3   11    1    7    1.59        100       1739141280          1

Amir Coffey, MAE: 0.8332886921462064, RMSE: 0.9906001513821832
{'RANK': 9, 'OffRtg': 113.7, 'W': 35, 'L': 27, 'DefRtg': 111.9, 'NetRtg': 1.9, 'AST%': 62.3, 'AST/TO': 1.71, 'ASTRatio': 18.6, 'OREB%': 30.8, 'DREB%': 72.4, 'REB%': 51.7, 'TOV%': 15.4, 'eFG%': 54.7, 'TS%': 57.9, 'PACE': 100.21, 'POSS': 6251, 'TEAM': 'DET', 'PIE': 50.8}

   MIN_x  FG%  FT%  BLK  TOV  DREB%  Date_in_Seconds  home_away
0     26   44   70    0    0   72.4       1738985760          0

Tim Hardaway Jr., MAE: 1.24631646546935, RMSE: 1.4434217896492954
{'RANK': 14, 'OffRtg': 111.6, 'W': 32, 'L': 29, 'DefRtg': 109.5, 'NetRtg': 2.1, 'AST%': 61.1, 'AST/TO': 1.59, 'ASTRatio': 18.1, 'OREB%': 28.7, 'DREB%': 73.1, 'REB%': 51.0, 'TOV%': 15.8, 'eFG%': 54.0, 'TS%': 57.6, 'PACE': 98.76, 'POSS': 6051, 'TEAM': 'LAC', 'PIE': 50.8}

   MIN_x  FGA  FG%  3PM  3PA  FTM  FTA  FT%  OREB  DREB  STL  BLK  TOV  PF  +/-  RANK  DefRtg  AST%  OREB%  TOV%   TS%   PACE  team_pace  Date_in_Seconds  home_away
0     27    8   35    1    5    1    1   47     0     2    0    0    0   1    6    14   109.5  61.1   28.7  15.8  57.6  98.76        100       1739141280          1

Kris Dunn, MAE: 2.500974514994195, RMSE: 2.8570093687213016
{'RANK': 9, 'OffRtg': 113.7, 'W': 35, 'L': 27, 'DefRtg': 111.9, 'NetRtg': 1.9, 'AST%': 62.3, 'AST/TO': 1.71, 'ASTRatio': 18.6, 'OREB%': 30.8, 'DREB%': 72.4, 'REB%': 51.7, 'TOV%': 15.4, 'eFG%': 54.7, 'TS%': 57.9, 'PACE': 100.21, 'POSS': 6251, 'TEAM': 'DET', 'PIE': 50.8}

   MIN_x  FGA  3P%  FTM  OREB  REB  STL  BLK  TOV  PF  +/-  RANK  DefRtg  AST%  OREB%  DREB%  TOV%  team_offrtg  team_poss  Date_in_Seconds
0     23    5   30    0     1    3    2    0    0   2    1     9   111.9  62.3   30.8   72.4  15.4          111       6051       1738622880

Isaiah Stewart, MAE: 1.0371498249914257, RMSE: 1.285430019280622
{'RANK': 14, 'OffRtg': 111.6, 'W': 32, 'L': 29, 'DefRtg': 109.5, 'NetRtg': 2.1, 'AST%': 61.1, 'AST/TO': 1.59, 'ASTRatio': 18.1, 'OREB%': 28.7, 'DREB%': 73.1, 'REB%': 51.0, 'TOV%': 15.8, 'eFG%': 54.0, 'TS%': 57.6, 'PACE': 98.76, 'POSS': 6051, 'TEAM': 'LAC', 'PIE': 50.8}

   MIN_x  3P%  FT%  REB  STL  RANK   W  OffRtg  AST%  OREB%  REB%  TOV%
0     17   15   34    5    0    14  32   111.6  61.1   28.7  51.0  15.8

Jonas Valanciunas, MAE: 2.034915800439405, RMSE: 2.3643722536035137
{'RANK': 5, 'OffRtg': 119.1, 'W': 39, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.2, 'eFG%': 57.4, 'TS%': 60.5, 'PACE': 101.04, 'POSS': 6201, 'TEAM': 'DEN', 'PIE': 53.3}

   FGM  3PM  FTM
0    3    0    1

Jamal Murray, MAE: 1.8967996361152442, RMSE: 2.247722524541422
{'RANK': 14, 'OffRtg': 115.9, 'W': 32, 'L': 28, 'DefRtg': 113.8, 'NetRtg': 2.1, 'AST%': 62.0, 'AST/TO': 2.0, 'ASTRatio': 19.0, 'OREB%': 29.4, 'DREB%': 72.8, 'REB%': 51.2, 'TOV%': 13.4, 'eFG%': 54.7, 'TS%': 58.2, 'PACE': 99.8, 'POSS': 6054, 'TEAM': 'SAC', 'PIE': 51.0}

   FGM  3PM  3PA  3P%  FTM
0    9    2    6   36    2

DeMar DeRozan, MAE: 2.2148533073324477, RMSE: 2.9245371630253
{'RANK': 5, 'OffRtg': 119.1, 'W': 39, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.2, 'eFG%': 57.4, 'TS%': 60.5, 'PACE': 101.04, 'POSS': 6201, 'TEAM': 'DEN', 'PIE': 53.3}

   FGM  3PM  FTM  FTA
0    8    1    5    5

Michael Porter Jr., MAE: 2.2022241808093734, RMSE: 2.8595739311837938
{'RANK': 14, 'OffRtg': 115.9, 'W': 32, 'L': 28, 'DefRtg': 113.8, 'NetRtg': 2.1, 'AST%': 62.0, 'AST/TO': 2.0, 'ASTRatio': 19.0, 'OREB%': 29.4, 'DREB%': 72.8, 'REB%': 51.2, 'TOV%': 13.4, 'eFG%': 54.7, 'TS%': 58.2, 'PACE': 99.8, 'POSS': 6054, 'TEAM': 'SAC', 'PIE': 51.0}

   FGM  3PM  FTM
0    6    2    1

Christian Braun, MAE: 1.8172436167588666, RMSE: 2.3885432652965033
{'RANK': 14, 'OffRtg': 115.9, 'W': 32, 'L': 28, 'DefRtg': 113.8, 'NetRtg': 2.1, 'AST%': 62.0, 'AST/TO': 2.0, 'ASTRatio': 19.0, 'OREB%': 29.4, 'DREB%': 72.8, 'REB%': 51.2, 'TOV%': 13.4, 'eFG%': 54.7, 'TS%': 58.2, 'PACE': 99.8, 'POSS': 6054, 'TEAM': 'SAC', 'PIE': 51.0}

   FGM  3PM  FTM
0    7    1    3

Keegan Murray, MAE: 1.1204032414404435, RMSE: 1.482855953234631
{'RANK': 5, 'OffRtg': 119.1, 'W': 39, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.2, 'eFG%': 57.4, 'TS%': 60.5, 'PACE': 101.04, 'POSS': 6201, 'TEAM': 'DEN', 'PIE': 53.3}

   FGM  3PM  FTM  FTA
0    5    2    0    1

Aaron Gordon, MAE: 2.4616881657640466, RMSE: 2.841805997983567
{'RANK': 14, 'OffRtg': 115.9, 'W': 32, 'L': 28, 'DefRtg': 113.8, 'NetRtg': 2.1, 'AST%': 62.0, 'AST/TO': 2.0, 'ASTRatio': 19.0, 'OREB%': 29.4, 'DREB%': 72.8, 'REB%': 51.2, 'TOV%': 13.4, 'eFG%': 54.7, 'TS%': 58.2, 'PACE': 99.8, 'POSS': 6054, 'TEAM': 'SAC', 'PIE': 51.0}

   FGM  3PM  FTM
0    4    1    1

Russell Westbrook, MAE: 2.325987734286917, RMSE: 2.7231662735077937
{'RANK': 14, 'OffRtg': 115.9, 'W': 32, 'L': 28, 'DefRtg': 113.8, 'NetRtg': 2.1, 'AST%': 62.0, 'AST/TO': 2.0, 'ASTRatio': 19.0, 'OREB%': 29.4, 'DREB%': 72.8, 'REB%': 51.2, 'TOV%': 13.4, 'eFG%': 54.7, 'TS%': 58.2, 'PACE': 99.8, 'POSS': 6054, 'TEAM': 'SAC', 'PIE': 51.0}

   FGM  3PM  FTM  FTA
0    5    1    1    2

Keon Ellis, MAE: 2.080583367231583, RMSE: 2.7348187988158177
{'RANK': 5, 'OffRtg': 119.1, 'W': 39, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.2, 'eFG%': 57.4, 'TS%': 60.5, 'PACE': 101.04, 'POSS': 6201, 'TEAM': 'DEN', 'PIE': 53.3}

   FGM  3PM  FTM  FTA
0    3    2    0    0

Trey Lyles, MAE: 1.9179758553438047, RMSE: 2.2115439921275546
{'RANK': 5, 'OffRtg': 119.1, 'W': 39, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.2, 'eFG%': 57.4, 'TS%': 60.5, 'PACE': 101.04, 'POSS': 6201, 'TEAM': 'DEN', 'PIE': 53.3}

   FGM  3PM  FTM  FTA
0    1    0    0    0

Markelle Fultz, MAE: 0.7723940914457239, RMSE: 0.843603312748769
{'RANK': 5, 'OffRtg': 119.1, 'W': 39, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.2, 'eFG%': 57.4, 'TS%': 60.5, 'PACE': 101.04, 'POSS': 6201, 'TEAM': 'DEN', 'PIE': 53.3}

   MIN_x  FGM  3PM  FTM
0     16    3    0    0

Jake LaRavia, MAE: 1.6325255755450068, RMSE: 1.928569579937284
{'RANK': 5, 'OffRtg': 119.1, 'W': 39, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.2, 'eFG%': 57.4, 'TS%': 60.5, 'PACE': 101.04, 'POSS': 6201, 'TEAM': 'DEN', 'PIE': 53.3}

   MIN_x  FGM  3PM  FTM  FTA  FT%
0     15    1    0    0    0   15

Shai Gilgeous-Alexander, MAE: 3.981489467621251e-15, RMSE: 4.9698598535040885e-15
{'RANK': 7, 'OffRtg': 118.0, 'W': 38, 'L': 23, 'DefRtg': 112.1, 'NetRtg': 5.9, 'AST%': 64.5, 'AST/TO': 1.77, 'ASTRatio': 19.3, 'OREB%': 34.5, 'DREB%': 69.5, 'REB%': 52.3, 'TOV%': 15.7, 'eFG%': 55.8, 'TS%': 59.2, 'PACE': 104.27, 'POSS': 6375, 'TEAM': 'MEM', 'PIE': 53.2}

   FGM  FGA  FG%  3PM  FTM  FTA
0   11   22   51    2    9   10

Desmond Bane, MAE: 1.9776357872330135, RMSE: 2.4851395269530476
{'RANK': 2, 'OffRtg': 118.5, 'W': 50, 'L': 11, 'DefRtg': 106.0, 'NetRtg': 12.5, 'AST%': 60.4, 'AST/TO': 2.26, 'ASTRatio': 18.9, 'OREB%': 28.5, 'DREB%': 69.4, 'REB%': 49.2, 'TOV%': 11.8, 'eFG%': 55.5, 'TS%': 58.8, 'PACE': 100.76, 'POSS': 6158, 'TEAM': 'OKC', 'PIE': 56.2}

   FGM  3PM  FTM  FTA
0    7    2    3    3

Jalen Williams, MAE: 2.027789873633095, RMSE: 2.88499238667523
{'RANK': 7, 'OffRtg': 118.0, 'W': 38, 'L': 23, 'DefRtg': 112.1, 'NetRtg': 5.9, 'AST%': 64.5, 'AST/TO': 1.77, 'ASTRatio': 19.3, 'OREB%': 34.5, 'DREB%': 69.5, 'REB%': 52.3, 'TOV%': 15.7, 'eFG%': 55.8, 'TS%': 59.2, 'PACE': 104.27, 'POSS': 6375, 'TEAM': 'MEM', 'PIE': 53.2}

   FGM  3PM  FTM
0    8    2    3

Ja Morant, MAE: 3.0874935365585694, RMSE: 3.671270401664074
{'RANK': 2, 'OffRtg': 118.5, 'W': 50, 'L': 11, 'DefRtg': 106.0, 'NetRtg': 12.5, 'AST%': 60.4, 'AST/TO': 2.26, 'ASTRatio': 18.9, 'OREB%': 28.5, 'DREB%': 69.4, 'REB%': 49.2, 'TOV%': 11.8, 'eFG%': 55.5, 'TS%': 58.8, 'PACE': 100.76, 'POSS': 6158, 'TEAM': 'OKC', 'PIE': 56.2}

   FGM  3PM  FTM
0    7    1    5

Santi Aldama, MAE: 1.9483412545054062, RMSE: 2.4867112867272034
{'RANK': 2, 'OffRtg': 118.5, 'W': 50, 'L': 11, 'DefRtg': 106.0, 'NetRtg': 12.5, 'AST%': 60.4, 'AST/TO': 2.26, 'ASTRatio': 18.9, 'OREB%': 28.5, 'DREB%': 69.4, 'REB%': 49.2, 'TOV%': 11.8, 'eFG%': 55.5, 'TS%': 58.8, 'PACE': 100.76, 'POSS': 6158, 'TEAM': 'OKC', 'PIE': 56.2}

   FGM  3PM  FTM
0    4    2    0

Aaron Wiggins, MAE: 1.7881169943577053, RMSE: 2.2846783978646044
{'RANK': 7, 'OffRtg': 118.0, 'W': 38, 'L': 23, 'DefRtg': 112.1, 'NetRtg': 5.9, 'AST%': 64.5, 'AST/TO': 1.77, 'ASTRatio': 19.3, 'OREB%': 34.5, 'DREB%': 69.5, 'REB%': 52.3, 'TOV%': 15.7, 'eFG%': 55.8, 'TS%': 59.2, 'PACE': 104.27, 'POSS': 6375, 'TEAM': 'MEM', 'PIE': 53.2}

   MIN_x  FGM  3PM  FTM  FTA
0     25    5    2    1    1

Isaiah Hartenstein, MAE: 1.6329853384242077, RMSE: 2.080726549546116
{'RANK': 7, 'OffRtg': 118.0, 'W': 38, 'L': 23, 'DefRtg': 112.1, 'NetRtg': 5.9, 'AST%': 64.5, 'AST/TO': 1.77, 'ASTRatio': 19.3, 'OREB%': 34.5, 'DREB%': 69.5, 'REB%': 52.3, 'TOV%': 15.7, 'eFG%': 55.8, 'TS%': 59.2, 'PACE': 104.27, 'POSS': 6375, 'TEAM': 'MEM', 'PIE': 53.2}

   FGM  3PM  FTM
0    4    0    1

Brandon Clarke, MAE: 1.1083387409779129, RMSE: 1.2621818341085858
{'RANK': 2, 'OffRtg': 118.5, 'W': 50, 'L': 11, 'DefRtg': 106.0, 'NetRtg': 12.5, 'AST%': 60.4, 'AST/TO': 2.26, 'ASTRatio': 18.9, 'OREB%': 28.5, 'DREB%': 69.4, 'REB%': 49.2, 'TOV%': 11.8, 'eFG%': 55.5, 'TS%': 58.8, 'PACE': 100.76, 'POSS': 6158, 'TEAM': 'OKC', 'PIE': 56.2}

   FGM  3PM  3P%  FTM
0    4    0    0    1

Luguentz Dort, MAE: 2.0801082177340713, RMSE: 2.5582364190803015
{'RANK': 7, 'OffRtg': 118.0, 'W': 38, 'L': 23, 'DefRtg': 112.1, 'NetRtg': 5.9, 'AST%': 64.5, 'AST/TO': 1.77, 'ASTRatio': 19.3, 'OREB%': 34.5, 'DREB%': 69.5, 'REB%': 52.3, 'TOV%': 15.7, 'eFG%': 55.8, 'TS%': 59.2, 'PACE': 104.27, 'POSS': 6375, 'TEAM': 'MEM', 'PIE': 53.2}

   FGM  3PM  FTM  FTA
0    3    2    0    0

Isaiah Joe, MAE: 1.34154351393902, RMSE: 1.7698290876288123
{'RANK': 7, 'OffRtg': 118.0, 'W': 38, 'L': 23, 'DefRtg': 112.1, 'NetRtg': 5.9, 'AST%': 64.5, 'AST/TO': 1.77, 'ASTRatio': 19.3, 'OREB%': 34.5, 'DREB%': 69.5, 'REB%': 52.3, 'TOV%': 15.7, 'eFG%': 55.8, 'TS%': 59.2, 'PACE': 104.27, 'POSS': 6375, 'TEAM': 'MEM', 'PIE': 53.2}

   FGM  3PM  FTM  FTA
0    4    3    0    0

Kenrich Williams, MAE: 1.6252419196682841, RMSE: 1.9348337649559564
{'RANK': 7, 'OffRtg': 118.0, 'W': 38, 'L': 23, 'DefRtg': 112.1, 'NetRtg': 5.9, 'AST%': 64.5, 'AST/TO': 1.77, 'ASTRatio': 19.3, 'OREB%': 34.5, 'DREB%': 69.5, 'REB%': 52.3, 'TOV%': 15.7, 'eFG%': 55.8, 'TS%': 59.2, 'PACE': 104.27, 'POSS': 6375, 'TEAM': 'MEM', 'PIE': 53.2}

   FGM  3PM  FTM
0    2    0    0

James Harden, MAE: 2.923541460609723, RMSE: 3.7375542982999006
{'RANK': 9, 'OffRtg': 113.7, 'W': 35, 'L': 27, 'DefRtg': 111.9, 'NetRtg': 1.9, 'AST%': 62.3, 'AST/TO': 1.71, 'ASTRatio': 18.6, 'OREB%': 30.8, 'DREB%': 72.4, 'REB%': 51.7, 'TOV%': 15.4, 'eFG%': 54.7, 'TS%': 57.9, 'PACE': 100.21, 'POSS': 6251, 'TEAM': 'DET', 'PIE': 50.8}

   FGM  3PM  FTM
0    6    2    6

Malik Beasley, MAE: 2.5044949686180615, RMSE: 3.0718405482352478
{'RANK': 14, 'OffRtg': 111.6, 'W': 32, 'L': 29, 'DefRtg': 109.5, 'NetRtg': 2.1, 'AST%': 61.1, 'AST/TO': 1.59, 'ASTRatio': 18.1, 'OREB%': 28.7, 'DREB%': 73.1, 'REB%': 51.0, 'TOV%': 15.8, 'eFG%': 54.0, 'TS%': 57.6, 'PACE': 98.76, 'POSS': 6051, 'TEAM': 'LAC', 'PIE': 50.8}

   FGM  3PM  FTM  FTA  FT%
0    6    4    1    1   30

Ivica Zubac, MAE: 1.6206987015825152, RMSE: 2.157279976724914
{'RANK': 9, 'OffRtg': 113.7, 'W': 35, 'L': 27, 'DefRtg': 111.9, 'NetRtg': 1.9, 'AST%': 62.3, 'AST/TO': 1.71, 'ASTRatio': 18.6, 'OREB%': 30.8, 'DREB%': 72.4, 'REB%': 51.7, 'TOV%': 15.4, 'eFG%': 54.7, 'TS%': 57.9, 'PACE': 100.21, 'POSS': 6251, 'TEAM': 'DET', 'PIE': 50.8}

   FGM  FTM  FTA
0    7    2    2

Jalen Duren, MAE: 1.5601248807839343, RMSE: 1.8219395054171754
{'RANK': 14, 'OffRtg': 111.6, 'W': 32, 'L': 29, 'DefRtg': 109.5, 'NetRtg': 2.1, 'AST%': 61.1, 'AST/TO': 1.59, 'ASTRatio': 18.1, 'OREB%': 28.7, 'DREB%': 73.1, 'REB%': 51.0, 'TOV%': 15.8, 'eFG%': 54.0, 'TS%': 57.6, 'PACE': 98.76, 'POSS': 6051, 'TEAM': 'LAC', 'PIE': 50.8}

   FGM  FTM  FTA  FT%
0    5    2    3   61

Amir Coffey, MAE: 1.8156046868253377, RMSE: 2.228592774915811
{'RANK': 9, 'OffRtg': 113.7, 'W': 35, 'L': 27, 'DefRtg': 111.9, 'NetRtg': 1.9, 'AST%': 62.3, 'AST/TO': 1.71, 'ASTRatio': 18.6, 'OREB%': 30.8, 'DREB%': 72.4, 'REB%': 51.7, 'TOV%': 15.4, 'eFG%': 54.7, 'TS%': 57.9, 'PACE': 100.21, 'POSS': 6251, 'TEAM': 'DET', 'PIE': 50.8}

   FGM  3PM  FTM
0    3    1    2

Tim Hardaway Jr., MAE: 1.2801090281697214, RMSE: 1.6183535619769995
{'RANK': 14, 'OffRtg': 111.6, 'W': 32, 'L': 29, 'DefRtg': 109.5, 'NetRtg': 2.1, 'AST%': 61.1, 'AST/TO': 1.59, 'ASTRatio': 18.1, 'OREB%': 28.7, 'DREB%': 73.1, 'REB%': 51.0, 'TOV%': 15.8, 'eFG%': 54.0, 'TS%': 57.6, 'PACE': 98.76, 'POSS': 6051, 'TEAM': 'LAC', 'PIE': 50.8}

   FGM  3PM  FTM  FTA
0    3    1    1    1

Kris Dunn, MAE: 1.5311142380668021, RMSE: 2.03058152006639
{'RANK': 9, 'OffRtg': 113.7, 'W': 35, 'L': 27, 'DefRtg': 111.9, 'NetRtg': 1.9, 'AST%': 62.3, 'AST/TO': 1.71, 'ASTRatio': 18.6, 'OREB%': 30.8, 'DREB%': 72.4, 'REB%': 51.7, 'TOV%': 15.4, 'eFG%': 54.7, 'TS%': 57.9, 'PACE': 100.21, 'POSS': 6251, 'TEAM': 'DET', 'PIE': 50.8}

   FGM  3PM  FTM
0    2    0    0

Isaiah Stewart, MAE: 1.7512869317506372, RMSE: 2.0498736384145104
{'RANK': 14, 'OffRtg': 111.6, 'W': 32, 'L': 29, 'DefRtg': 109.5, 'NetRtg': 2.1, 'AST%': 61.1, 'AST/TO': 1.59, 'ASTRatio': 18.1, 'OREB%': 28.7, 'DREB%': 73.1, 'REB%': 51.0, 'TOV%': 15.8, 'eFG%': 54.0, 'TS%': 57.6, 'PACE': 98.76, 'POSS': 6051, 'TEAM': 'LAC', 'PIE': 50.8}

   FGM  3PM  FTM
0    2    0    0

c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.185e+00, tolerance: 1.125e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.076e+00, tolerance: 1.990e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.200e+00, tolerance: 1.830e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.436e+00, tolerance: 2.069e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.531e+00, tolerance: 2.012e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.847e-01, tolerance: 9.264e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.610e-01, tolerance: 9.173e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.597e-01, tolerance: 9.297e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.463e-01, tolerance: 9.118e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.592e+00, tolerance: 3.359e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.564e-01, tolerance: 3.761e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.495e-01, tolerance: 3.654e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.458e+00, tolerance: 3.713e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.325e+00, tolerance: 3.315e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.687e+00, tolerance: 7.321e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.610e+00, tolerance: 6.830e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.698e+00, tolerance: 6.879e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.183e+00, tolerance: 7.297e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.450e-01, tolerance: 7.330e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.771e+00, tolerance: 3.032e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.275e+00, tolerance: 3.135e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.089e+00, tolerance: 3.112e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.694e+00, tolerance: 3.083e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.662e+00, tolerance: 2.213e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.209e-01, tolerance: 6.889e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.262e+00, tolerance: 6.093e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.550e-01, tolerance: 6.840e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.866e-01, tolerance: 6.248e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.428e+00, tolerance: 7.379e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.842e-01, tolerance: 2.554e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.051e+00, tolerance: 2.290e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.183e-01, tolerance: 2.552e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.005e-01, tolerance: 2.376e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.649e+00, tolerance: 2.338e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.569e+00, tolerance: 3.070e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.501e-02, tolerance: 3.402e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.785e-01, tolerance: 3.408e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.580e-02, tolerance: 3.280e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.096e-01, tolerance: 2.766e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.636e-01, tolerance: 6.621e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.451e-01, tolerance: 7.180e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.218e+00, tolerance: 5.142e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.856e-01, tolerance: 5.108e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.654e+00, tolerance: 4.873e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.125e+00, tolerance: 8.116e-03
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.340e+00, tolerance: 1.054e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.441e+00, tolerance: 1.078e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.202e+00, tolerance: 1.134e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.365e-02, tolerance: 1.112e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.592e-01, tolerance: 4.878e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.786e-01, tolerance: 5.165e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.506e-01, tolerance: 2.556e-02
  model = cd_fast.enet_coordinate_descent(

Jonas Valanciunas, MAE: 3.232840380634936e-14, RMSE: 3.29179491584211e-14
{'RANK': 5, 'OffRtg': 119.1, 'W': 39, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.2, 'eFG%': 57.4, 'TS%': 60.5, 'PACE': 101.04, 'POSS': 6201, 'TEAM': 'DEN', 'PIE': 53.3}

   FGA  FG%  3PM  3P%  FT%  AST  team_poss
0    7   52    0   10   79    1       6054

Jamal Murray, MAE: 1.9101607522798084e-12, RMSE: 1.911732437138796e-12
{'RANK': 14, 'OffRtg': 115.9, 'W': 32, 'L': 28, 'DefRtg': 113.8, 'NetRtg': 2.1, 'AST%': 62.0, 'AST/TO': 2.0, 'ASTRatio': 19.0, 'OREB%': 29.4, 'DREB%': 72.8, 'REB%': 51.2, 'TOV%': 13.4, 'eFG%': 54.7, 'TS%': 58.2, 'PACE': 99.8, 'POSS': 6054, 'TEAM': 'SAC', 'PIE': 51.0}

   FGA  FG%  3PM  3P%  OREB  AST  TOV  OffRtg  AST/TO  Date_in_Seconds
0   18   51    2   36     0    6    2   115.9     2.0       1738860480

DeMar DeRozan, MAE: 2.7133914370507606e-12, RMSE: 2.7156132497832155e-12
{'RANK': 5, 'OffRtg': 119.1, 'W': 39, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.2, 'eFG%': 57.4, 'TS%': 60.5, 'PACE': 101.04, 'POSS': 6201, 'TEAM': 'DEN', 'PIE': 53.3}

   FGA  FG%  3PM  3P%  OREB  ASTRatio  DREB%  team_pace  Date_in_Seconds
0   16   50    1   35     0      21.1   71.0         99       1738856160

Michael Porter Jr., MAE: 7.824725721649935e-15, RMSE: 1.0401019557581101e-14
{'RANK': 14, 'OffRtg': 115.9, 'W': 32, 'L': 28, 'DefRtg': 113.8, 'NetRtg': 2.1, 'AST%': 62.0, 'AST/TO': 2.0, 'ASTRatio': 19.0, 'OREB%': 29.4, 'DREB%': 72.8, 'REB%': 51.2, 'TOV%': 13.4, 'eFG%': 54.7, 'TS%': 58.2, 'PACE': 99.8, 'POSS': 6054, 'TEAM': 'SAC', 'PIE': 51.0}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTM  FTA  FT%  OREB  REB  BLK  PF  +/-  OffRtg  DefRtg  AST%  OREB%  DREB%  POSS  team_pace  home_away
0     31    6   13   48    2   39    1    2   65     2    7    0   1    4   115.9   113.8  62.0   29.4   72.8  6054        101          0

Christian Braun, MAE: 6.015868584113058e-15, RMSE: 6.862113788850805e-15
{'RANK': 14, 'OffRtg': 115.9, 'W': 32, 'L': 28, 'DefRtg': 113.8, 'NetRtg': 2.1, 'AST%': 62.0, 'AST/TO': 2.0, 'ASTRatio': 19.0, 'OREB%': 29.4, 'DREB%': 72.8, 'REB%': 51.2, 'TOV%': 13.4, 'eFG%': 54.7, 'TS%': 58.2, 'PACE': 99.8, 'POSS': 6054, 'TEAM': 'SAC', 'PIE': 51.0}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FT%  OREB  DREB  AST  BLK  +/-  RANK  GP  OffRtg  AST%  REB%  TOV%  home_away
0     33    7   12   57    1   27   80     1     4    2    0    8    14  61   115.9  62.0  51.2  13.4          0

Keegan Murray, MAE: 3.1280981209675257e-12, RMSE: 3.130397923796548e-12
{'RANK': 5, 'OffRtg': 119.1, 'W': 39, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.2, 'eFG%': 57.4, 'TS%': 60.5, 'PACE': 101.04, 'POSS': 6201, 'TEAM': 'DEN', 'PIE': 53.3}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FT%  OREB  REB  AST  STL  BLK  PF  +/-  OffRtg  DefRtg  DREB%  eFG%    PACE  team_pace  Date_in_Seconds  home_away
0     32    5   10   47    2   36   33     1    6    1    1    0   1    0   119.1   113.9   71.0  57.4  101.04         99       1738856160          1

Aaron Gordon, MAE: 8.055080706502522e-15, RMSE: 1.0071436402979476e-14
{'RANK': 14, 'OffRtg': 115.9, 'W': 32, 'L': 28, 'DefRtg': 113.8, 'NetRtg': 2.1, 'AST%': 62.0, 'AST/TO': 2.0, 'ASTRatio': 19.0, 'OREB%': 29.4, 'DREB%': 72.8, 'REB%': 51.2, 'TOV%': 13.4, 'eFG%': 54.7, 'TS%': 58.2, 'PACE': 99.8, 'POSS': 6054, 'TEAM': 'SAC', 'PIE': 51.0}

   FGA  FG%  3PM  3P%  FTM  FTA  FT%  OREB  PF   L  PACE
0    8   51    1   42    1    2   64     1   1  28  99.8

Russell Westbrook, MAE: 2.9123406627033326e-12, RMSE: 2.9151997986153023e-12
{'RANK': 14, 'OffRtg': 115.9, 'W': 32, 'L': 28, 'DefRtg': 113.8, 'NetRtg': 2.1, 'AST%': 62.0, 'AST/TO': 2.0, 'ASTRatio': 19.0, 'OREB%': 29.4, 'DREB%': 72.8, 'REB%': 51.2, 'TOV%': 13.4, 'eFG%': 54.7, 'TS%': 58.2, 'PACE': 99.8, 'POSS': 6054, 'TEAM': 'SAC', 'PIE': 51.0}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTA  FT%  OREB  REB  AST  STL  BLK  TOV  +/-  RANK  DefRtg  AST%  AST/TO  DREB%  PACE  team_pace  Date_in_Seconds  home_away
0     28    5   11   48    1   28    2   60     1    5    5    0    0    3    2    14   113.8  62.0     2.0   72.8  99.8        101       1738173600          0

Keon Ellis, MAE: 3.0795711032513736e-14, RMSE: 3.509289055900684e-14
{'RANK': 5, 'OffRtg': 119.1, 'W': 39, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.2, 'eFG%': 57.4, 'TS%': 60.5, 'PACE': 101.04, 'POSS': 6201, 'TEAM': 'DEN', 'PIE': 53.3}

   FGM  FGA  FG%  3PM  3P%  FTM  FTA  FT%  OREB  AST  BLK  TOV  PF  +/-  RANK  DefRtg  AST%  AST/TO  DREB%  TOV%  eFG%   TS%    PACE  POSS  home_away
0    3    6   55    2   47    0    0   27     0    1    0    0   1   -2     5   113.9  68.1    2.16   71.0  14.2  57.4  60.5  101.04  6201          1

Trey Lyles, MAE: 4.484087832432701e-15, RMSE: 5.76649838091041e-15
{'RANK': 5, 'OffRtg': 119.1, 'W': 39, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.2, 'eFG%': 57.4, 'TS%': 60.5, 'PACE': 101.04, 'POSS': 6201, 'TEAM': 'DEN', 'PIE': 53.3}

   MIN_x  FGM  FGA  3PM  3P%  FTM  FT%  OREB  DREB  AST  STL  BLK  TOV  PF  MIN_y  DefRtg  ASTRatio  OREB%  DREB%  TOV%  eFG%    PACE  team_offrtg  home_away
0     14    1    4    0   35    0   25     0     2    1    0    0    0   0   2967   113.9      21.1   31.2   71.0  14.2  57.4  101.04          115          1

Markelle Fultz, MAE: 8.268551480600104e-16, RMSE: 1.0121300753535982e-15
{'RANK': 5, 'OffRtg': 119.1, 'W': 39, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.2, 'eFG%': 57.4, 'TS%': 60.5, 'PACE': 101.04, 'POSS': 6201, 'TEAM': 'DEN', 'PIE': 53.3}

   FGA  3PM  AST%  team_pace  team_offrtg
0    6    0  68.1         99          116

Jake LaRavia, MAE: 9.806990706008022e-15, RMSE: 1.0158196659945495e-14
{'RANK': 5, 'OffRtg': 119.1, 'W': 39, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.2, 'eFG%': 57.4, 'TS%': 60.5, 'PACE': 101.04, 'POSS': 6201, 'TEAM': 'DEN', 'PIE': 53.3}

   MIN_x  FGM  FGA  3PM  3P%  FTM  FTA  OREB  REB  AST  STL  BLK  TOV  PF  +/-  RANK   W  AST%  OREB%  DREB%  TOV%   TS%  POSS  team_offrtg
0     15    1    3    0   26    0    0     1    3    1    0    0    0   1    0     5  39  68.1   31.2   71.0  14.2  60.5  6201          115

Shai Gilgeous-Alexander, MAE: 9.796761103502674e-15, RMSE: 1.1657888653629471e-14
{'RANK': 7, 'OffRtg': 118.0, 'W': 38, 'L': 23, 'DefRtg': 112.1, 'NetRtg': 5.9, 'AST%': 64.5, 'AST/TO': 1.77, 'ASTRatio': 19.3, 'OREB%': 34.5, 'DREB%': 69.5, 'REB%': 52.3, 'TOV%': 15.7, 'eFG%': 55.8, 'TS%': 59.2, 'PACE': 104.27, 'POSS': 6375, 'TEAM': 'MEM', 'PIE': 53.2}

   FGA  FG%  3PM  3P%  FTM  REB  TOV  +/-  AST%  POSS  team_pace  team_poss
0   22   51    2   42    9    4    2   11  64.5  6375        100       6158

Desmond Bane, MAE: 7.730259296468039e-15, RMSE: 9.518950875789393e-15
{'RANK': 2, 'OffRtg': 118.5, 'W': 50, 'L': 11, 'DefRtg': 106.0, 'NetRtg': 12.5, 'AST%': 60.4, 'AST/TO': 2.26, 'ASTRatio': 18.9, 'OREB%': 28.5, 'DREB%': 69.4, 'REB%': 49.2, 'TOV%': 11.8, 'eFG%': 55.5, 'TS%': 58.8, 'PACE': 100.76, 'POSS': 6158, 'TEAM': 'OKC', 'PIE': 56.2}

   FGM  FGA  FG%  3PM  3P%  FTM  FTA  FT%  OREB  AST  STL  BLK  TOV  PF  +/-  RANK   W  OffRtg  AST%  DREB%  REB%   TS%    PACE   PIE  team_pace  team_offrtg  home_away
0    7   15   51    2   40    3    3   76     1    6    1    0    2   2    2     2  50   118.5  60.4   69.4  49.2  58.8  100.76  56.2        104          118          0

Jalen Williams, MAE: 2.998537540038083e-15, RMSE: 4.021323192283258e-15
{'RANK': 7, 'OffRtg': 118.0, 'W': 38, 'L': 23, 'DefRtg': 112.1, 'NetRtg': 5.9, 'AST%': 64.5, 'AST/TO': 1.77, 'ASTRatio': 19.3, 'OREB%': 34.5, 'DREB%': 69.5, 'REB%': 52.3, 'TOV%': 15.7, 'eFG%': 55.8, 'TS%': 59.2, 'PACE': 104.27, 'POSS': 6375, 'TEAM': 'MEM', 'PIE': 53.2}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTM  OREB  REB  AST  BLK  TOV  PF  RANK  GP  DefRtg  NetRtg  AST%  DREB%  REB%  home_away
0     33    8   17   48    2   39    3     0    4    5    0    2   2     7  61   112.1     5.9  64.5   69.5  52.3          1

Ja Morant, MAE: 5.898430519127078e-13, RMSE: 5.901382941200382e-13
{'RANK': 2, 'OffRtg': 118.5, 'W': 50, 'L': 11, 'DefRtg': 106.0, 'NetRtg': 12.5, 'AST%': 60.4, 'AST/TO': 2.26, 'ASTRatio': 18.9, 'OREB%': 28.5, 'DREB%': 69.4, 'REB%': 49.2, 'TOV%': 11.8, 'eFG%': 55.5, 'TS%': 58.8, 'PACE': 100.76, 'POSS': 6158, 'TEAM': 'OKC', 'PIE': 56.2}

   MIN_x  FGA  FG%  3PM  3P%  FT%  OREB  STL  PF  OffRtg  AST%  DREB%  TOV%    PACE  Date_in_Seconds  home_away
0     30   16   44    1   27   80     0    1   2   118.5  60.4   69.4  11.8  100.76       1737970560          0

Santi Aldama, MAE: 1.5908093489220577e-09, RMSE: 2.0849238022315727e-09
{'RANK': 2, 'OffRtg': 118.5, 'W': 50, 'L': 11, 'DefRtg': 106.0, 'NetRtg': 12.5, 'AST%': 60.4, 'AST/TO': 2.26, 'ASTRatio': 18.9, 'OREB%': 28.5, 'DREB%': 69.4, 'REB%': 49.2, 'TOV%': 11.8, 'eFG%': 55.5, 'TS%': 58.8, 'PACE': 100.76, 'POSS': 6158, 'TEAM': 'OKC', 'PIE': 56.2}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTM  FTA  FT%  OREB  AST  STL  TOV  PF  +/-   W  DefRtg  AST/TO  OREB%  DREB%  TOV%  eFG%    PACE  team_offrtg  Date_in_Seconds  home_away
0     24    4   10   45    2   35    0    1   21     1    2    0    0   1    3  50   106.0    2.26   28.5   69.4  11.8  55.5  100.76          118       1738687680          0

Aaron Wiggins, MAE: 8.804481991078665e-14, RMSE: 8.97124080811616e-14
{'RANK': 7, 'OffRtg': 118.0, 'W': 38, 'L': 23, 'DefRtg': 112.1, 'NetRtg': 5.9, 'AST%': 64.5, 'AST/TO': 1.77, 'ASTRatio': 19.3, 'OREB%': 34.5, 'DREB%': 69.5, 'REB%': 52.3, 'TOV%': 15.7, 'eFG%': 55.8, 'TS%': 59.2, 'PACE': 104.27, 'POSS': 6375, 'TEAM': 'MEM', 'PIE': 53.2}

   FGA  FG%  3PM  3P%  FT%  MIN_y  DREB%  TOV%  POSS  home_away
0   11   50    2   37   35   2969   69.5  15.7  6375          1

Isaiah Hartenstein, MAE: 8.201905754066909e-16, RMSE: 8.234926847046236e-16
{'RANK': 7, 'OffRtg': 118.0, 'W': 38, 'L': 23, 'DefRtg': 112.1, 'NetRtg': 5.9, 'AST%': 64.5, 'AST/TO': 1.77, 'ASTRatio': 19.3, 'OREB%': 34.5, 'DREB%': 69.5, 'REB%': 52.3, 'TOV%': 15.7, 'eFG%': 55.8, 'TS%': 59.2, 'PACE': 104.27, 'POSS': 6375, 'TEAM': 'MEM', 'PIE': 53.2}

   FG%  3PM  GP
0   58    0  61

Brandon Clarke, MAE: 5.0995677129789304e-12, RMSE: 5.889961930034717e-12
{'RANK': 2, 'OffRtg': 118.5, 'W': 50, 'L': 11, 'DefRtg': 106.0, 'NetRtg': 12.5, 'AST%': 60.4, 'AST/TO': 2.26, 'ASTRatio': 18.9, 'OREB%': 28.5, 'DREB%': 69.4, 'REB%': 49.2, 'TOV%': 11.8, 'eFG%': 55.5, 'TS%': 58.8, 'PACE': 100.76, 'POSS': 6158, 'TEAM': 'OKC', 'PIE': 56.2}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTM  FTA  FT%  DREB  REB  AST  STL  BLK  TOV  PF  +/-  RANK  OffRtg  NetRtg  ASTRatio  DREB%  TOV%   TS%    PACE  team_pace  Date_in_Seconds  home_away
0     19    4    6   61    0    0    1    1   45     2    5    1    0    0    0   2   -1     2   118.5    12.5      18.9   69.4  11.8  58.8  100.76        104       1738713600          0

Luguentz Dort, MAE: 2.106183257713199e-15, RMSE: 2.4975915104010164e-15
{'RANK': 7, 'OffRtg': 118.0, 'W': 38, 'L': 23, 'DefRtg': 112.1, 'NetRtg': 5.9, 'AST%': 64.5, 'AST/TO': 1.77, 'ASTRatio': 19.3, 'OREB%': 34.5, 'DREB%': 69.5, 'REB%': 52.3, 'TOV%': 15.7, 'eFG%': 55.8, 'TS%': 59.2, 'PACE': 104.27, 'POSS': 6375, 'TEAM': 'MEM', 'PIE': 53.2}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTM  FTA  FT%  OREB  DREB  AST  STL  TOV  +/-  RANK   W  OffRtg  ASTRatio  DREB%  REB%  TOV%    PACE   PIE  team_offrtg  home_away
0     27    3    8   45    2   34    0    0   10     1     2    1    0    0    5     7  38   118.0      19.3   69.5  52.3  15.7  104.27  53.2          118          1

Isaiah Joe, MAE: 6.412740626134003e-15, RMSE: 8.159995712518275e-15
{'RANK': 7, 'OffRtg': 118.0, 'W': 38, 'L': 23, 'DefRtg': 112.1, 'NetRtg': 5.9, 'AST%': 64.5, 'AST/TO': 1.77, 'ASTRatio': 19.3, 'OREB%': 34.5, 'DREB%': 69.5, 'REB%': 52.3, 'TOV%': 15.7, 'eFG%': 55.8, 'TS%': 59.2, 'PACE': 104.27, 'POSS': 6375, 'TEAM': 'MEM', 'PIE': 53.2}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTM  FT%  OREB  AST  BLK  TOV  +/-  GP  DefRtg  AST%  DREB%  TOV%    PACE   PIE  team_offrtg  home_away
0     21    4    8   45    3   42    0   25     0    1    0    0    9  61   112.1  64.5   69.5  15.7  104.27  53.2          118          1

Kenrich Williams, MAE: 1.9759255035038495e-14, RMSE: 1.9918196335694853e-14
{'RANK': 7, 'OffRtg': 118.0, 'W': 38, 'L': 23, 'DefRtg': 112.1, 'NetRtg': 5.9, 'AST%': 64.5, 'AST/TO': 1.77, 'ASTRatio': 19.3, 'OREB%': 34.5, 'DREB%': 69.5, 'REB%': 52.3, 'TOV%': 15.7, 'eFG%': 55.8, 'TS%': 59.2, 'PACE': 104.27, 'POSS': 6375, 'TEAM': 'MEM', 'PIE': 53.2}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTA  FT%  OREB  DREB  AST  STL  BLK  TOV  PF  +/-  AST/TO  ASTRatio  OREB%  DREB%   TS%    PACE  team_pace  team_poss  home_away
0     15    2    4   45    0   30    0    7     1     2    1    0    0    0   1    4    1.77      19.3   34.5   69.5  59.2  104.27        100       6158          1

James Harden, MAE: 2.1543139658145645e-13, RMSE: 2.1563960457886335e-13
{'RANK': 9, 'OffRtg': 113.7, 'W': 35, 'L': 27, 'DefRtg': 111.9, 'NetRtg': 1.9, 'AST%': 62.3, 'AST/TO': 1.71, 'ASTRatio': 18.6, 'OREB%': 30.8, 'DREB%': 72.4, 'REB%': 51.7, 'TOV%': 15.4, 'eFG%': 54.7, 'TS%': 57.9, 'PACE': 100.21, 'POSS': 6251, 'TEAM': 'DET', 'PIE': 50.8}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTA  OREB  DREB  AST  STL  BLK  PF  +/-  RANK  OffRtg  DefRtg  ASTRatio  OREB%  TOV%    PACE  team_pace  Date_in_Seconds
0     37    6   17   36    2   30    7     0     4    9    1    0   2    0     9   113.7   111.9      18.6   30.8  15.4  100.21         98       1739080800

Malik Beasley, MAE: 6.521209574704086e-15, RMSE: 8.811180919884783e-15
{'RANK': 14, 'OffRtg': 111.6, 'W': 32, 'L': 29, 'DefRtg': 109.5, 'NetRtg': 2.1, 'AST%': 61.1, 'AST/TO': 1.59, 'ASTRatio': 18.1, 'OREB%': 28.7, 'DREB%': 73.1, 'REB%': 51.0, 'TOV%': 15.8, 'eFG%': 54.0, 'TS%': 57.6, 'PACE': 98.76, 'POSS': 6051, 'TEAM': 'LAC', 'PIE': 50.8}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FT%  DREB  REB  AST  STL  BLK  PF  +/-  RANK   W  DefRtg  AST%  AST/TO  OREB%  DREB%   TS%   PACE  home_away
0     25    6   12   47    4   47   30     1    2    1    1    0   1    3    14  32   109.5  61.1    1.59   28.7   73.1  57.6  98.76          1

Ivica Zubac, MAE: 0.0, RMSE: 0.0
{'RANK': 9, 'OffRtg': 113.7, 'W': 35, 'L': 27, 'DefRtg': 111.9, 'NetRtg': 1.9, 'AST%': 62.3, 'AST/TO': 1.71, 'ASTRatio': 18.6, 'OREB%': 30.8, 'DREB%': 72.4, 'REB%': 51.7, 'TOV%': 15.4, 'eFG%': 54.7, 'TS%': 57.9, 'PACE': 100.21, 'POSS': 6251, 'TEAM': 'DET', 'PIE': 50.8}

   MIN_x  FGA  FG%  FTA  FT%  OREB  REB  AST  STL  BLK  TOV  PF  +/-   W  DefRtg  AST%  DREB%  REB%  TOV%    PACE  team_pace  Date_in_Seconds  home_away
0     32   11   61    2   69     3   12    2    1    1    1   2    6  35   111.9  62.3   72.4  51.7  15.4  100.21         98       1739063520          0

Jalen Duren, MAE: 0.0, RMSE: 0.0
{'RANK': 14, 'OffRtg': 111.6, 'W': 32, 'L': 29, 'DefRtg': 109.5, 'NetRtg': 2.1, 'AST%': 61.1, 'AST/TO': 1.59, 'ASTRatio': 18.1, 'OREB%': 28.7, 'DREB%': 73.1, 'REB%': 51.0, 'TOV%': 15.8, 'eFG%': 54.0, 'TS%': 57.6, 'PACE': 98.76, 'POSS': 6051, 'TEAM': 'LAC', 'PIE': 50.8}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTM  FTA  FT%  DREB  REB  AST  STL  BLK  TOV  PF  +/-  RANK  OffRtg  NetRtg  ASTRatio  DREB%  TOV%   TS%   PACE  team_pace  Date_in_Seconds  home_away
0     27    5    8   72    0    0    2    3   61     7   11    3    1    1    1   2    7    14   111.6     2.1      18.1   73.1  15.8  57.6  98.76        100       1739141280          1

Amir Coffey, MAE: 1.6310032334003138e-12, RMSE: 1.632359889486527e-12
{'RANK': 9, 'OffRtg': 113.7, 'W': 35, 'L': 27, 'DefRtg': 111.9, 'NetRtg': 1.9, 'AST%': 62.3, 'AST/TO': 1.71, 'ASTRatio': 18.6, 'OREB%': 30.8, 'DREB%': 72.4, 'REB%': 51.7, 'TOV%': 15.4, 'eFG%': 54.7, 'TS%': 57.9, 'PACE': 100.21, 'POSS': 6251, 'TEAM': 'DET', 'PIE': 50.8}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTM  FT%  DREB  AST  STL  TOV  PF  +/-  RANK  DefRtg  AST%  DREB%  REB%  TOV%  eFG%    PACE  team_pace  Date_in_Seconds  home_away
0     26    3    7   44    1   28    2   70     1    1    0    0   2   -3     9   111.9  62.3   72.4  51.7  15.4  54.7  100.21         98       1738985760          0

Tim Hardaway Jr., MAE: 1.8286888987285574e-14, RMSE: 2.3368226358264357e-14
{'RANK': 14, 'OffRtg': 111.6, 'W': 32, 'L': 29, 'DefRtg': 109.5, 'NetRtg': 2.1, 'AST%': 61.1, 'AST/TO': 1.59, 'ASTRatio': 18.1, 'OREB%': 28.7, 'DREB%': 73.1, 'REB%': 51.0, 'TOV%': 15.8, 'eFG%': 54.0, 'TS%': 57.6, 'PACE': 98.76, 'POSS': 6051, 'TEAM': 'LAC', 'PIE': 50.8}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTM  FTA  OREB  DREB  AST  STL  BLK  TOV  PF  RANK  GP  OffRtg  AST%  AST/TO  DREB%  REB%  TOV%   TS%   PACE  POSS  team_pace
0     27    3    8   35    1   32    1    1     0     2    2    0    0    0   1    14  61   111.6  61.1    1.59   73.1  51.0  15.8  57.6  98.76  6051        100

Kris Dunn, MAE: 2.962063053091947e-11, RMSE: 3.489734733939739e-11
{'RANK': 9, 'OffRtg': 113.7, 'W': 35, 'L': 27, 'DefRtg': 111.9, 'NetRtg': 1.9, 'AST%': 62.3, 'AST/TO': 1.71, 'ASTRatio': 18.6, 'OREB%': 30.8, 'DREB%': 72.4, 'REB%': 51.7, 'TOV%': 15.4, 'eFG%': 54.7, 'TS%': 57.9, 'PACE': 100.21, 'POSS': 6251, 'TEAM': 'DET', 'PIE': 50.8}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTM  FTA  FT%  DREB  REB  AST  STL  BLK  TOV  PF  +/-  RANK  OffRtg  NetRtg  ASTRatio  DREB%  TOV%   TS%    PACE  team_pace  Date_in_Seconds  home_away
0     23    2    5   39    0   30    0    0    7     2    3    3    2    0    0   2    1     9   113.7     1.9      18.6   72.4  15.4  57.9  100.21         98       1738622880          0

Isaiah Stewart, MAE: 1.5810216319424857e-15, RMSE: 2.3190981048036585e-15
{'RANK': 14, 'OffRtg': 111.6, 'W': 32, 'L': 29, 'DefRtg': 109.5, 'NetRtg': 2.1, 'AST%': 61.1, 'AST/TO': 1.59, 'ASTRatio': 18.1, 'OREB%': 28.7, 'DREB%': 73.1, 'REB%': 51.0, 'TOV%': 15.8, 'eFG%': 54.0, 'TS%': 57.6, 'PACE': 98.76, 'POSS': 6051, 'TEAM': 'LAC', 'PIE': 50.8}

   MIN_x  FGM  FGA  3PM  3P%  FTA  FT%  OREB  REB  AST  STL  BLK  TOV  PF  +/-  RANK   L  DREB%  REB%  TOV%   PACE  team_pace  team_offrtg  home_away
0     17    2    3    0   15    1   34     1    5    1    0    1    1   2    1    14  29   73.1  51.0  15.8  98.76        100          113          1

                     Player  REB      RMSE_reb  AST  RMSE_ast  PTS      RMSE_3pm  3PM    RMSE_final  total_points
0         Jonas Valanciunas    6  6.792222e-16    2  1.209617    6  2.364372e+00    0  3.291795e-14            14
1              Jamal Murray    2  0.000000e+00    5  1.905655   18  2.247723e+00    1  1.911732e-12            26
2             DeMar DeRozan    3  9.555278e-17    4  2.254447   16  2.924537e+00    1  2.715613e-12            24
3        Michael Porter Jr.    6  1.538370e-15    2  1.882614   12  2.859574e+00    1  1.040102e-14            21
4           Christian Braun    4  1.081732e-15    2  1.368525   11  2.388543e+00    1  6.862114e-15            18
5             Keegan Murray    5  6.404746e-16    1  1.517163   11  1.482856e+00    1  3.130398e-12            18
6              Aaron Gordon    2  1.755786e-15    2  3.035445    7  2.841806e+00    0  1.007144e-14            11
7         Russell Westbrook    4  1.018589e-15    4  2.512063   10  2.723166e+00    1  2.915200e-12            19
8                Keon Ellis    2  1.317104e-15    1  1.091022    5  2.734819e+00    2  3.509289e-14            10
9                Trey Lyles    2  8.319553e-16    0  1.119001    3  2.211544e+00    0  5.766498e-15             5
10           Markelle Fultz    1  1.383108e-15    0  2.439462    6  8.436033e-01    0  1.012130e-15             7
11             Jake LaRavia    3  8.932106e-16    3  2.024282    3  1.928570e+00    0  1.015820e-14             9
12  Shai Gilgeous-Alexander    4  0.000000e+00    6  2.398019   21  4.969860e-15    1  1.165789e-14            32
13             Desmond Bane    5  3.140185e-16    5  2.797061   14  2.485140e+00    2  9.518951e-15            26
14           Jalen Williams    3  7.047625e-16    6  2.050405   14  2.884992e+00    1  4.021323e-15            24
15                Ja Morant    3  7.691851e-16    8  3.661281   16  3.671270e+00    1  5.901383e-13            28
16             Santi Aldama    5  1.408507e-15    2  2.240627    8  2.486711e+00    2  2.084924e-09            17
17            Aaron Wiggins    3  2.593268e-15    0  1.282296    9  2.284678e+00    1  8.971241e-14            13
18       Isaiah Hartenstein    9  8.747543e-16    6  1.795578    6  2.080727e+00    0  8.234927e-16            21
19           Brandon Clarke    4  1.571348e-15    1  1.334105    6  1.262182e+00    0  5.889962e-12            11
20            Luguentz Dort    3  5.438960e-16    1  1.341549    8  2.558236e+00    1  2.497592e-15            13
21               Isaiah Joe    1  4.213000e-16    0  1.044340    8  1.769829e+00    3  8.159996e-15            12
22         Kenrich Williams    3  1.286545e-15    1  1.281062    4  1.934834e+00    0  1.991820e-14             8
23             James Harden    4  1.133821e-15    6  3.356658   14  3.737554e+00    1  2.156396e-13            25
24            Malik Beasley    1  1.111702e-15    2  1.605814   12  3.071841e+00    3  8.811181e-15            18
25              Ivica Zubac   10  2.215506e-15    2  1.251106    9  2.157280e+00    0  0.000000e+00            21
26              Jalen Duren   10  1.356715e-15    1  1.827916    7  1.821940e+00    0  0.000000e+00            18
27              Amir Coffey    0  6.792222e-16    0  0.990600    6  2.228593e+00    0  1.632360e-12             6
28         Tim Hardaway Jr.    2  7.081940e-16    1  1.443422    9  1.618354e+00    0  2.336823e-14            12
29                Kris Dunn    3  0.000000e+00    0  2.857009    5  2.030582e+00    0  3.489735e-11             8
30           Isaiah Stewart    3  7.412053e-16    1  1.285430    5  2.049874e+00    0  2.319098e-15             9