In [15]:
from prediction import prediction

# players_teams = {
#     "Mark Williams": "CHA",
#     # "Miles Bridges": "CHA",
#     # "Jimmy Butler": "GSW",
#     "LaMelo Ball": "CHA",
#     "Stephen Curry": "GSW",
#     # "Brandin Podziemski": "GSW",
#     # "Nick Smith Jr.": "CHA",
#     "Josh Green": "CHA",
#     "Moses Moody": "GSW",
#     "Draymond Green": "GSW",
#     "Paul George": "PHI",
#     "Tyrese Maxey": "PHI",
#     "Kelly Oubre Jr.": "PHI",
#     "Andre Drummond": "PHI",
#     "Shaedon Sharpe": "POR",
#     "Quentin Grimes": "PHI",
#     "Deni Avdija": "POR",
#     "Anfernee Simons": "POR",
#     # "Toumani Camara": "POR",
#     # "Donovan Clingan": "POR",
#     "Bam Adebayo": "MIA",
#     "Tyler Herro": "MIA",
#     "Andrew Wiggins": "MIA",
#     # "Bilal Coulibaly": "WAS",
#     # "Alexandre Sarr": "WAS",
#     "Khris Middleton": "WAS",
#     # "Carlton Carrington": "WAS",
#     "Davion Mitchell": "MIA",
#     # "Kyshawn George": "WAS",
#     "Haywood Highsmith": "MIA"
# }



# players_teams = {
#     "Giannis Antetokounmpo": "MIL",
#     "Trae Young": "ATL",
#     "Damian Lillard": "MIL",
#     "Dyson Daniels": "ATL",
#     "Brook Lopez": "MIL",
#     "Taurean Prince": "MIL",
#     "Onyeka Okongwu": "ATL",
#     "Jalen Brunson": "NYK",
#     "Karl-Anthony Towns": "NYK",
#     "Mikal Bridges": "NYK",
#     "Moses Moody": "GSW",
#     "Stephen Curry": "GSW",
#     "Josh Hart": "NYK",
#     # "Brandin Podziemski": "GSW",
#     "OG Anunoby": "NYK",
#     "Draymond Green": "GSW",
#     "Paolo Banchero": "ORL",
#     "Franz Wagner": "ORL",
#     "Jakob Poeltl": "TOR",
#     "Immanuel Quickley": "TOR",
#     "Scottie Barnes": "TOR",
#     "RJ Barrett": "TOR",
#     "Wendell Carter Jr.": "ORL",
#     "Cole Anthony": "ORL",
#     "Kentavious Caldwell-Pope": "ORL",
#     # "Ja'Kobe Walter": "TOR",
#     "Donovan Mitchell": "CLE",
#     "Darius Garland": "CLE",
#     "Jarrett Allen": "CLE",
#     "Josh Giddey": "CHI",
#     "Coby White": "CHI",
#     # "Matas Buzelis": "CHI",
#     "Max Strus": "CLE",
#     "Dean Wade": "CLE",
#     "Zach Collins": "CHI",
#     # "Lonzo Ball": "CHI"
# }



# players_teams = {
#     "Jonas Valanciunas": "SAC",
#     "Jamal Murray": "DEN",
#     "DeMar DeRozan": "SAC",
#     "Michael Porter Jr.": "DEN",
#     "Christian Braun": "DEN",
#     "Keegan Murray": "SAC",
#     "Aaron Gordon": "DEN",
#     "Russell Westbrook": "DEN",
#     "Keon Ellis": "SAC",
#     "Trey Lyles": "SAC",
#     "Markelle Fultz": "SAC",
#     "Jake LaRavia": "SAC",
#     "Shai Gilgeous-Alexander": "OKC",
#     "Desmond Bane": "MEM",
#     "Jalen Williams": "OKC",
#     "Ja Morant": "MEM",
#     "Santi Aldama": "MEM",
#     # "Jaylen Wells": "MEM",
#     "Aaron Wiggins": "OKC",
#     "Isaiah Hartenstein": "OKC",
#     # "Cason Wallace": "OKC",
#     "Brandon Clarke": "MEM",
#     "Luguentz Dort": "OKC",
#     "Isaiah Joe": "OKC",
#     # "Zach Edey": "MEM",
#     "Kenrich Williams": "OKC",
#     "James Harden": "LAC",
#     "Malik Beasley": "DET",
#     "Ivica Zubac": "LAC",
#     # "Bogdan Bogdanovic": "LAC",
#     # "Ausar Thompson": "DET",
#     "Jalen Duren": "DET",
#     "Amir Coffey": "LAC",
#     "Tim Hardaway Jr.": "DET",
#     # "Dennis Schroder": "DET",
#     "Kris Dunn": "LAC",
#     # "Ron Holland II": "DET",
#     "Isaiah Stewart": "DET"
# }


# players_teams = {
#     "Franz Wagner": "ORL",
#     "Paolo Banchero": "ORL",
#     "Coby White": "CHI",
#     "Josh Giddey": "CHI",
#     "Zach Collins": "ORL",
#     # "Matas Buzelis": "CHI",
#     "Cole Anthony": "ORL",
#     "Wendell Carter Jr.": "ORL",
#     "Kevin Huerter": "CHI",
#     "Kentavious Caldwell-Pope": "ORL",
#     "Stephen Curry": "GSW",
#     # "Cameron Thomas": "BKN",
#     # "Cameron Johnson": "BKN",
#     # "Brandin Podziemski": "GSW",
#     # "D'Angelo Russell": "GSW",
#     "Moses Moody": "GSW",
#     "Buddy Hield": "GSW",
#     # "Nicolas Claxton": "BKN",
#     "Draymond Green": "GSW",
#     "Trendon Watford": "BKN",
#     "Ziaire Williams": "BKN",
#     "Keon Johnson": "BKN",
#     "Day'Ron Sharpe": "BKN",
#     # "Quinten Post": "GSW",
#     # "Tyrese Martin": "BKN",
#     # "Jalen Wilson": "BKN",
#     # "Gui Santos": "GSW",
#     "Kevon Looney": "GSW",
#     # "Zion Williamson": "NOP",
#     "Alperen Sengun": "HOU",
#     "Jalen Green": "HOU",
#     "CJ McCollum": "NOP",
#     "Trey Murphy III": "NOP",
#     "Dillon Brooks": "HOU",
#     # "Amen Thompson": "HOU",
#     "Jabari Smith Jr.": "HOU",
#     "Tari Eason": "HOU",
#     # "Jordan Hawkins": "NOP",
#     "Kelly Olynyk": "NOP",
#     "Bruce Brown": "NOP",
#     "Jose Alvarado": "NOP",
#     # "Karlo Matkovic": "NOP"
# }


players_teams = {
    "Kevin Durant": "PHX",
    "Devin Booker": "PHX",
    "Nikola Jokic": "DEN",
    "Jamal Murray": "DEN",
    "Michael Porter Jr.": "DEN",
    "Bradley Beal": "PHX",
    "Christian Braun": "DEN",
    "Russell Westbrook": "DEN",
    "Aaron Gordon": "DEN",
    "Bol Bol": "PHX",
    "Nick Richards": "PHX",
    "Grayson Allen": "PHX",
    "Royce O'Neale": "PHX",
    "Mason Plumlee": "PHX",
    "DeMar DeRozan": "SAC",
    # "Zach LaVine": "SAC",
    "Devin Vassell": "SAS",
    "De'Aaron Fox": "SAS",
    # "Stephon Castle": "SAS",
    "Keldon Johnson": "SAS",
    "Jonas Valanciunas": "SAS",
    "Keegan Murray": "SAC",
    "Keon Ellis": "SAC",
    "Harrison Barnes": "SAS",
    "Jeremy Sochan": "SAS",
    "Chris Paul": "SAS",
    "Jake LaRavia": "SAC",
    "Julian Champagnie": "SAS",
    "Trey Lyles": "SAC",
    "Bismack Biyombo": "SAS",
    "Markelle Fultz": "SAC",
    "James Harden": "LAC",
    "Karl-Anthony Towns": "NYK",
    "Kawhi Leonard": "LAC",
    "Mikal Bridges": "NYK",
    "Bogdan Bogdanovic": "LAC",
    "OG Anunoby": "NYK",
    "Ivica Zubac": "LAC",
    "Miles McBride": "NYK",
    "Josh Hart": "NYK",
    "Cameron Payne": "NYK",
    "Amir Coffey": "LAC",
    "Kris Dunn": "LAC",
    "Precious Achiuwa": "NYK",
    "Drew Eubanks": "NYK",
    "Nicolas Batum": "LAC"
}


import pandas as pd
date_list = ["2022-23","2023-24","2024-25"]
usage_path = "D:/nba_usage_csv_historic/usage_csv_{date}/{date}_content.csv"
schedule_base_path = "D:/nba_scheduled_csv/schedule_csv_2025/{schedule_team}_schedule_content.csv"
player_base_path = "D:/nba_player_csv_historic/season_{date}/all_quarters/{player}_content.csv"
defense_base_path = "D:/nba_defense_history_csv/defense_csv_{date}/all_quarter_defense_content.csv"

results_reb = prediction(players_teams, date_list, usage_path, player_base_path, defense_base_path, schedule_base_path,'REB','REB')
results_ast = prediction(players_teams, date_list, usage_path, player_base_path, defense_base_path, schedule_base_path,'AST','AST')
results_pts = prediction(players_teams, date_list, usage_path, player_base_path, defense_base_path, schedule_base_path,'PTS','FGA')
results_3pm = prediction(players_teams, date_list, usage_path, player_base_path, defense_base_path, schedule_base_path,'3PA','3PM')


df_combined = pd.concat([results_reb, results_ast, results_pts, results_3pm], axis=0, ignore_index=True)

df_merged = results_reb.merge(results_ast, on='Player', suffixes=('_reb', '_ast')) \
    .merge(results_pts, on='Player', suffixes=('_pts', '_extra')) \
    .merge(results_3pm, on='Player', suffixes=('_pts', '_3pm'))


df_merged['total_points'] = df_merged[['FGA', 'AST', 'REB','3PM']].sum(axis=1)
df_merged = df_merged.rename(columns={'FGA': 'PTS'})

display(df_merged)

Kevin Durant, MAE: 2.220446049250313e-16, RMSE: 3.1401849173675503e-16
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   OREB  DREB
0     0     5

Devin Booker, MAE: 8.881784197001252e-16, RMSE: 8.881784197001252e-16
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   OREB  DREB
0     0     3

Nikola Jokic, MAE: 4.440892098500626e-16, RMSE: 8.881784197001252e-16
{'RANK': 17, 'OffRtg': 114.3, 'W': 29, 'L': 33, 'DefRtg': 116.3, 'NetRtg': -2.1, 'AST%': 67.6, 'AST/TO': 1.97, 'ASTRatio': 19.9, 'OREB%': 25.7, 'DREB%': 70.6, 'REB%': 49.1, 'TOV%': 14.1, 'eFG%': 56.0, 'TS%': 59.6, 'PACE': 98.82, 'POSS': 6177, 'TEAM': 'PHX', 'PIE': 50.1}

   OREB  DREB
0     2    10

Jamal Murray, MAE: 6.661338147750939e-16, RMSE: 7.691850745534255e-16
{'RANK': 17, 'OffRtg': 114.3, 'W': 29, 'L': 33, 'DefRtg': 116.3, 'NetRtg': -2.1, 'AST%': 67.6, 'AST/TO': 1.97, 'ASTRatio': 19.9, 'OREB%': 25.7, 'DREB%': 70.6, 'REB%': 49.1, 'TOV%': 14.1, 'eFG%': 56.0, 'TS%': 59.6, 'PACE': 98.82, 'POSS': 6177, 'TEAM': 'PHX', 'PIE': 50.1}

   OREB  DREB
0     0     2

Michael Porter Jr., MAE: 3.552713678800501e-15, RMSE: 4.351167857633658e-15
{'RANK': 17, 'OffRtg': 114.3, 'W': 29, 'L': 33, 'DefRtg': 116.3, 'NetRtg': -2.1, 'AST%': 67.6, 'AST/TO': 1.97, 'ASTRatio': 19.9, 'OREB%': 25.7, 'DREB%': 70.6, 'REB%': 49.1, 'TOV%': 14.1, 'eFG%': 56.0, 'TS%': 59.6, 'PACE': 98.82, 'POSS': 6177, 'TEAM': 'PHX', 'PIE': 50.1}

   OREB  DREB
0     2     5

Bradley Beal, MAE: 6.661338147750939e-16, RMSE: 9.42055475210265e-16
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   OREB  DREB
0     0     2

Christian Braun, MAE: 4.440892098500626e-16, RMSE: 8.881784197001252e-16
{'RANK': 17, 'OffRtg': 114.3, 'W': 29, 'L': 33, 'DefRtg': 116.3, 'NetRtg': -2.1, 'AST%': 67.6, 'AST/TO': 1.97, 'ASTRatio': 19.9, 'OREB%': 25.7, 'DREB%': 70.6, 'REB%': 49.1, 'TOV%': 14.1, 'eFG%': 56.0, 'TS%': 59.6, 'PACE': 98.82, 'POSS': 6177, 'TEAM': 'PHX', 'PIE': 50.1}

   OREB  DREB
0     1     4

Russell Westbrook, MAE: 5.551115123125783e-16, RMSE: 8.005932084973442e-16
{'RANK': 17, 'OffRtg': 114.3, 'W': 29, 'L': 33, 'DefRtg': 116.3, 'NetRtg': -2.1, 'AST%': 67.6, 'AST/TO': 1.97, 'ASTRatio': 19.9, 'OREB%': 25.7, 'DREB%': 70.6, 'REB%': 49.1, 'TOV%': 14.1, 'eFG%': 56.0, 'TS%': 59.6, 'PACE': 98.82, 'POSS': 6177, 'TEAM': 'PHX', 'PIE': 50.1}

   OREB  DREB
0     1     3

Aaron Gordon, MAE: 0.0, RMSE: 0.0
{'RANK': 17, 'OffRtg': 114.3, 'W': 29, 'L': 33, 'DefRtg': 116.3, 'NetRtg': -2.1, 'AST%': 67.6, 'AST/TO': 1.97, 'ASTRatio': 19.9, 'OREB%': 25.7, 'DREB%': 70.6, 'REB%': 49.1, 'TOV%': 14.1, 'eFG%': 56.0, 'TS%': 59.6, 'PACE': 98.82, 'POSS': 6177, 'TEAM': 'PHX', 'PIE': 50.1}

   OREB  DREB
0     1     2

Bol Bol, MAE: 2.6645352591003757e-15, RMSE: 3.0927234722497852e-15
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   OREB  DREB
0     0     3

Nick Richards, MAE: 0.0, RMSE: 0.0
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   OREB  DREB
0     2     7

Grayson Allen, MAE: 4.440892098500626e-16, RMSE: 4.440892098500626e-16
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   OREB  DREB
0     0     2

Royce O'Neale, MAE: 1.3877787807814457e-16, RMSE: 2.2887833992611187e-16
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   OREB  DREB
0     0     3

Mason Plumlee, MAE: 8.881784197001252e-16, RMSE: 1.2560739669470201e-15
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   OREB  DREB
0     1     4

DeMar DeRozan, MAE: 5.551115123125783e-16, RMSE: 6.661338147750939e-16
{'RANK': 22, 'OffRtg': 112.6, 'W': 26, 'L': 34, 'DefRtg': 114.7, 'NetRtg': -2.1, 'AST%': 70.2, 'AST/TO': 2.07, 'ASTRatio': 20.4, 'OREB%': 28.0, 'DREB%': 69.3, 'REB%': 48.9, 'TOV%': 14.0, 'eFG%': 53.9, 'TS%': 57.1, 'PACE': 100.21, 'POSS': 6038, 'TEAM': 'SAS', 'PIE': 50.3}

   OREB  DREB
0     0     3

Devin Vassell, MAE: 1.1102230246251565e-16, RMSE: 2.220446049250313e-16
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   OREB  DREB
0     0     3

De'Aaron Fox, MAE: 2.220446049250313e-16, RMSE: 4.440892098500626e-16
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   OREB  DREB
0     0     3

Keldon Johnson, MAE: 0.0, RMSE: 0.0
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   OREB  DREB
0     1     2

Jonas Valanciunas, MAE: 8.881784197001252e-16, RMSE: 1.2560739669470201e-15
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   OREB  DREB
0     2     5

Keegan Murray, MAE: 3.3306690738754696e-16, RMSE: 6.661338147750939e-16
{'RANK': 22, 'OffRtg': 112.6, 'W': 26, 'L': 34, 'DefRtg': 114.7, 'NetRtg': -2.1, 'AST%': 70.2, 'AST/TO': 2.07, 'ASTRatio': 20.4, 'OREB%': 28.0, 'DREB%': 69.3, 'REB%': 48.9, 'TOV%': 14.0, 'eFG%': 53.9, 'TS%': 57.1, 'PACE': 100.21, 'POSS': 6038, 'TEAM': 'SAS', 'PIE': 50.3}

   OREB  DREB
0     1     4

Keon Ellis, MAE: 0.0, RMSE: 0.0
{'RANK': 22, 'OffRtg': 112.6, 'W': 26, 'L': 34, 'DefRtg': 114.7, 'NetRtg': -2.1, 'AST%': 70.2, 'AST/TO': 2.07, 'ASTRatio': 20.4, 'OREB%': 28.0, 'DREB%': 69.3, 'REB%': 48.9, 'TOV%': 14.0, 'eFG%': 53.9, 'TS%': 57.1, 'PACE': 100.21, 'POSS': 6038, 'TEAM': 'SAS', 'PIE': 50.3}

   OREB  DREB
0     0     2

Harrison Barnes, MAE: 4.440892098500626e-16, RMSE: 5.438959822042073e-16
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   OREB  DREB
0     1     3

Jeremy Sochan, MAE: 1.1102230246251565e-16, RMSE: 2.220446049250313e-16
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   OREB  DREB
0     2     3

Chris Paul, MAE: 8.881784197001252e-16, RMSE: 9.930136612989092e-16
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   OREB  DREB
0     0     2

Jake LaRavia, MAE: 6.661338147750939e-16, RMSE: 9.930136612989092e-16
{'RANK': 22, 'OffRtg': 112.6, 'W': 26, 'L': 34, 'DefRtg': 114.7, 'NetRtg': -2.1, 'AST%': 70.2, 'AST/TO': 2.07, 'ASTRatio': 20.4, 'OREB%': 28.0, 'DREB%': 69.3, 'REB%': 48.9, 'TOV%': 14.0, 'eFG%': 53.9, 'TS%': 57.1, 'PACE': 100.21, 'POSS': 6038, 'TEAM': 'SAS', 'PIE': 50.3}

   OREB  DREB
0     1     2

Julian Champagnie, MAE: 2.220446049250313e-16, RMSE: 3.1401849173675503e-16
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   OREB  DREB
0     0     1

Trey Lyles, MAE: 5.921189464667501e-16, RMSE: 1.0255800994045674e-15
{'RANK': 22, 'OffRtg': 112.6, 'W': 26, 'L': 34, 'DefRtg': 114.7, 'NetRtg': -2.1, 'AST%': 70.2, 'AST/TO': 2.07, 'ASTRatio': 20.4, 'OREB%': 28.0, 'DREB%': 69.3, 'REB%': 48.9, 'TOV%': 14.0, 'eFG%': 53.9, 'TS%': 57.1, 'PACE': 100.21, 'POSS': 6038, 'TEAM': 'SAS', 'PIE': 50.3}

   OREB  DREB
0     0     3

Bismack Biyombo, MAE: 1.6653345369377348e-15, RMSE: 1.9984014443252818e-15
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   MIN_x  FGA  OREB  DREB
0     14    2     1     2

Markelle Fultz, MAE: 8.326672684688674e-17, RMSE: 9.614813431917819e-17
{'RANK': 22, 'OffRtg': 112.6, 'W': 26, 'L': 34, 'DefRtg': 114.7, 'NetRtg': -2.1, 'AST%': 70.2, 'AST/TO': 2.07, 'ASTRatio': 20.4, 'OREB%': 28.0, 'DREB%': 69.3, 'REB%': 48.9, 'TOV%': 14.0, 'eFG%': 53.9, 'TS%': 57.1, 'PACE': 100.21, 'POSS': 6038, 'TEAM': 'SAS', 'PIE': 50.3}

   OREB  DREB
0     0     1

James Harden, MAE: 1.2434497875801752e-15, RMSE: 1.7540118387177282e-15
{'RANK': 4, 'OffRtg': 118.2, 'W': 40, 'L': 22, 'DefRtg': 114.0, 'NetRtg': 4.2, 'AST%': 62.2, 'AST/TO': 2.07, 'ASTRatio': 19.4, 'OREB%': 30.3, 'DREB%': 71.1, 'REB%': 50.9, 'TOV%': 13.3, 'eFG%': 56.0, 'TS%': 59.4, 'PACE': 98.12, 'POSS': 6148, 'TEAM': 'NYK', 'PIE': 52.5}

   OREB  DREB
0     0     4

Karl-Anthony Towns, MAE: 1.4802973661668755e-15, RMSE: 1.8488908177493114e-15
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   OREB  DREB
0     3     9

Kawhi Leonard, MAE: 2.220446049250313e-15, RMSE: 2.3498992183808826e-15
{'RANK': 4, 'OffRtg': 118.2, 'W': 40, 'L': 22, 'DefRtg': 114.0, 'NetRtg': 4.2, 'AST%': 62.2, 'AST/TO': 2.07, 'ASTRatio': 19.4, 'OREB%': 30.3, 'DREB%': 71.1, 'REB%': 50.9, 'TOV%': 13.3, 'eFG%': 56.0, 'TS%': 59.4, 'PACE': 98.12, 'POSS': 6148, 'TEAM': 'NYK', 'PIE': 52.5}

   OREB  DREB
0     0     4

Mikal Bridges, MAE: 1.7763568394002506e-16, RMSE: 2.808666774861361e-16
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   OREB  DREB
0     0     2

Bogdan Bogdanovic, MAE: 3.552713678800501e-16, RMSE: 3.9720546451956367e-16
{'RANK': 4, 'OffRtg': 118.2, 'W': 40, 'L': 22, 'DefRtg': 114.0, 'NetRtg': 4.2, 'AST%': 62.2, 'AST/TO': 2.07, 'ASTRatio': 19.4, 'OREB%': 30.3, 'DREB%': 71.1, 'REB%': 50.9, 'TOV%': 13.3, 'eFG%': 56.0, 'TS%': 59.4, 'PACE': 98.12, 'POSS': 6148, 'TEAM': 'NYK', 'PIE': 52.5}

   OREB  DREB
0     0     1

OG Anunoby, MAE: 7.105427357601002e-16, RMSE: 9.729507111180987e-16
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   OREB  DREB
0     1     2

Ivica Zubac, MAE: 1.0658141036401502e-15, RMSE: 1.7763568394002505e-15
{'RANK': 4, 'OffRtg': 118.2, 'W': 40, 'L': 22, 'DefRtg': 114.0, 'NetRtg': 4.2, 'AST%': 62.2, 'AST/TO': 2.07, 'ASTRatio': 19.4, 'OREB%': 30.3, 'DREB%': 71.1, 'REB%': 50.9, 'TOV%': 13.3, 'eFG%': 56.0, 'TS%': 59.4, 'PACE': 98.12, 'POSS': 6148, 'TEAM': 'NYK', 'PIE': 52.5}

   OREB  DREB
0     3     8

Miles McBride, MAE: 6.217248937900876e-16, RMSE: 7.021666937153402e-16
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   OREB  DREB
0     0     1

Josh Hart, MAE: 1.9539925233402757e-15, RMSE: 2.2817716744798718e-15
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   OREB  DREB
0     2     7

Cameron Payne, MAE: 1.3322676295501878e-16, RMSE: 1.7199501139797033e-16
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   OREB  DREB
0     0     1

Amir Coffey, MAE: 4.884981308350689e-16, RMSE: 5.347542221830668e-16
{'RANK': 4, 'OffRtg': 118.2, 'W': 40, 'L': 22, 'DefRtg': 114.0, 'NetRtg': 4.2, 'AST%': 62.2, 'AST/TO': 2.07, 'ASTRatio': 19.4, 'OREB%': 30.3, 'DREB%': 71.1, 'REB%': 50.9, 'TOV%': 13.3, 'eFG%': 56.0, 'TS%': 59.4, 'PACE': 98.12, 'POSS': 6148, 'TEAM': 'NYK', 'PIE': 52.5}

   OREB  DREB
0     0     1

Kris Dunn, MAE: 1.4654943925052066e-15, RMSE: 1.8011636440705246e-15
{'RANK': 4, 'OffRtg': 118.2, 'W': 40, 'L': 22, 'DefRtg': 114.0, 'NetRtg': 4.2, 'AST%': 62.2, 'AST/TO': 2.07, 'ASTRatio': 19.4, 'OREB%': 30.3, 'DREB%': 71.1, 'REB%': 50.9, 'TOV%': 13.3, 'eFG%': 56.0, 'TS%': 59.4, 'PACE': 98.12, 'POSS': 6148, 'TEAM': 'NYK', 'PIE': 52.5}

   OREB  DREB
0     1     2

Precious Achiuwa, MAE: 1.0362081563168128e-15, RMSE: 1.2819751242557094e-15
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   OREB  DREB
0     2     4

Drew Eubanks, MAE: 1.3322676295501878e-15, RMSE: 1.9860273225978185e-15
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   OREB  DREB
0     1     3

Nicolas Batum, MAE: 6.217248937900876e-16, RMSE: 7.691850745534255e-16
{'RANK': 4, 'OffRtg': 118.2, 'W': 40, 'L': 22, 'DefRtg': 114.0, 'NetRtg': 4.2, 'AST%': 62.2, 'AST/TO': 2.07, 'ASTRatio': 19.4, 'OREB%': 30.3, 'DREB%': 71.1, 'REB%': 50.9, 'TOV%': 13.3, 'eFG%': 56.0, 'TS%': 59.4, 'PACE': 98.12, 'POSS': 6148, 'TEAM': 'NYK', 'PIE': 52.5}

   OREB  DREB
0     0     2

c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.661e+01, tolerance: 7.227e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.424e+01, tolerance: 6.032e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.370e+02, tolerance: 7.578e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.116e+02, tolerance: 7.463e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.510e+02, tolerance: 7.777e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.847e-01, tolerance: 7.227e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.118e-01, tolerance: 6.032e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.231e+00, tolerance: 7.463e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.529e+02, tolerance: 8.493e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.239e+01, tolerance: 8.418e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.566e+01, tolerance: 8.019e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.407e+01, tolerance: 8.078e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.013e+01, tolerance: 8.000e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.902e-01, tolerance: 8.493e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.479e+01, tolerance: 1.352e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.885e+02, tolerance: 1.413e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.030e+02, tolerance: 1.250e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.116e+01, tolerance: 1.229e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.487e+02, tolerance: 1.286e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.473e-01, tolerance: 1.250e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.462e-01, tolerance: 1.229e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.036e-01, tolerance: 1.286e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.102e+02, tolerance: 7.452e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.350e+02, tolerance: 7.590e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.563e+02, tolerance: 7.106e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.254e+02, tolerance: 8.203e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.541e+01, tolerance: 8.419e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.290e-01, tolerance: 8.203e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.917e+00, tolerance: 2.296e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.626e+01, tolerance: 2.192e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.655e+00, tolerance: 2.220e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.772e+00, tolerance: 1.579e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.518e+00, tolerance: 2.320e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.292e+01, tolerance: 6.724e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.802e+01, tolerance: 5.626e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.233e+00, tolerance: 6.368e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.167e+01, tolerance: 5.732e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.592e+01, tolerance: 6.120e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.483e-01, tolerance: 5.626e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.190e-02, tolerance: 5.732e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.418e+01, tolerance: 3.349e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.271e+01, tolerance: 3.466e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.782e+00, tolerance: 3.376e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.866e+00, tolerance: 2.808e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.287e+00, tolerance: 2.706e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.151e+02, tolerance: 1.086e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.975e+01, tolerance: 1.271e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.528e+02, tolerance: 1.179e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.187e+02, tolerance: 1.120e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.068e+01, tolerance: 1.307e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.787e-01, tolerance: 1.179e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.015e+01, tolerance: 5.279e-02
  model = cd_fast.enet_coordinate_descent(

Kevin Durant, MAE: 1.933214058253217, RMSE: 1.9339130441971706
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   MIN_x  FG%  3P%  FT%  DREB  STL  BLK  TOV  +/-   L  DefRtg  AST%  OREB%  DREB%  REB%  TOV%  home_away
0     37   54   43   80     5    1    1    2    2  22   113.9  68.1   31.2   71.0  52.2  14.1          1

Devin Booker, MAE: 1.242695745384355, RMSE: 1.4224230009849386
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   MIN_x  PTS  FG%  3PM  FTM  FTA  STL  BLK  +/-  MIN_y  DefRtg  AST%  ASTRatio  REB%  Date_in_Seconds
0     38   27   46    2    6    7    0    0   -2   3000   113.9  68.1      21.1  52.2       1738800000

Nikola Jokic, MAE: 2.734589401084591, RMSE: 2.994381332745178
{'RANK': 17, 'OffRtg': 114.3, 'W': 29, 'L': 33, 'DefRtg': 116.3, 'NetRtg': -2.1, 'AST%': 67.6, 'AST/TO': 1.97, 'ASTRatio': 19.9, 'OREB%': 25.7, 'DREB%': 70.6, 'REB%': 49.1, 'TOV%': 14.1, 'eFG%': 56.0, 'TS%': 59.6, 'PACE': 98.82, 'POSS': 6177, 'TEAM': 'PHX', 'PIE': 50.1}

   MIN_x  FGA  3PM  3P%  FTA  FT%  OREB  DREB  STL  BLK  TOV  PF  +/-  eFG%   PACE  team_pace  Date_in_Seconds  home_away
0     35   16    1   35    5   73     2    10    1    0    3   2    7  56.0  98.82        101       1739141280          0

Jamal Murray, MAE: 1.221519893615353, RMSE: 1.369184031819043
{'RANK': 17, 'OffRtg': 114.3, 'W': 29, 'L': 33, 'DefRtg': 116.3, 'NetRtg': -2.1, 'AST%': 67.6, 'AST/TO': 1.97, 'ASTRatio': 19.9, 'OREB%': 25.7, 'DREB%': 70.6, 'REB%': 49.1, 'TOV%': 14.1, 'eFG%': 56.0, 'TS%': 59.6, 'PACE': 98.82, 'POSS': 6177, 'TEAM': 'PHX', 'PIE': 50.1}

   MIN_x  PTS  3PM  DREB  TOV  +/-  AST/TO  DREB%  TOV%  team_pace  team_poss  home_away
0     36   23    2     2    2    5    1.97   70.6  14.1        101       6301          0

Michael Porter Jr., MAE: 0.7568731613720789, RMSE: 1.0481490179927164
{'RANK': 17, 'OffRtg': 114.3, 'W': 29, 'L': 33, 'DefRtg': 116.3, 'NetRtg': -2.1, 'AST%': 67.6, 'AST/TO': 1.97, 'ASTRatio': 19.9, 'OREB%': 25.7, 'DREB%': 70.6, 'REB%': 49.1, 'TOV%': 14.1, 'eFG%': 56.0, 'TS%': 59.6, 'PACE': 98.82, 'POSS': 6177, 'TEAM': 'PHX', 'PIE': 50.1}

   MIN_x  PTS  FGA  3PM  3PA  3P%  FTM  FT%  DREB  REB  STL  BLK  TOV  PF  +/-  RANK  GP  OffRtg  NetRtg  AST%  ASTRatio  eFG%   PACE   PIE  Date_in_Seconds  home_away
0     32   17   13    2    6   36    2   70     5    7    0    0    1   1    4    17  62   114.3    -2.1  67.6      19.9  56.0  98.82  50.1       1738830240          0

Bradley Beal, MAE: 0.4519126253843999, RMSE: 0.4523603379765806
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   MIN_x  FGM  FG%  OREB  STL  BLK  TOV  PF  +/-   L  DefRtg  TOV%    PACE  POSS  home_away
0     31    6   50     0    0    0    1   2   -3  22   113.9  14.1  101.01  6301          1

Christian Braun, MAE: 1.7227860547878295, RMSE: 2.0717281421205986
{'RANK': 17, 'OffRtg': 114.3, 'W': 29, 'L': 33, 'DefRtg': 116.3, 'NetRtg': -2.1, 'AST%': 67.6, 'AST/TO': 1.97, 'ASTRatio': 19.9, 'OREB%': 25.7, 'DREB%': 70.6, 'REB%': 49.1, 'TOV%': 14.1, 'eFG%': 56.0, 'TS%': 59.6, 'PACE': 98.82, 'POSS': 6177, 'TEAM': 'PHX', 'PIE': 50.1}

   MIN_x  FG%  3PM  3PA  FTA  FT%  OREB  TOV  PF  +/-   W  NetRtg  AST%  REB%
0     34   57    1    3    3   80     1    0   1    7  29    -2.1  67.6  49.1

Russell Westbrook, MAE: 1.3201552207751917, RMSE: 1.8221846626719687
{'RANK': 17, 'OffRtg': 114.3, 'W': 29, 'L': 33, 'DefRtg': 116.3, 'NetRtg': -2.1, 'AST%': 67.6, 'AST/TO': 1.97, 'ASTRatio': 19.9, 'OREB%': 25.7, 'DREB%': 70.6, 'REB%': 49.1, 'TOV%': 14.1, 'eFG%': 56.0, 'TS%': 59.6, 'PACE': 98.82, 'POSS': 6177, 'TEAM': 'PHX', 'PIE': 50.1}

   MIN_x  FGA  3P%  FT%  DREB  BLK  TOV  PF  +/-  DefRtg  DREB%  REB%  TOV%   TS%   PACE  team_pace  Date_in_Seconds  home_away
0     28   11   29   61     3    0    3   2    3   116.3   70.6  49.1  14.1  59.6  98.82        101       1738419840          0

Aaron Gordon, MAE: 0.5013944883812655, RMSE: 0.5013944883812655
{'RANK': 17, 'OffRtg': 114.3, 'W': 29, 'L': 33, 'DefRtg': 116.3, 'NetRtg': -2.1, 'AST%': 67.6, 'AST/TO': 1.97, 'ASTRatio': 19.9, 'OREB%': 25.7, 'DREB%': 70.6, 'REB%': 49.1, 'TOV%': 14.1, 'eFG%': 56.0, 'TS%': 59.6, 'PACE': 98.82, 'POSS': 6177, 'TEAM': 'PHX', 'PIE': 50.1}

   MIN_x  PTS  FGA  3PM  3PA  3P%  FTM  FT%  DREB  REB  STL  BLK  TOV  PF  +/-  RANK  GP  OffRtg  NetRtg  AST%  ASTRatio  eFG%   PACE   PIE  Date_in_Seconds  home_away
0     24   11    8    1    2   42    1   64     2    4    0    0    1   1    5    17  62   114.3    -2.1  67.6      19.9  56.0  98.82  50.1       1738255680          0

Bol Bol, MAE: 0.8350815831010294, RMSE: 1.0261924259546067
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   MIN_x  DREB  STL  +/-  team_pace
0     15     3    0   -2         98

Nick Richards, MAE: 0.658185459150648, RMSE: 0.6616170586478078
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   MIN_x  BLK  TOV  POSS
0     22    0    1  6301

Grayson Allen, MAE: 0.6442773865826416, RMSE: 0.7875831438608165
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   MIN_x  FG%  3PA  FT%  OREB  DREB  STL  BLK  TOV  PF  +/-  DefRtg  AST%  AST/TO  OREB%  team_pace  home_away
0     25   44    5   36     0     2    0    0    1   1    0   113.9  68.1    2.16   31.2         98          1

Royce O'Neale, MAE: 0.7974655225084701, RMSE: 0.9419295150552391
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   MIN_x  3P%  FT%  REB  +/-  OffRtg  DefRtg  AST/TO   TS%  team_poss
0     25   40    5    3   -2   119.1   113.9    2.16  60.4       6177

Mason Plumlee, MAE: 0.8826918235442003, RMSE: 1.165873179009217
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   MIN_x  FGM  3PA  FTA  OREB  REB  STL  TOV   L  DREB%  REB%  team_offrtg  team_poss
0     18    1    0    1     1    6    0    0  22   71.0  52.2          114       6177

DeMar DeRozan, MAE: 1.2025361613478784, RMSE: 1.7140494027609448
{'RANK': 22, 'OffRtg': 112.6, 'W': 26, 'L': 34, 'DefRtg': 114.7, 'NetRtg': -2.1, 'AST%': 70.2, 'AST/TO': 2.07, 'ASTRatio': 20.4, 'OREB%': 28.0, 'DREB%': 69.3, 'REB%': 48.9, 'TOV%': 14.0, 'eFG%': 53.9, 'TS%': 57.1, 'PACE': 100.21, 'POSS': 6038, 'TEAM': 'SAS', 'PIE': 50.3}

   MIN_x  FG%  3PA  3P%  FTM  TOV  PF  +/-  AST%  DREB%  REB%  POSS  team_poss
0     36   49    3   35    5    1   1    1  70.2   69.3  48.9  6038       6152

Devin Vassell, MAE: 1.4476865149770406, RMSE: 1.685174388437973
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   MIN_x  PTS  FGA  3PM  3PA  3P%  FTM  FT%  DREB  REB  STL  BLK  TOV  PF  +/-  RANK  GP  OffRtg  NetRtg  AST%  ASTRatio  eFG%   PACE   PIE  Date_in_Seconds  home_away
0     31   15   14    2    6   31    1   49     3    3    1    0    1   1   -3    15  62   115.8     2.0  61.8      18.9  54.6  99.79  50.9       1739249280          1

De'Aaron Fox, MAE: 1.433728351319676, RMSE: 1.4570593697105005
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   MIN_x  PTS  3PM  3PA  DREB  STL  BLK  TOV  +/-  DefRtg  REB%  TOV%   PACE  team_offrtg  Date_in_Seconds
0     34   18    1    5     3    1    0    2   -3   113.8  51.1  13.4  99.79          112       1739180160

Keldon Johnson, MAE: 1.5874210574502599, RMSE: 2.0594959661154038
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   MIN_x  FG%  3P%  FTA  OREB  TOV  +/-   L  DefRtg  DREB%
0     21   47   38    2     1    1   -2  29   113.8   72.7

Jonas Valanciunas, MAE: 1.1619710812020227, RMSE: 1.3122809371402664
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   MIN_x  PTS  FGA  3PM  3PA  3P%  FTM  FT%  DREB  REB  STL  BLK  TOV  PF  +/-  RANK  GP  OffRtg  NetRtg  AST%  ASTRatio  eFG%   PACE   PIE  Date_in_Seconds  home_away
0     19   10    7    0    0   10    2   81     5    7    0    0    1   2   -2    15  62   115.8     2.0  61.8      18.9  54.6  99.79  50.9       1739033280          1

Keegan Murray, MAE: 1.1139683374399167, RMSE: 1.2911890103023995
{'RANK': 22, 'OffRtg': 112.6, 'W': 26, 'L': 34, 'DefRtg': 114.7, 'NetRtg': -2.1, 'AST%': 70.2, 'AST/TO': 2.07, 'ASTRatio': 20.4, 'OREB%': 28.0, 'DREB%': 69.3, 'REB%': 48.9, 'TOV%': 14.0, 'eFG%': 53.9, 'TS%': 57.1, 'PACE': 100.21, 'POSS': 6038, 'TEAM': 'SAS', 'PIE': 50.3}

   MIN_x  PTS  FGA  3PM  3PA  3P%  FTM  FT%  DREB  REB  STL  BLK  TOV  PF  +/-  RANK  GP  OffRtg  NetRtg  AST%  ASTRatio  eFG%    PACE   PIE  Date_in_Seconds  home_away
0     31   12   10    1    5   33    0   28     4    5    1    0    0   2    0    22  62   112.6    -2.1  70.2      20.4  53.9  100.21  50.3       1739063520          0

Keon Ellis, MAE: 1.025336013222958, RMSE: 1.3847092804958272
{'RANK': 22, 'OffRtg': 112.6, 'W': 26, 'L': 34, 'DefRtg': 114.7, 'NetRtg': -2.1, 'AST%': 70.2, 'AST/TO': 2.07, 'ASTRatio': 20.4, 'OREB%': 28.0, 'DREB%': 69.3, 'REB%': 48.9, 'TOV%': 14.0, 'eFG%': 53.9, 'TS%': 57.1, 'PACE': 100.21, 'POSS': 6038, 'TEAM': 'SAS', 'PIE': 50.3}

   MIN_x  3P%  FTM  OREB  STL  TOV  PF  +/-  MIN_y  DREB%  REB%    PACE  team_pace
0     25   45    0     0    1    0   2   -2   3016   69.3  48.9  100.21         99

Harrison Barnes, MAE: 0.7053305671305266, RMSE: 0.8753458495065095
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   OREB  REB  BLK  +/-  MIN_y  OREB%  DREB%  TOV%   PACE  team_offrtg  home_away
0     1    4    0   -2   2995   29.4   72.7  13.4  99.79          112          1

Jeremy Sochan, MAE: 1.2291926227593808, RMSE: 1.2779790065653513
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   MIN_x  FG%  FTA  REB  AST%  OREB%  TOV%
0     21   56    1    5  61.8   29.4  13.4

Chris Paul, MAE: 1.4113220696683082, RMSE: 2.228853104750868
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   MIN_x  FGM  FG%  3PM  FTA  OREB  REB  STL  TOV  PF  +/-  OREB%  REB%  TOV%   PACE  home_away
0     27    2   43    1    1     0    2    1    1   1   -1   29.4  51.1  13.4  99.79          1

Jake LaRavia, MAE: 1.537249072248989, RMSE: 1.6579902334998111
{'RANK': 22, 'OffRtg': 112.6, 'W': 26, 'L': 34, 'DefRtg': 114.7, 'NetRtg': -2.1, 'AST%': 70.2, 'AST/TO': 2.07, 'ASTRatio': 20.4, 'OREB%': 28.0, 'DREB%': 69.3, 'REB%': 48.9, 'TOV%': 14.0, 'eFG%': 53.9, 'TS%': 57.1, 'PACE': 100.21, 'POSS': 6038, 'TEAM': 'SAS', 'PIE': 50.3}

   MIN_x  3PM  3PA  FTA  OREB  STL  +/-   L  MIN_y  AST%    PACE  home_away
0     15    0    1    0     1    1    0  34   3002  70.2  100.21          0

Julian Champagnie, MAE: 1.4607254073264038, RMSE: 1.7502207097513305
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   MIN_x  PTS  FGA  3PM  3PA  3P%  FTM  FT%  DREB  REB  STL  BLK  TOV  PF  +/-  RANK  GP  OffRtg  NetRtg  AST%  ASTRatio  eFG%   PACE   PIE  Date_in_Seconds  home_away
0     17    6    5    1    3   35    0   32     1    2    1    0    0   1    0    15  62   115.8     2.0  61.8      18.9  54.6  99.79  50.9       1739249280          1

Trey Lyles, MAE: 1.5402418918210434, RMSE: 2.2418461667920186
{'RANK': 22, 'OffRtg': 112.6, 'W': 26, 'L': 34, 'DefRtg': 114.7, 'NetRtg': -2.1, 'AST%': 70.2, 'AST/TO': 2.07, 'ASTRatio': 20.4, 'OREB%': 28.0, 'DREB%': 69.3, 'REB%': 48.9, 'TOV%': 14.0, 'eFG%': 53.9, 'TS%': 57.1, 'PACE': 100.21, 'POSS': 6038, 'TEAM': 'SAS', 'PIE': 50.3}

   MIN_x  FG%  3P%  FTM  REB  TOV  TOV%
0     14   44   33    0    4    0  14.0

Bismack Biyombo, MAE: 0.7839750427365637, RMSE: 0.9947754751312387
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   MIN_x  OREB  BLK  TOV  PF  AST/TO  home_away
0     14     1    0    0   1    1.99          1

Markelle Fultz, MAE: 1.3942011324597008, RMSE: 1.600739368831481
{'RANK': 22, 'OffRtg': 112.6, 'W': 26, 'L': 34, 'DefRtg': 114.7, 'NetRtg': -2.1, 'AST%': 70.2, 'AST/TO': 2.07, 'ASTRatio': 20.4, 'OREB%': 28.0, 'DREB%': 69.3, 'REB%': 48.9, 'TOV%': 14.0, 'eFG%': 53.9, 'TS%': 57.1, 'PACE': 100.21, 'POSS': 6038, 'TEAM': 'SAS', 'PIE': 50.3}

   MIN_x  FGA  FG%  3PM  FTM  OREB  DREB  STL  TOV  +/-  RANK  ASTRatio  DREB%    PACE  team_pace  Date_in_Seconds
0     16    6   46    0    0     0     1    0    1    0    22      20.4   69.3  100.21         99       1720500480

James Harden, MAE: 1.6964826717575932, RMSE: 2.2924508507272776
{'RANK': 4, 'OffRtg': 118.2, 'W': 40, 'L': 22, 'DefRtg': 114.0, 'NetRtg': 4.2, 'AST%': 62.2, 'AST/TO': 2.07, 'ASTRatio': 19.4, 'OREB%': 30.3, 'DREB%': 71.1, 'REB%': 50.9, 'TOV%': 13.3, 'eFG%': 56.0, 'TS%': 59.4, 'PACE': 98.12, 'POSS': 6148, 'TEAM': 'NYK', 'PIE': 52.5}

   MIN_x  FGA  FG%  3PM  3PA  FTM  FTA  FT%  OREB  DREB  STL  BLK  TOV  PF  +/-  DefRtg  AST%  OREB%  TOV%   TS%   PACE  team_pace  Date_in_Seconds  home_away
0     37   17   37    3    9    6    7   87     0     4    1    0    4   2    0   114.0  62.2   30.3  13.3  59.4  98.12         98       1739275200          0

Karl-Anthony Towns, MAE: 2.344512662381373, RMSE: 2.6259763757389307
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   MIN_x  3PM  3P%  FTA  OREB  STL  +/-  OffRtg  DefRtg   TS%  team_pace  Date_in_Seconds
0     36    1   36    5     3    1    2   111.9   109.7  57.8         98       1738730880

Kawhi Leonard, MAE: 1.058610410815783, RMSE: 1.6591430155929945
{'RANK': 4, 'OffRtg': 118.2, 'W': 40, 'L': 22, 'DefRtg': 114.0, 'NetRtg': 4.2, 'AST%': 62.2, 'AST/TO': 2.07, 'ASTRatio': 19.4, 'OREB%': 30.3, 'DREB%': 71.1, 'REB%': 50.9, 'TOV%': 13.3, 'eFG%': 56.0, 'TS%': 59.4, 'PACE': 98.12, 'POSS': 6148, 'TEAM': 'NYK', 'PIE': 52.5}

   MIN_x  FGA  FTA  DREB  BLK  TOV  +/-  RANK   L  AST/TO  TOV%   TS%   PACE  Date_in_Seconds  home_away
0     28   15    2     4    0    2    5     4  22    2.07  13.3  59.4  98.12       1738497600          0

Mikal Bridges, MAE: 2.189595601227878, RMSE: 2.8775747311225417
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   MIN_x  PTS  FGA  3PM  3PA  3P%  FTM  FT%  DREB  REB  STL  BLK  TOV  PF  +/-  RANK  GP  OffRtg  NetRtg  AST%  ASTRatio  eFG%   PACE   PIE  Date_in_Seconds  home_away
0     35   15   13    1    4   32    0   32     2    3    0    0    1   1    0    14  62   111.9     2.2  60.8      18.0  54.1  98.71  50.9       1739171520          1

Bogdan Bogdanovic, MAE: 1.2853568117605527, RMSE: 2.108874052961351
{'RANK': 4, 'OffRtg': 118.2, 'W': 40, 'L': 22, 'DefRtg': 114.0, 'NetRtg': 4.2, 'AST%': 62.2, 'AST/TO': 2.07, 'ASTRatio': 19.4, 'OREB%': 30.3, 'DREB%': 71.1, 'REB%': 50.9, 'TOV%': 13.3, 'eFG%': 56.0, 'TS%': 59.4, 'PACE': 98.12, 'POSS': 6148, 'TEAM': 'NYK', 'PIE': 52.5}

   MIN_x  PTS  FGA  3PM  3PA  3P%  FTM  FT%  DREB  REB  STL  BLK  TOV  PF  +/-  RANK  GP  OffRtg  NetRtg  AST%  ASTRatio  eFG%   PACE   PIE  Date_in_Seconds  home_away
0     25   10   10    1    6   32    0   32     1    2    0    0    1   2    0     4  62   118.2     4.2  62.2      19.4  56.0  98.12  52.5       1738657440          0

OG Anunoby, MAE: 1.2046777729066, RMSE: 1.6040086624003278
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   MIN_x  PTS  FGA  3PM  3PA  3P%  FTM  FT%  DREB  REB  STL  BLK  TOV  PF  +/-  RANK  GP  OffRtg  NetRtg  AST%  ASTRatio  eFG%   PACE   PIE  Date_in_Seconds  home_away
0     36   16   12    2    6   34    2   57     2    4    1    0    1   2    1    14  62   111.9     2.2  60.8      18.0  54.1  98.71  50.9       1738393920          1

Ivica Zubac, MAE: 0.9938058706865064, RMSE: 1.3944294653412486
{'RANK': 4, 'OffRtg': 118.2, 'W': 40, 'L': 22, 'DefRtg': 114.0, 'NetRtg': 4.2, 'AST%': 62.2, 'AST/TO': 2.07, 'ASTRatio': 19.4, 'OREB%': 30.3, 'DREB%': 71.1, 'REB%': 50.9, 'TOV%': 13.3, 'eFG%': 56.0, 'TS%': 59.4, 'PACE': 98.12, 'POSS': 6148, 'TEAM': 'NYK', 'PIE': 52.5}

   MIN_x  FG%  REB  +/-  DefRtg  ASTRatio  eFG%   TS%  team_poss  Date_in_Seconds
0     32   61   12    5   114.0      19.4  56.0  59.4       6147       1739270880

Miles McBride, MAE: 1.1885847258525088, RMSE: 1.328977037071586
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   MIN_x  3PM  3PA  OREB  REB  STL  BLK  PF  +/-   PACE  team_offrtg
0     23    1    4     0    2    1    0   1    2  98.71          118

Josh Hart, MAE: 3.5857026933055365, RMSE: 3.8989197427985913
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   MIN_x  FGM  FGA  3P%  FTA  FT%  DREB  REB  STL  BLK  TOV  PF  +/-  GP  DefRtg  AST%  TOV%   TS%   PACE
0     38    5   11   18    3   52     7   10    1    0    2   2   -2  62   109.7  60.8  15.7  57.8  98.71

Cameron Payne, MAE: 1.3809513926347983, RMSE: 1.4798388204103001
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   MIN_x  3PM  FT%  STL  BLK  +/-   L  DefRtg  ASTRatio  team_pace  Date_in_Seconds
0     12    0   43    0    0    2  29   109.7      18.0         98       1739171520

Amir Coffey, MAE: 0.8866612616099004, RMSE: 1.1705735622543612
{'RANK': 4, 'OffRtg': 118.2, 'W': 40, 'L': 22, 'DefRtg': 114.0, 'NetRtg': 4.2, 'AST%': 62.2, 'AST/TO': 2.07, 'ASTRatio': 19.4, 'OREB%': 30.3, 'DREB%': 71.1, 'REB%': 50.9, 'TOV%': 13.3, 'eFG%': 56.0, 'TS%': 59.4, 'PACE': 98.12, 'POSS': 6148, 'TEAM': 'NYK', 'PIE': 52.5}

   MIN_x  FG%  FT%  BLK  TOV  DREB%  Date_in_Seconds  home_away
0     26   41   70    0    0   71.1       1739180160          0

Kris Dunn, MAE: 1.0356720590351416, RMSE: 1.2313792212142116
{'RANK': 4, 'OffRtg': 118.2, 'W': 40, 'L': 22, 'DefRtg': 114.0, 'NetRtg': 4.2, 'AST%': 62.2, 'AST/TO': 2.07, 'ASTRatio': 19.4, 'OREB%': 30.3, 'DREB%': 71.1, 'REB%': 50.9, 'TOV%': 13.3, 'eFG%': 56.0, 'TS%': 59.4, 'PACE': 98.12, 'POSS': 6148, 'TEAM': 'NYK', 'PIE': 52.5}

   MIN_x  FGA  3P%  FTM  OREB  REB  STL  BLK  TOV  PF  +/-  RANK  AST%  OREB%  DREB%  TOV%  team_offrtg  team_poss  Date_in_Seconds
0     23    5   35    0     1    3    2    0    0   2    2     4  62.2   30.3   71.1  13.3          111       6147       1738882080

Precious Achiuwa, MAE: 0.8006601674529037, RMSE: 0.9723776133700067
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   MIN_x  FTM  FTA  REB  OREB%  TOV%   PACE
0     26    1    1    6   28.5  15.7  98.71

Drew Eubanks, MAE: 0.8540491754596617, RMSE: 0.8819931587470997
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   MIN_x  FGA  REB  PF  REB%  team_pace
0     14    4    4   0  51.0         98

Nicolas Batum, MAE: 0.7951637935349346, RMSE: 0.8666230843094118
{'RANK': 4, 'OffRtg': 118.2, 'W': 40, 'L': 22, 'DefRtg': 114.0, 'NetRtg': 4.2, 'AST%': 62.2, 'AST/TO': 2.07, 'ASTRatio': 19.4, 'OREB%': 30.3, 'DREB%': 71.1, 'REB%': 50.9, 'TOV%': 13.3, 'eFG%': 56.0, 'TS%': 59.4, 'PACE': 98.12, 'POSS': 6148, 'TEAM': 'NYK', 'PIE': 52.5}

   MIN_x  FT%  OREB  REB  TOV  +/-   PACE  POSS  team_offrtg
0     15   15     0    2    0   -1  98.12  6148          111

Kevin Durant, MAE: 3.634925791746584, RMSE: 3.635372823025492
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   FGM  3PM  FTM  RANK
0    9    2    3     4

Devin Booker, MAE: 4.081206409636815, RMSE: 4.397919533864541
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   FGM  3PM  FTM
0    9    2    6

Nikola Jokic, MAE: 3.9968028886505635e-15, RMSE: 4.259554063523935e-15
{'RANK': 17, 'OffRtg': 114.3, 'W': 29, 'L': 33, 'DefRtg': 116.3, 'NetRtg': -2.1, 'AST%': 67.6, 'AST/TO': 1.97, 'ASTRatio': 19.9, 'OREB%': 25.7, 'DREB%': 70.6, 'REB%': 49.1, 'TOV%': 14.1, 'eFG%': 56.0, 'TS%': 59.6, 'PACE': 98.82, 'POSS': 6177, 'TEAM': 'PHX', 'PIE': 50.1}

   FGM  FGA  FG%  3PM  FTM
0   10   16   60    1    4

Jamal Murray, MAE: 2.5729073319050535, RMSE: 2.622333415465926
{'RANK': 17, 'OffRtg': 114.3, 'W': 29, 'L': 33, 'DefRtg': 116.3, 'NetRtg': -2.1, 'AST%': 67.6, 'AST/TO': 1.97, 'ASTRatio': 19.9, 'OREB%': 25.7, 'DREB%': 70.6, 'REB%': 49.1, 'TOV%': 14.1, 'eFG%': 56.0, 'TS%': 59.6, 'PACE': 98.82, 'POSS': 6177, 'TEAM': 'PHX', 'PIE': 50.1}

   FGM  3PM  3PA  3P%  FTM  FTA
0    8    2    6   37    3    3

Michael Porter Jr., MAE: 3.593734802399948, RMSE: 5.352331071152524
{'RANK': 17, 'OffRtg': 114.3, 'W': 29, 'L': 33, 'DefRtg': 116.3, 'NetRtg': -2.1, 'AST%': 67.6, 'AST/TO': 1.97, 'ASTRatio': 19.9, 'OREB%': 25.7, 'DREB%': 70.6, 'REB%': 49.1, 'TOV%': 14.1, 'eFG%': 56.0, 'TS%': 59.6, 'PACE': 98.82, 'POSS': 6177, 'TEAM': 'PHX', 'PIE': 50.1}

   FGM  3PM  FTM
0    6    2    2

Bradley Beal, MAE: 0.5748864068947377, RMSE: 0.753389425291013
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   FGM  3PM  FTM
0    6    1    2

Christian Braun, MAE: 2.7959915043580104, RMSE: 3.8877579892607743
{'RANK': 17, 'OffRtg': 114.3, 'W': 29, 'L': 33, 'DefRtg': 116.3, 'NetRtg': -2.1, 'AST%': 67.6, 'AST/TO': 1.97, 'ASTRatio': 19.9, 'OREB%': 25.7, 'DREB%': 70.6, 'REB%': 49.1, 'TOV%': 14.1, 'eFG%': 56.0, 'TS%': 59.6, 'PACE': 98.82, 'POSS': 6177, 'TEAM': 'PHX', 'PIE': 50.1}

   FGM  3PM  FTM
0    7    1    2

Russell Westbrook, MAE: 2.7596079572519474, RMSE: 2.86776582720498
{'RANK': 17, 'OffRtg': 114.3, 'W': 29, 'L': 33, 'DefRtg': 116.3, 'NetRtg': -2.1, 'AST%': 67.6, 'AST/TO': 1.97, 'ASTRatio': 19.9, 'OREB%': 25.7, 'DREB%': 70.6, 'REB%': 49.1, 'TOV%': 14.1, 'eFG%': 56.0, 'TS%': 59.6, 'PACE': 98.82, 'POSS': 6177, 'TEAM': 'PHX', 'PIE': 50.1}

   FGM  3PM  FTM  FTA
0    5    1    1    2

Aaron Gordon, MAE: 5.059191257604813, RMSE: 5.059191257604813
{'RANK': 17, 'OffRtg': 114.3, 'W': 29, 'L': 33, 'DefRtg': 116.3, 'NetRtg': -2.1, 'AST%': 67.6, 'AST/TO': 1.97, 'ASTRatio': 19.9, 'OREB%': 25.7, 'DREB%': 70.6, 'REB%': 49.1, 'TOV%': 14.1, 'eFG%': 56.0, 'TS%': 59.6, 'PACE': 98.82, 'POSS': 6177, 'TEAM': 'PHX', 'PIE': 50.1}

   FGM  3PM  FTM
0    4    1    1

Bol Bol, MAE: 1.894011773690302, RMSE: 2.191969507429045
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   FGM  3PM  FTM  FTA
0    3    1    0    0

Nick Richards, MAE: 0.6708954597588597, RMSE: 0.7592845026942623
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   FGM  3PM  FTM
0    3    0    2

Grayson Allen, MAE: 2.87606674563761, RMSE: 3.2418638794799826
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   FGM  3PM  FTM  FTA
0    3    2    1    1

Royce O'Neale, MAE: 1.5523473673498733, RMSE: 1.79405342120787
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   FGM  3PM  FTM
0    3    2    0

Mason Plumlee, MAE: 1.0109955761431362, RMSE: 1.133286790496573
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   FGM  FTM  FTA
0    1    1    1

DeMar DeRozan, MAE: 3.7505899860878005, RMSE: 5.158364027010926
{'RANK': 22, 'OffRtg': 112.6, 'W': 26, 'L': 34, 'DefRtg': 114.7, 'NetRtg': -2.1, 'AST%': 70.2, 'AST/TO': 2.07, 'ASTRatio': 20.4, 'OREB%': 28.0, 'DREB%': 69.3, 'REB%': 48.9, 'TOV%': 14.0, 'eFG%': 53.9, 'TS%': 57.1, 'PACE': 100.21, 'POSS': 6038, 'TEAM': 'SAS', 'PIE': 50.3}

   FGM  3PM  FTM  FTA
0    8    1    5    5

Devin Vassell, MAE: 1.3322676295501878e-15, RMSE: 2.6645352591003757e-15
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   MIN_x  FGM  FGA  FG%  3PM  FTM
0     31    6   14   41    2    1

De'Aaron Fox, MAE: 1.3332667698316403, RMSE: 1.7194861432630009
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   FGM  3PM  3PA  3P%  FTM
0    6    1    5   25    3

Keldon Johnson, MAE: 1.7899960144063969, RMSE: 1.876873107873917
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   MIN_x  FGM  3PM  FTM  FTA
0     21    4    1    1    2

Jonas Valanciunas, MAE: 2.706519442058159, RMSE: 3.0840791684182207
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   FGM  3PM  FTM
0    4    0    2

Keegan Murray, MAE: 1.041373365467753, RMSE: 1.3561214567056072
{'RANK': 22, 'OffRtg': 112.6, 'W': 26, 'L': 34, 'DefRtg': 114.7, 'NetRtg': -2.1, 'AST%': 70.2, 'AST/TO': 2.07, 'ASTRatio': 20.4, 'OREB%': 28.0, 'DREB%': 69.3, 'REB%': 48.9, 'TOV%': 14.0, 'eFG%': 53.9, 'TS%': 57.1, 'PACE': 100.21, 'POSS': 6038, 'TEAM': 'SAS', 'PIE': 50.3}

   FGM  3PM  FTM
0    4    1    0

Keon Ellis, MAE: 2.499240963983741, RMSE: 2.7571846883081923
{'RANK': 22, 'OffRtg': 112.6, 'W': 26, 'L': 34, 'DefRtg': 114.7, 'NetRtg': -2.1, 'AST%': 70.2, 'AST/TO': 2.07, 'ASTRatio': 20.4, 'OREB%': 28.0, 'DREB%': 69.3, 'REB%': 48.9, 'TOV%': 14.0, 'eFG%': 53.9, 'TS%': 57.1, 'PACE': 100.21, 'POSS': 6038, 'TEAM': 'SAS', 'PIE': 50.3}

   MIN_x  FGM  3PM  FTM  FTA
0     25    3    2    0    0

Harrison Barnes, MAE: 1.1041631445780071, RMSE: 1.1300567696546506
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   FGM  3PM  FTM
0    4    2    1

Jeremy Sochan, MAE: 2.9458024307253083, RMSE: 3.312646566206655
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   FGM  3PM  FTM  FTA  FT%
0    3    0    0    1   27

Chris Paul, MAE: 2.2015547275277845, RMSE: 2.4790397578076933
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   FGM  3PM  FTM
0    2    1    0

Jake LaRavia, MAE: 0.7762539766283427, RMSE: 0.8776218699756532
{'RANK': 22, 'OffRtg': 112.6, 'W': 26, 'L': 34, 'DefRtg': 114.7, 'NetRtg': -2.1, 'AST%': 70.2, 'AST/TO': 2.07, 'ASTRatio': 20.4, 'OREB%': 28.0, 'DREB%': 69.3, 'REB%': 48.9, 'TOV%': 14.0, 'eFG%': 53.9, 'TS%': 57.1, 'PACE': 100.21, 'POSS': 6038, 'TEAM': 'SAS', 'PIE': 50.3}

   MIN_x  FGM  3PM  FTM  FTA  FT%
0     15    1    0    0    0   15

Julian Champagnie, MAE: 1.6422789568198648, RMSE: 1.9007126146533637
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   FGM  3PM  FTM  FTA
0    2    1    0    0

Trey Lyles, MAE: 1.7920860915807058, RMSE: 1.9556788377993946
{'RANK': 22, 'OffRtg': 112.6, 'W': 26, 'L': 34, 'DefRtg': 114.7, 'NetRtg': -2.1, 'AST%': 70.2, 'AST/TO': 2.07, 'ASTRatio': 20.4, 'OREB%': 28.0, 'DREB%': 69.3, 'REB%': 48.9, 'TOV%': 14.0, 'eFG%': 53.9, 'TS%': 57.1, 'PACE': 100.21, 'POSS': 6038, 'TEAM': 'SAS', 'PIE': 50.3}

   FGM  3PM  FTM  FTA
0    1    0    0    0

Bismack Biyombo, MAE: 0.9198535829204023, RMSE: 1.0907072607960824
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   FGM  FTM
0    1    0

Markelle Fultz, MAE: 0.7978143980733658, RMSE: 0.8802010662835555
{'RANK': 22, 'OffRtg': 112.6, 'W': 26, 'L': 34, 'DefRtg': 114.7, 'NetRtg': -2.1, 'AST%': 70.2, 'AST/TO': 2.07, 'ASTRatio': 20.4, 'OREB%': 28.0, 'DREB%': 69.3, 'REB%': 48.9, 'TOV%': 14.0, 'eFG%': 53.9, 'TS%': 57.1, 'PACE': 100.21, 'POSS': 6038, 'TEAM': 'SAS', 'PIE': 50.3}

   MIN_x  FGM  3PM  FTM
0     16    2    0    0

James Harden, MAE: 3.8397031723107404, RMSE: 4.485397437047357
{'RANK': 4, 'OffRtg': 118.2, 'W': 40, 'L': 22, 'DefRtg': 114.0, 'NetRtg': 4.2, 'AST%': 62.2, 'AST/TO': 2.07, 'ASTRatio': 19.4, 'OREB%': 30.3, 'DREB%': 71.1, 'REB%': 50.9, 'TOV%': 13.3, 'eFG%': 56.0, 'TS%': 59.4, 'PACE': 98.12, 'POSS': 6148, 'TEAM': 'NYK', 'PIE': 52.5}

   FGM  3PM  FTM  FTA
0    6    3    6    7

Karl-Anthony Towns, MAE: 2.237316781926325, RMSE: 2.7286540311022205
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   FGM  3PM  FTM  FTA
0    8    1    4    5

Kawhi Leonard, MAE: 1.7756299280164938, RMSE: 2.012420629514898
{'RANK': 4, 'OffRtg': 118.2, 'W': 40, 'L': 22, 'DefRtg': 114.0, 'NetRtg': 4.2, 'AST%': 62.2, 'AST/TO': 2.07, 'ASTRatio': 19.4, 'OREB%': 30.3, 'DREB%': 71.1, 'REB%': 50.9, 'TOV%': 13.3, 'eFG%': 56.0, 'TS%': 59.4, 'PACE': 98.12, 'POSS': 6148, 'TEAM': 'NYK', 'PIE': 52.5}

   FGM  3PM  FTM  FTA
0    7    1    1    2

Mikal Bridges, MAE: 2.016092214799628, RMSE: 2.5173271401246695
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   FGM  3PM  FTM
0    6    1    0

Bogdan Bogdanovic, MAE: 3.155666747209449, RMSE: 4.000346594746444
{'RANK': 4, 'OffRtg': 118.2, 'W': 40, 'L': 22, 'DefRtg': 114.0, 'NetRtg': 4.2, 'AST%': 62.2, 'AST/TO': 2.07, 'ASTRatio': 19.4, 'OREB%': 30.3, 'DREB%': 71.1, 'REB%': 50.9, 'TOV%': 13.3, 'eFG%': 56.0, 'TS%': 59.4, 'PACE': 98.12, 'POSS': 6148, 'TEAM': 'NYK', 'PIE': 52.5}

   FGM  3PM  FTM  FTA
0    3    1    0    1

OG Anunoby, MAE: 3.3181261639964177, RMSE: 3.5133641522109023
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   FGM  3PM  FTM  FTA
0    5    2    2    2

Ivica Zubac, MAE: 1.908982961458976, RMSE: 2.6211203120646336
{'RANK': 4, 'OffRtg': 118.2, 'W': 40, 'L': 22, 'DefRtg': 114.0, 'NetRtg': 4.2, 'AST%': 62.2, 'AST/TO': 2.07, 'ASTRatio': 19.4, 'OREB%': 30.3, 'DREB%': 71.1, 'REB%': 50.9, 'TOV%': 13.3, 'eFG%': 56.0, 'TS%': 59.4, 'PACE': 98.12, 'POSS': 6148, 'TEAM': 'NYK', 'PIE': 52.5}

   FGM  FTM  FTA
0    7    2    2

Miles McBride, MAE: 1.110397681733941, RMSE: 1.384321788677427
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   MIN_x  FGM  3PM  FTM  FTA  FT%
0     23    3    1    0    0   27

Josh Hart, MAE: 1.7513585924496406, RMSE: 2.0942690584792727
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   FGM  3PM  FTM
0    5    0    2

Cameron Payne, MAE: 1.4222600354408477, RMSE: 1.6166699717465554
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   FGM  3PM  FTM  FT%
0    2    0    1   43

Amir Coffey, MAE: 2.1599010291441454, RMSE: 2.3001664892728355
{'RANK': 4, 'OffRtg': 118.2, 'W': 40, 'L': 22, 'DefRtg': 114.0, 'NetRtg': 4.2, 'AST%': 62.2, 'AST/TO': 2.07, 'ASTRatio': 19.4, 'OREB%': 30.3, 'DREB%': 71.1, 'REB%': 50.9, 'TOV%': 13.3, 'eFG%': 56.0, 'TS%': 59.4, 'PACE': 98.12, 'POSS': 6148, 'TEAM': 'NYK', 'PIE': 52.5}

   FGM  3PM  FTM
0    3    1    2

Kris Dunn, MAE: 1.3605596272534786, RMSE: 1.699638075970401
{'RANK': 4, 'OffRtg': 118.2, 'W': 40, 'L': 22, 'DefRtg': 114.0, 'NetRtg': 4.2, 'AST%': 62.2, 'AST/TO': 2.07, 'ASTRatio': 19.4, 'OREB%': 30.3, 'DREB%': 71.1, 'REB%': 50.9, 'TOV%': 13.3, 'eFG%': 56.0, 'TS%': 59.4, 'PACE': 98.12, 'POSS': 6148, 'TEAM': 'NYK', 'PIE': 52.5}

   FGM  3PM  FTM
0    2    0    0

Precious Achiuwa, MAE: 1.6095449810327827, RMSE: 2.053011631971303
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   FGM  3PM  FTM
0    3    0    1

Drew Eubanks, MAE: 1.2885105113721318, RMSE: 1.4786455880229028
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   FGM  3PM  FTM
0    2    0    0

Nicolas Batum, MAE: 1.3257018211410272, RMSE: 1.5781908140665981
{'RANK': 4, 'OffRtg': 118.2, 'W': 40, 'L': 22, 'DefRtg': 114.0, 'NetRtg': 4.2, 'AST%': 62.2, 'AST/TO': 2.07, 'ASTRatio': 19.4, 'OREB%': 30.3, 'DREB%': 71.1, 'REB%': 50.9, 'TOV%': 13.3, 'eFG%': 56.0, 'TS%': 59.4, 'PACE': 98.12, 'POSS': 6148, 'TEAM': 'NYK', 'PIE': 52.5}

   FGM  3PM  FTM  FTA  FT%
0    1    1    0    0   15

c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.327e-01, tolerance: 7.144e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.054e-01, tolerance: 6.404e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.057e-01, tolerance: 7.476e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.526e-01, tolerance: 7.080e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.222e+00, tolerance: 6.890e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.350e+01, tolerance: 1.085e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.537e+01, tolerance: 1.107e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.140e+00, tolerance: 1.081e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.242e+01, tolerance: 9.480e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.665e+00, tolerance: 1.004e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.596e+01, tolerance: 9.132e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.270e+01, tolerance: 8.087e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.952e+00, tolerance: 8.612e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.674e-01, tolerance: 8.275e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.562e+01, tolerance: 5.780e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.966e+00, tolerance: 9.156e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.618e-01, tolerance: 9.073e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.972e-01, tolerance: 9.120e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.686e-01, tolerance: 9.297e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.038e-01, tolerance: 9.000e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.643e+00, tolerance: 7.208e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.837e+00, tolerance: 6.715e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.676e-01, tolerance: 6.772e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.211e-01, tolerance: 7.286e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.351e-01, tolerance: 7.239e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.526e+00, tolerance: 5.806e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.028e+01, tolerance: 5.985e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.403e+01, tolerance: 5.825e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.751e+01, tolerance: 6.034e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.872e+00, tolerance: 5.856e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.364e+00, tolerance: 3.175e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.728e+00, tolerance: 3.288e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.377e+00, tolerance: 3.264e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.415e+00, tolerance: 3.239e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.571e+00, tolerance: 2.220e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.573e+00, tolerance: 3.228e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.056e-01, tolerance: 3.533e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.463e+00, tolerance: 3.530e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.106e-01, tolerance: 3.412e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.765e-01, tolerance: 2.772e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.916e-01, tolerance: 2.554e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.799e-01, tolerance: 2.290e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.221e-01, tolerance: 2.552e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.866e-01, tolerance: 2.376e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.129e+00, tolerance: 2.338e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.603e-01, tolerance: 4.129e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.025e-02, tolerance: 3.957e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.096e+00, tolerance: 4.006e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.112e-01, tolerance: 4.133e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.293e-01, tolerance: 1.784e-02
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.026e-01, tolerance: 1.169e-01
  model = cd_fast.enet_coordinate_descent(
c:\Users\mandy\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.403e+00, tolerance: 1.181e-01
  model = cd_fast.enet_coordinate_descent(

Kevin Durant, MAE: 1.3949288391046366e-09, RMSE: 1.4276633297344952e-09
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   MIN_x  PTS  FGM  FGA  FG%  3PM  3P%  FTA  OREB  REB  AST  STL  BLK  TOV  PF  +/-  RANK   L  DefRtg  AST%  DREB%  REB%  TOV%   TS%   PIE  Date_in_Seconds  home_away
0     37   26    9   18   54    2   43    4     0    5    4    1    1    2   1    2     4  22   113.9  68.1   71.0  52.2  14.1  60.4  53.4       1738609920          1

Devin Booker, MAE: 1.3322676295501878e-15, RMSE: 1.88411095042053e-15
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   MIN_x  FGA  FG%  3PM  3P%  FTA  DREB  REB  AST  PF  NetRtg  AST%  DREB%  TOV%  eFG%    PACE
0     38   19   46    2   31    7     3    3    6   3     5.2  68.1   71.0  14.1  57.4  101.01

Nikola Jokic, MAE: 1.3764978393967195e-12, RMSE: 1.5900611080902489e-12
{'RANK': 17, 'OffRtg': 114.3, 'W': 29, 'L': 33, 'DefRtg': 116.3, 'NetRtg': -2.1, 'AST%': 67.6, 'AST/TO': 1.97, 'ASTRatio': 19.9, 'OREB%': 25.7, 'DREB%': 70.6, 'REB%': 49.1, 'TOV%': 14.1, 'eFG%': 56.0, 'TS%': 59.6, 'PACE': 98.82, 'POSS': 6177, 'TEAM': 'PHX', 'PIE': 50.1}

   MIN_x  FGM  FGA  3PM  3P%  FTM  FTA  FT%  OREB  DREB  AST  BLK  TOV  PF  +/-  RANK  GP   L  OffRtg  DefRtg  AST%  OREB%  DREB%  REB%  TOV%   PACE  Date_in_Seconds  home_away
0     35   10   16    1   35    4    5   73     2    10   11    0    3   2    7    17  62  33   114.3   116.3  67.6   25.7   70.6  49.1  14.1  98.82       1739141280          0

Jamal Murray, MAE: 5.269673586383306e-13, RMSE: 5.26998639380994e-13
{'RANK': 17, 'OffRtg': 114.3, 'W': 29, 'L': 33, 'DefRtg': 116.3, 'NetRtg': -2.1, 'AST%': 67.6, 'AST/TO': 1.97, 'ASTRatio': 19.9, 'OREB%': 25.7, 'DREB%': 70.6, 'REB%': 49.1, 'TOV%': 14.1, 'eFG%': 56.0, 'TS%': 59.6, 'PACE': 98.82, 'POSS': 6177, 'TEAM': 'PHX', 'PIE': 50.1}

   FGA  FG%  3PM  3P%  OREB  AST  TOV  AST/TO  TOV%  Date_in_Seconds
0   17   51    2   37     0    6    2    1.97  14.1       1739063520

Michael Porter Jr., MAE: 6.0845772864581704e-12, RMSE: 6.084709052227395e-12
{'RANK': 17, 'OffRtg': 114.3, 'W': 29, 'L': 33, 'DefRtg': 116.3, 'NetRtg': -2.1, 'AST%': 67.6, 'AST/TO': 1.97, 'ASTRatio': 19.9, 'OREB%': 25.7, 'DREB%': 70.6, 'REB%': 49.1, 'TOV%': 14.1, 'eFG%': 56.0, 'TS%': 59.6, 'PACE': 98.82, 'POSS': 6177, 'TEAM': 'PHX', 'PIE': 50.1}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTM  FTA  FT%  OREB  REB  AST  BLK  TOV  PF  +/-  OffRtg  AST%  OREB%  DREB%  POSS  team_pace  Date_in_Seconds  home_away
0     32    6   13   47    2   36    2    2   70     2    7    1    0    1   1    4   114.3  67.6   25.7   70.6  6177        101       1738830240          0

Bradley Beal, MAE: 1.2824334518506839e-14, RMSE: 1.5568842940908582e-14
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   MIN_x  FGA  FG%  3PM  3P%  FT%  REB  DefRtg  AST%  POSS  team_poss
0     31   12   50    1   39   65    3   113.9  68.1  6301       6177

Christian Braun, MAE: 2.6710237526389656e-15, RMSE: 2.8880507797453316e-15
{'RANK': 17, 'OffRtg': 114.3, 'W': 29, 'L': 33, 'DefRtg': 116.3, 'NetRtg': -2.1, 'AST%': 67.6, 'AST/TO': 1.97, 'ASTRatio': 19.9, 'OREB%': 25.7, 'DREB%': 70.6, 'REB%': 49.1, 'TOV%': 14.1, 'eFG%': 56.0, 'TS%': 59.6, 'PACE': 98.82, 'POSS': 6177, 'TEAM': 'PHX', 'PIE': 50.1}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FT%  OREB  DREB  BLK  +/-  RANK  OffRtg  NetRtg  AST%  REB%  TOV%  home_away
0     34    7   12   57    1   28   80     1     4    0    7    17   114.3    -2.1  67.6  49.1  14.1          0

Russell Westbrook, MAE: 4.488853733164433e-12, RMSE: 4.48893391278155e-12
{'RANK': 17, 'OffRtg': 114.3, 'W': 29, 'L': 33, 'DefRtg': 116.3, 'NetRtg': -2.1, 'AST%': 67.6, 'AST/TO': 1.97, 'ASTRatio': 19.9, 'OREB%': 25.7, 'DREB%': 70.6, 'REB%': 49.1, 'TOV%': 14.1, 'eFG%': 56.0, 'TS%': 59.6, 'PACE': 98.82, 'POSS': 6177, 'TEAM': 'PHX', 'PIE': 50.1}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTM  FT%  OREB  REB  AST  STL  BLK  TOV  +/-  RANK  DefRtg  AST%  AST/TO  DREB%   PACE  team_pace  Date_in_Seconds  home_away
0     28    5   11   48    1   29    1   61     1    5    5    0    0    3    3    17   116.3  67.6    1.97   70.6  98.82        101       1738419840          0

Aaron Gordon, MAE: 5.218048215738236e-15, RMSE: 5.218048215738236e-15
{'RANK': 17, 'OffRtg': 114.3, 'W': 29, 'L': 33, 'DefRtg': 116.3, 'NetRtg': -2.1, 'AST%': 67.6, 'AST/TO': 1.97, 'ASTRatio': 19.9, 'OREB%': 25.7, 'DREB%': 70.6, 'REB%': 49.1, 'TOV%': 14.1, 'eFG%': 56.0, 'TS%': 59.6, 'PACE': 98.82, 'POSS': 6177, 'TEAM': 'PHX', 'PIE': 50.1}

   FGA  FG%  3PM  3P%  FTM  FTA  FT%  OREB  PF   L   PACE
0    8   51    1   42    1    2   64     1   1  33  98.82

Bol Bol, MAE: 8.20282743459549e-12, RMSE: 8.202891712879002e-12
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   FGM  FGA  3PM  3P%  FTA  FT%  OREB  DREB  AST  STL  BLK  TOV  PF  RANK   W   L  OffRtg  NetRtg  AST%  DREB%  eFG%   TS%    PACE  Date_in_Seconds  home_away
0    3    6    1   27    0   26     0     3    0    0    1    0   0     4  40  22   119.1     5.2  68.1   71.0  57.4  60.4  101.01       1738864800          1

Nick Richards, MAE: 4.0937015155134206e-17, RMSE: 4.1784687351701864e-17
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   3PM  AST  TOV  PF  OREB%  DREB%  POSS  Date_in_Seconds  home_away
0    0    0    1   2   31.2   71.0  6301       1738916640          1

Grayson Allen, MAE: 2.5509422982890976e-10, RMSE: 3.4422667909547015e-10
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTM  FT%  OREB  DREB  AST  STL  TOV  PF  +/-   W   L  OffRtg  DefRtg  AST%  OREB%  DREB%  TOV%  eFG%    PACE  Date_in_Seconds  home_away
0     25    3    7   44    2   43    1   36     0     2    2    0    1   1    0  40  22   119.1   113.9  68.1   31.2   71.0  14.1  57.4  101.01       1738912320          1

Royce O'Neale, MAE: 8.957997283402605e-16, RMSE: 1.1352974897487174e-15
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTM  FTA  FT%  OREB  REB  AST  STL  BLK  TOV  +/-  RANK  DefRtg  AST%  ASTRatio  OREB%  DREB%   TS%    PACE  team_pace  home_away
0     25    3    8   40    2   40    0    0    5     0    3    1    1    0    0   -2     4   113.9  68.1      21.1   31.2   71.0  60.4  101.01         98          1

Mason Plumlee, MAE: 0.0, RMSE: 0.0
{'RANK': 4, 'OffRtg': 119.1, 'W': 40, 'L': 22, 'DefRtg': 113.9, 'NetRtg': 5.2, 'AST%': 68.1, 'AST/TO': 2.16, 'ASTRatio': 21.1, 'OREB%': 31.2, 'DREB%': 71.0, 'REB%': 52.2, 'TOV%': 14.1, 'eFG%': 57.4, 'TS%': 60.4, 'PACE': 101.01, 'POSS': 6301, 'TEAM': 'DEN', 'PIE': 53.4}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTM  FTA  FT%  OREB  REB  AST  STL  BLK  TOV  PF  +/-  RANK  GP   L  OffRtg  DefRtg  AST%  AST/TO  ASTRatio  OREB%  DREB%  REB%  TOV%  eFG%   TS%    PACE   PIE  team_pace  team_offrtg  team_poss  Date_in_Seconds  home_away
0     18    1    2   53    0    0    1    1   45     1    6    2    0    0    0   2    1     4  62  22   119.1   113.9  68.1    2.16      21.1   31.2   71.0  52.2  14.1  57.4  60.4  101.01  53.4         98          114       6177       1739288160          1

DeMar DeRozan, MAE: 2.500445006295616e-12, RMSE: 2.5005048044280505e-12
{'RANK': 22, 'OffRtg': 112.6, 'W': 26, 'L': 34, 'DefRtg': 114.7, 'NetRtg': -2.1, 'AST%': 70.2, 'AST/TO': 2.07, 'ASTRatio': 20.4, 'OREB%': 28.0, 'DREB%': 69.3, 'REB%': 48.9, 'TOV%': 14.0, 'eFG%': 53.9, 'TS%': 57.1, 'PACE': 100.21, 'POSS': 6038, 'TEAM': 'SAS', 'PIE': 50.3}

   FGA  FG%  3PM  3P%  OREB  BLK  AST/TO  DREB%  team_pace  Date_in_Seconds
0   16   49    1   35     0    0    2.07   69.3         99       1739063520

Devin Vassell, MAE: 2.4313884239290928e-14, RMSE: 2.6053601613584877e-14
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   MIN_x  FGM  FGA  3PM  3P%  FTA  FT%  OREB  REB  AST  STL  BLK  TOV  PF  +/-  RANK  GP  OffRtg  AST/TO  DREB%  REB%  TOV%   PIE  POSS  Date_in_Seconds
0     31    6   14    2   31    1   49     0    3    2    1    0    1   1   -3    15  62   115.8    1.99   72.7  51.1  13.4  50.9  6152       1739249280

De'Aaron Fox, MAE: 4.440892098500626e-15, RMSE: 6.282332143745565e-15
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTM  FTA  DREB  REB  AST  STL  BLK  PF  RANK   L  DefRtg  ASTRatio  OREB%  DREB%   TS%  team_offrtg  Date_in_Seconds  home_away
0     34    6   16   41    1   25    3    4     3    4    6    1    0   2    15  29   113.8      18.9   29.4   72.7  58.1          112       1739180160          1

Keldon Johnson, MAE: 4.6980535478921795e-15, RMSE: 5.990196617711264e-15
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   MIN_x  FGA  FG%  3PM  3P%  OREB  STL
0     21    8   47    1   38     1    0

Jonas Valanciunas, MAE: 2.162911941067894e-15, RMSE: 2.8576958410776923e-15
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   FGA  FG%  3PM  3P%  FT%  AST  team_offrtg
0    7   54    0   10   81    2          112

Keegan Murray, MAE: 1.8427521637019633e-12, RMSE: 1.8427850074246803e-12
{'RANK': 22, 'OffRtg': 112.6, 'W': 26, 'L': 34, 'DefRtg': 114.7, 'NetRtg': -2.1, 'AST%': 70.2, 'AST/TO': 2.07, 'ASTRatio': 20.4, 'OREB%': 28.0, 'DREB%': 69.3, 'REB%': 48.9, 'TOV%': 14.0, 'eFG%': 53.9, 'TS%': 57.1, 'PACE': 100.21, 'POSS': 6038, 'TEAM': 'SAS', 'PIE': 50.3}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FT%  OREB  REB  AST  STL  BLK  TOV  PF  +/-  OffRtg  DefRtg  eFG%    PACE  team_pace  Date_in_Seconds  home_away
0     31    4   10   46    1   33   28     1    5    1    1    0    0   2    0   112.6   114.7  53.9  100.21         99       1739063520          0

Keon Ellis, MAE: 4.575855917096816e-14, RMSE: 4.843242416350267e-14
{'RANK': 22, 'OffRtg': 112.6, 'W': 26, 'L': 34, 'DefRtg': 114.7, 'NetRtg': -2.1, 'AST%': 70.2, 'AST/TO': 2.07, 'ASTRatio': 20.4, 'OREB%': 28.0, 'DREB%': 69.3, 'REB%': 48.9, 'TOV%': 14.0, 'eFG%': 53.9, 'TS%': 57.1, 'PACE': 100.21, 'POSS': 6038, 'TEAM': 'SAS', 'PIE': 50.3}

   FGM  FGA  FG%  3PM  3P%  FTM  FT%  OREB  AST  BLK  TOV  PF  +/-  RANK  AST%  DREB%  TOV%  eFG%   TS%    PACE   PIE  POSS  team_offrtg  home_away
0    3    6   54    2   45    0   32     0    1    1    0   2   -2    22  70.2   69.3  14.0  53.9  57.1  100.21  50.3  6038          115          0

Harrison Barnes, MAE: 2.6339486147719526e-12, RMSE: 2.6339584531279654e-12
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTA  FT%  OREB  AST  STL  TOV  PF  +/-  RANK   W   L  OffRtg  AST%  DREB%  TOV%   TS%   PACE  Date_in_Seconds  home_away
0     25    4    8   47    2   40    1   42     1    1    0    0   0   -2    15  32  29   115.8  61.8   72.7  13.4  58.1  99.79       1739249280          1

Jeremy Sochan, MAE: 6.8472074607872555e-15, RMSE: 8.350198582959463e-15
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   FGA  FG%  3PM  3P%  FTA  DREB  STL  PF   W  DREB%  team_offrtg
0    6   56    0   31    1     3    0   2  32   72.7          112

Chris Paul, MAE: 2.549321620187816e-11, RMSE: 2.931198114302897e-11
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   MIN_x  FGM  FGA  3PM  3P%  FTM  FTA  FT%  DREB  AST  STL  BLK  TOV  PF  +/-   W  OffRtg  DefRtg  AST%  AST/TO  OREB%  DREB%  TOV%   PACE   PIE  team_offrtg  Date_in_Seconds  home_away
0     27    2    6    1   39    0    1   48     2    7    1    0    1   1   -1  32   115.8   113.8  61.8    1.99   29.4   72.7  13.4  99.79  50.9          112       1739249280          1

Jake LaRavia, MAE: 2.4144670183972e-15, RMSE: 2.975388460662843e-15
{'RANK': 22, 'OffRtg': 112.6, 'W': 26, 'L': 34, 'DefRtg': 114.7, 'NetRtg': -2.1, 'AST%': 70.2, 'AST/TO': 2.07, 'ASTRatio': 20.4, 'OREB%': 28.0, 'DREB%': 69.3, 'REB%': 48.9, 'TOV%': 14.0, 'eFG%': 53.9, 'TS%': 57.1, 'PACE': 100.21, 'POSS': 6038, 'TEAM': 'SAS', 'PIE': 50.3}

   MIN_x  FGM  FGA  3PM  3P%  FTM  FTA  OREB  REB  AST  STL  BLK  TOV  PF  +/-  RANK   W  AST%  OREB%  DREB%  TOV%  eFG%    PACE  POSS  team_offrtg
0     15    1    3    0   28    0    0     1    3    1    1    0    0   1    0    22  26  70.2   28.0   69.3  14.0  53.9  100.21  6038          115

Julian Champagnie, MAE: 3.4658831360445674e-11, RMSE: 3.465975225142927e-11
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTA  DREB  REB  AST  STL  BLK  PF  +/-  RANK   W  MIN_y  AST/TO  OREB%  DREB%   PACE   PIE  Date_in_Seconds  home_away
0     17    2    5   43    1   35    0     1    2    1    1    0   1    0    15  32   2995    1.99   29.4   72.7  99.79  50.9       1739249280          1

Trey Lyles, MAE: 1.2542543383705653e-14, RMSE: 1.3644438921769167e-14
{'RANK': 22, 'OffRtg': 112.6, 'W': 26, 'L': 34, 'DefRtg': 114.7, 'NetRtg': -2.1, 'AST%': 70.2, 'AST/TO': 2.07, 'ASTRatio': 20.4, 'OREB%': 28.0, 'DREB%': 69.3, 'REB%': 48.9, 'TOV%': 14.0, 'eFG%': 53.9, 'TS%': 57.1, 'PACE': 100.21, 'POSS': 6038, 'TEAM': 'SAS', 'PIE': 50.3}

   MIN_x  FGM  FGA  3PM  3P%  FTM  FT%  OREB  DREB  AST  STL  BLK  TOV  PF   L  MIN_y  OREB%  DREB%  eFG%  team_offrtg  home_away
0     14    1    4    0   33    0   25     0     3    1    0    0    0   1  34   3018   28.0   69.3  53.9          115          0

Bismack Biyombo, MAE: 0.0, RMSE: 0.0
{'RANK': 15, 'OffRtg': 115.8, 'W': 32, 'L': 29, 'DefRtg': 113.8, 'NetRtg': 2.0, 'AST%': 61.8, 'AST/TO': 1.99, 'ASTRatio': 18.9, 'OREB%': 29.4, 'DREB%': 72.7, 'REB%': 51.1, 'TOV%': 13.4, 'eFG%': 54.6, 'TS%': 58.1, 'PACE': 99.79, 'POSS': 6152, 'TEAM': 'SAC', 'PIE': 50.9}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTM  FTA  FT%  OREB  REB  AST  STL  BLK  TOV  PF  +/-  RANK  GP   L  OffRtg  DefRtg  AST%  AST/TO  ASTRatio  OREB%  DREB%  REB%  TOV%  eFG%   TS%   PACE   PIE  team_pace  team_offrtg  team_poss  Date_in_Seconds  home_away
0     14    1    2   42    0    0    0    0   14     1    4    1    0    0    0   1   -1    15  73  29   115.8   113.8  61.8    1.99      18.9   29.4   72.7  51.1  13.4  54.6  58.1  99.79  50.9        101          110       7344       1723140000          1

Markelle Fultz, MAE: 6.942031219146853e-16, RMSE: 7.041323832850291e-16
{'RANK': 22, 'OffRtg': 112.6, 'W': 26, 'L': 34, 'DefRtg': 114.7, 'NetRtg': -2.1, 'AST%': 70.2, 'AST/TO': 2.07, 'ASTRatio': 20.4, 'OREB%': 28.0, 'DREB%': 69.3, 'REB%': 48.9, 'TOV%': 14.0, 'eFG%': 53.9, 'TS%': 57.1, 'PACE': 100.21, 'POSS': 6038, 'TEAM': 'SAS', 'PIE': 50.3}

   FGA  3PM  AST%  team_pace  team_offrtg
0    6    0  70.2         99          116

James Harden, MAE: 3.987921104453562e-14, RMSE: 3.996654856172554e-14
{'RANK': 4, 'OffRtg': 118.2, 'W': 40, 'L': 22, 'DefRtg': 114.0, 'NetRtg': 4.2, 'AST%': 62.2, 'AST/TO': 2.07, 'ASTRatio': 19.4, 'OREB%': 30.3, 'DREB%': 71.1, 'REB%': 50.9, 'TOV%': 13.3, 'eFG%': 56.0, 'TS%': 59.4, 'PACE': 98.12, 'POSS': 6148, 'TEAM': 'NYK', 'PIE': 52.5}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTA  OREB  DREB  AST  STL  BLK  PF  +/-  RANK  OffRtg  DefRtg  ASTRatio  OREB%  TOV%  eFG%   PACE  team_pace  Date_in_Seconds
0     37    6   17   37    3   30    7     0     4    9    1    0   2    0     4   118.2   114.0      19.4   30.3  13.3  56.0  98.12         98       1739275200

Karl-Anthony Towns, MAE: 8.22675261247241e-13, RMSE: 8.226918969445166e-13
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   MIN_x  FGA  FG%  3PM  3P%  FTM  OREB  REB  AST  BLK  PF  DefRtg  OREB%  DREB%  Date_in_Seconds
0     36   16   47    1   36    4     3   12    2    0   3   109.7   28.5   73.0       1738730880

Kawhi Leonard, MAE: 2.1649348980190553e-15, RMSE: 3.188872858294072e-15
{'RANK': 4, 'OffRtg': 118.2, 'W': 40, 'L': 22, 'DefRtg': 114.0, 'NetRtg': 4.2, 'AST%': 62.2, 'AST/TO': 2.07, 'ASTRatio': 19.4, 'OREB%': 30.3, 'DREB%': 71.1, 'REB%': 50.9, 'TOV%': 13.3, 'eFG%': 56.0, 'TS%': 59.4, 'PACE': 98.12, 'POSS': 6148, 'TEAM': 'NYK', 'PIE': 52.5}

   FGA  FG%  3PM  3P%  FT%  OREB%  REB%   PACE
0   15   46    1   33   61   30.3  50.9  98.12

Mikal Bridges, MAE: 2.429298463318346e-14, RMSE: 2.6633987177955573e-14
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTM  FT%  OREB  REB  AST  STL  BLK  TOV  PF  +/-  RANK  DefRtg  NetRtg  AST%  OREB%  DREB%   PACE  team_pace  team_poss  home_away
0     35    6   13   47    1   32    0   32     0    3    3    0    0    1   1    0    14   109.7     2.2  60.8   28.5   73.0  98.71         98       6148          1

Bogdan Bogdanovic, MAE: 3.597122599785507e-14, RMSE: 3.8360157579890285e-14
{'RANK': 4, 'OffRtg': 118.2, 'W': 40, 'L': 22, 'DefRtg': 114.0, 'NetRtg': 4.2, 'AST%': 62.2, 'AST/TO': 2.07, 'ASTRatio': 19.4, 'OREB%': 30.3, 'DREB%': 71.1, 'REB%': 50.9, 'TOV%': 13.3, 'eFG%': 56.0, 'TS%': 59.4, 'PACE': 98.12, 'POSS': 6148, 'TEAM': 'NYK', 'PIE': 52.5}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTA  FT%  OREB  REB  AST  STL  BLK  TOV  PF  +/-  RANK  OffRtg  DefRtg  AST%  AST/TO  OREB%  REB%  TOV%   PACE  POSS  team_offrtg  home_away
0     25    3   10   38    1   32    1   32     0    2    2    0    0    1   2    0     4   118.2   114.0  62.2    2.07   30.3  50.9  13.3  98.12  6148          111          0

OG Anunoby, MAE: 7.850940342279955e-10, RMSE: 9.42076814236561e-10
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTM  OREB  DREB  AST  STL  TOV  PF  +/-   L  AST%  AST/TO  OREB%  DREB%  TOV%   TS%   PACE   PIE  team_pace  Date_in_Seconds  home_away
0     36    5   12   46    2   34    2     1     2    2    1    1   2    1  29  60.8    1.59   28.5   73.0  15.7  57.8  98.71  50.9         98       1738393920          1

Ivica Zubac, MAE: 0.0, RMSE: 0.0
{'RANK': 4, 'OffRtg': 118.2, 'W': 40, 'L': 22, 'DefRtg': 114.0, 'NetRtg': 4.2, 'AST%': 62.2, 'AST/TO': 2.07, 'ASTRatio': 19.4, 'OREB%': 30.3, 'DREB%': 71.1, 'REB%': 50.9, 'TOV%': 13.3, 'eFG%': 56.0, 'TS%': 59.4, 'PACE': 98.12, 'POSS': 6148, 'TEAM': 'NYK', 'PIE': 52.5}

   MIN_x  FGA  FG%  FTA  FT%  OREB  REB  AST  STL  BLK  TOV  PF  +/-   W  DefRtg  AST%  DREB%  REB%  TOV%   PACE  team_pace  Date_in_Seconds  home_away
0     32   12   61    2   69     3   12    2    1    1    1   2    5  40   114.0  62.2   71.1  50.9  13.3  98.12         98       1739270880          0

Miles McBride, MAE: 2.383886534164739e-15, RMSE: 2.7957357295414075e-15
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTA  OREB  TOV  PF  GP  OffRtg  DefRtg  AST%  ASTRatio  DREB%  REB%  TOV%  eFG%   PACE  team_pace  home_away
0     23    3    7   37    1   24    0     0    0   1  62   111.9   109.7  60.8      18.0   73.0  51.0  15.7  54.1  98.71         98          1

Josh Hart, MAE: 8.521311900174412e-10, RMSE: 1.0025069851619148e-09
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTA  FT%  DREB  REB  AST  STL  BLK  TOV  PF  +/-  RANK   L  DefRtg  NetRtg  AST%  AST/TO  DREB%  REB%  TOV%  eFG%   PACE  POSS  Date_in_Seconds  home_away
0     38    5   11   49    0   18    3   52     7   10    5    1    0    2   2   -2    14  29   109.7     2.2  60.8    1.59   73.0  51.0  15.7  54.1  98.71  6147       1738847520          1

Cameron Payne, MAE: 5.234835563671022e-12, RMSE: 5.234985472103618e-12
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   FGM  FGA  FG%  3PM  3P%  FT%  OREB  DREB  STL  BLK  PF  +/-  RANK   W  AST%  OREB%  DREB%  REB%  TOV%  eFG%   TS%   PACE   PIE  team_pace  Date_in_Seconds
0    2    6   33    0   24   43     0     1    0    0   1    2    14  33  60.8   28.5   73.0  51.0  15.7  54.1  57.8  98.71  50.9         98       1739171520

Amir Coffey, MAE: 6.974978293507095e-13, RMSE: 6.975655220390512e-13
{'RANK': 4, 'OffRtg': 118.2, 'W': 40, 'L': 22, 'DefRtg': 114.0, 'NetRtg': 4.2, 'AST%': 62.2, 'AST/TO': 2.07, 'ASTRatio': 19.4, 'OREB%': 30.3, 'DREB%': 71.1, 'REB%': 50.9, 'TOV%': 13.3, 'eFG%': 56.0, 'TS%': 59.4, 'PACE': 98.12, 'POSS': 6148, 'TEAM': 'NYK', 'PIE': 52.5}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTM  FT%  DREB  AST  STL  TOV  PF  +/-  RANK  DefRtg  AST%  REB%  TOV%  eFG%   PACE  team_pace  Date_in_Seconds  home_away
0     26    3    7   41    1   33    2   70     1    1    0    0   2   -4     4   114.0  62.2  50.9  13.3  56.0  98.12         98       1739180160          0

Kris Dunn, MAE: 1.9496588729117115e-09, RMSE: 2.2454526186763824e-09
{'RANK': 4, 'OffRtg': 118.2, 'W': 40, 'L': 22, 'DefRtg': 114.0, 'NetRtg': 4.2, 'AST%': 62.2, 'AST/TO': 2.07, 'ASTRatio': 19.4, 'OREB%': 30.3, 'DREB%': 71.1, 'REB%': 50.9, 'TOV%': 13.3, 'eFG%': 56.0, 'TS%': 59.4, 'PACE': 98.12, 'POSS': 6148, 'TEAM': 'NYK', 'PIE': 52.5}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTM  FTA  FT%  DREB  AST  STL  BLK  TOV  PF  +/-  RANK  OffRtg  NetRtg  AST%  ASTRatio  DREB%  REB%  TOV%   PACE  team_pace  Date_in_Seconds
0     23    2    5   41    0   35    0    0    7     2    3    2    0    0   2    2     4   118.2     4.2  62.2      19.4   71.1  50.9  13.3  98.12         98       1738882080

Precious Achiuwa, MAE: 1.3244464166862981e-11, RMSE: 1.324470544814918e-11
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   MIN_x  FGM  FGA  FG%  3PM  3P%  FTM  FTA  FT%  OREB  REB  AST  STL  BLK  TOV  PF  +/-  RANK  GP   L  OffRtg  DefRtg  AST%  AST/TO  ASTRatio  OREB%  DREB%  REB%  TOV%  eFG%   TS%   PACE   PIE  team_pace  team_offrtg  team_poss  Date_in_Seconds  home_away
0     26    3    7   46    0   10    1    1   38     2    6    1    1    0    0   1   -2    14  62  29   111.9   109.7  60.8    1.59      18.0   28.5   73.0  51.0  15.7  54.1  57.8  98.71  50.9         98          118       6148       1738748160          1

Drew Eubanks, MAE: 4.4322043109054065e-17, RMSE: 4.574173905854816e-17
{'RANK': 14, 'OffRtg': 111.9, 'W': 33, 'L': 29, 'DefRtg': 109.7, 'NetRtg': 2.2, 'AST%': 60.8, 'AST/TO': 1.59, 'ASTRatio': 18.0, 'OREB%': 28.5, 'DREB%': 73.0, 'REB%': 51.0, 'TOV%': 15.7, 'eFG%': 54.1, 'TS%': 57.8, 'PACE': 98.71, 'POSS': 6147, 'TEAM': 'LAC', 'PIE': 50.9}

   FGA  3PM
0    4    0

Nicolas Batum, MAE: 1.0092225102981664e-13, RMSE: 1.0162511134295764e-13
{'RANK': 4, 'OffRtg': 118.2, 'W': 40, 'L': 22, 'DefRtg': 114.0, 'NetRtg': 4.2, 'AST%': 62.2, 'AST/TO': 2.07, 'ASTRatio': 19.4, 'OREB%': 30.3, 'DREB%': 71.1, 'REB%': 50.9, 'TOV%': 13.3, 'eFG%': 56.0, 'TS%': 59.4, 'PACE': 98.12, 'POSS': 6148, 'TEAM': 'NYK', 'PIE': 52.5}

   FGM  FGA  FG%  3PM  3P%  REB  AST  BLK  TOV  PF  RANK  DefRtg  REB%   PACE  POSS  team_pace  home_away
0    1    2   31    1   34    2    0    0    0   1     4   114.0  50.9  98.12  6148         98          0

                Player  REB      RMSE_reb  AST  RMSE_ast  PTS      RMSE_pts  3PM      RMSE_3pm  total_points
0         Kevin Durant    5  3.140185e-16    4  1.933913   17  3.635373e+00    2  1.427663e-09            28
1         Devin Booker    3  8.881784e-16    8  1.422423   19  4.397920e+00    2  1.884111e-15            32
2         Nikola Jokic   12  8.881784e-16   11  2.994381   16  4.259554e-15    0  1.590061e-12            39
3         Jamal Murray    1  7.691851e-16    5  1.369184   17  2.622333e+00    1  5.269986e-13            24
4   Michael Porter Jr.    6  4.351168e-15    2  1.048149   12  5.352331e+00    1  6.084709e-12            21
5         Bradley Beal    2  9.420555e-16    3  0.452360   12  7.533894e-01    0  1.556884e-14            17
6      Christian Braun    5  8.881784e-16    3  2.071728   11  3.887758e+00    0  2.888051e-15            19
7    Russell Westbrook    3  8.005932e-16    5  1.822185   10  2.867766e+00    1  4.488934e-12            19
8         Aaron Gordon    2  0.000000e+00    2  0.501394    7  5.059191e+00    1  5.218048e-15            12
9              Bol Bol    2  3.092723e-15    1  1.026192    5  2.191970e+00    1  8.202892e-12             9
10       Nick Richards    9  0.000000e+00    0  0.661617    4  7.592845e-01    0  4.178469e-17            13
11       Grayson Allen    2  4.440892e-16    2  0.787583    7  3.241864e+00    1  3.442267e-10            12
12       Royce O'Neale    2  2.288783e-16    2  0.941930    7  1.794053e+00    2  1.135297e-15            13
13       Mason Plumlee    5  1.256074e-15    1  1.165873    2  1.133287e+00    0  0.000000e+00             8
14       DeMar DeRozan    3  6.661338e-16    3  1.714049   16  5.158364e+00    1  2.500505e-12            23
15       Devin Vassell    3  2.220446e-16    3  1.685174   14  2.664535e-15    1  2.605360e-14            21
16        De'Aaron Fox    3  4.440892e-16    5  1.457059   15  1.719486e+00    1  6.282332e-15            24
17      Keldon Johnson    3  0.000000e+00    1  2.059496    9  1.876873e+00    1  5.990197e-15            14
18   Jonas Valanciunas    7  1.256074e-15    1  1.312281    7  3.084079e+00    0  2.857696e-15            15
19       Keegan Murray    5  6.661338e-16    1  1.291189    9  1.356121e+00    0  1.842785e-12            15
20          Keon Ellis    2  0.000000e+00    1  1.384709    6  2.757185e+00    1  4.843242e-14            10
21     Harrison Barnes    4  5.438960e-16    1  0.875346    8  1.130057e+00    2  2.633958e-12            15
22       Jeremy Sochan    5  2.220446e-16    2  1.277979    7  3.312647e+00    0  8.350199e-15            14
23          Chris Paul    2  9.930137e-16    7  2.228853    5  2.479040e+00    0  2.931198e-11            14
24        Jake LaRavia    3  9.930137e-16    2  1.657990    3  8.776219e-01    0  2.975388e-15             8
25   Julian Champagnie    0  3.140185e-16    0  1.750221    5  1.900713e+00    1  3.465975e-11             6
26          Trey Lyles    3  1.025580e-15    0  2.241846    3  1.955679e+00    0  1.364444e-14             6
27     Bismack Biyombo    3  1.998401e-15    0  0.994775    2  1.090707e+00    0  0.000000e+00             5
28      Markelle Fultz    0  9.614813e-17    1  1.600739    5  8.802011e-01    0  7.041324e-16             6
29        James Harden    4  1.754012e-15    7  2.292451   14  4.485397e+00    3  3.996655e-14            28
30  Karl-Anthony Towns   12  1.848891e-15    2  2.625976   15  2.728654e+00    0  8.226919e-13            29
31       Kawhi Leonard    4  2.349899e-15    2  1.659143   14  2.012421e+00    1  3.188873e-15            21
32       Mikal Bridges    1  2.808667e-16    3  2.877575   13  2.517327e+00    0  2.663399e-14            17
33   Bogdan Bogdanovic    1  3.972055e-16    2  2.108874    9  4.000347e+00    0  3.836016e-14            12
34          OG Anunoby    3  9.729507e-16    2  1.604009   11  3.513364e+00    1  9.420768e-10            17
35         Ivica Zubac   11  1.776357e-15    2  1.394429   10  2.621120e+00    0  0.000000e+00            23
36       Miles McBride    1  7.021667e-16    1  1.328977    7  1.384322e+00    1  2.795736e-15            10
37           Josh Hart    9  2.281772e-15    5  3.898920    9  2.094269e+00    0  1.002507e-09            23
38       Cameron Payne    0  1.719950e-16    2  1.479839    5  1.616670e+00    0  5.234985e-12             7
39         Amir Coffey    1  5.347542e-16    0  1.170574    6  2.300166e+00    0  6.975655e-13             7
40           Kris Dunn    3  1.801164e-15    2  1.231379    5  1.699638e+00    0  2.245453e-09            10
41    Precious Achiuwa    6  1.281975e-15    1  0.972378    5  2.053012e+00    0  1.324471e-11            12
42        Drew Eubanks    4  1.986027e-15    0  0.881993    3  1.478646e+00    0  4.574174e-17             7
43       Nicolas Batum    2  7.691851e-16    0  0.866623    3  1.578191e+00    1  1.016251e-13             6